<?php
/* +**********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.1
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is: vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 * ***********************************************************************************/

$languageStrings = array(
	'LBL_PUBLISHER' => '發佈者',
	'LBL_LICENSE' => '授權許可',
	'LBL_PUBLISHED_ON' => '發表於',
	'LBL_INSTALL' => '安裝',
	'LBL_UPGRADE' => '升級',
	'LBL_VERSION' => '版本',
	'LBL_DECLINE' => '拒絕',
	'LBL_ACCEPT_AND_INSTALL' => '接受並安裝',
	'LBL_OK' => 'OK',
	'LBL_EXTENSION_NOT_COMPATABLE' => '此擴展並不相容',
	'LBL_INVALID_FILE' => '無效文件',
	'LBL_NO_LICENSE_PROVIDED' => '沒有提供授權許可',
	'LBL_INSTALLATION' => '安裝',
	'LBL_FAILED' => '失敗',
	'LBL_SUCCESSFULL' => '成功',
	'LBL_INSTALLATION_LOG' => '安裝日誌',
	'LBL_UPDATED_MODULE' => ' 模組已成功更新。',
	'LBL_UPDATING_MODULE' => '更新模組',
	'LBL_MARKET_PLACE' => '市集',

	//Extension Store translations
	'LBL_VTIGER_EXTENSION_STORE' => 'Vtiger 擴展應用市集',
	'LBL_SEARCH_FOR_AN_EXTENSION'  => '搜尋擴展應用...',
	'LBL_DOWNLOADS' => '下載',
	'LBL_NO_EXTENSIONS_FOUND' => '沒有找到擴展應用',
	'LBL_REGISTER_TO_MARKET_PLACE' => '註冊到市集',
	'LBL_MARKETPLACE_REGISTRATION' => '市集註冊',
	'LBL_MARKETPLACE_LOGIN' => '市集登入',
	'LBL_NEW_TO_MARKETPLCAE' => '第一次到市集?',
	'LBL_CREATE_AN_ACCOUNT' => '建立新用戶',
	'LBL_SETUP_CARD_DETAILS' => '設定信用卡資訊',
	'LBL_SETUP_CARD' => '設定信用卡',
	'LBL_CARD_NUMBER' => '信用卡號',
	'LBL_EXP_MONTH' => '到期月',
	'LBL_EXP_YEAR' => '到期年',
	'LBL_CVC_CODE' => '信用卡背面後3碼',
	'LBL_RESET' => '重新設定',
	'LBL_EXTENSION_STORE' => '擴展應用市集',
	'LBL_INSTALLED' => '已安裝',
	'LBL_UPDATE_CARD_DETAILS' => '更新信用卡資訊',
	'LBL_BY' => '由',
	'LBL_RATINGS' => '評價',
	'LBL_DESCRIPTION' => '描述',
	'LBL_AUTHOR_INFORMATION' => '作者資訊',
	'LBL_AUTHOR_NAME' => '作者名稱',
	'LBL_PHONE' => '電話',
	'LBL_EMAIL' => 'Email',
	'LBL_SCREEN_SHOTS' => '截圖',
	'LBL_CUSTOMER_RATINGS' => '用戶評價',
	'LBL_CUSTOMER_REVIEWS' => '用戶意見',
	'LBL_WRITE_A_REVIEW' => '留下意見',
	'LBL_CUSTOMER_REVIEW' => '用戶意見',
	'LBL_REVIEW' => '意見',
	'LBL_CUSTOMERS_REVIEWED' => '用戶已留下意見',
	'LBL_SINGLE_CUSTOMER_REVIEWED' => '1個用戶意見',
	'LBL_INSTALLATION_FAILED' => '安裝失敗',
	'LBL_SUCCESSFULL_INSTALLATION' => '安裝成功',
	'LBL_INSTALL_FROM_ZIP' => '安裝自壓縮檔案',
	'LBL_MORE_DETAILS' => '更多內容',
	'Install' => '安裝',
	'Upgrade' => '升級',
	'LBL_RATE_IT' => '評價去',
	'LBL_UNINSTALL' => '反安裝',
	'LBL_LAUNCH' => '開啟',
	'LBL_SIGN_UP_FOR_FREE' => '註冊免費',
	'LBL_EMAIL_ADDRESS' => 'Email地址',
	'LBL_FIRST_NAME' => '名字',
	'LBL_LAST_NAME' => '英文名',
	'LBL_COMPANY_NAME' => '公司名稱',
	'LBL_PASSWORD' => '密碼',
	'LBL_CONFIRM_PASSWORD' => '確認密碼',
	'LBL_REGISTER' => '註冊',
	'LBL_EXTENSION_STORE_LOGIN' => '擴展應用市集 登入',
	'LBL_REMEMBER_ME' => '記得我',
	'LBL_TRY_IT' => '試試吧',
	'LBL_TRIAL_INSTALLED' => '試用安裝',
	'LBL_BUY' => '購買 ',
	'LBL_LOGIN_TO_MARKET_PLACE' => '市集登入',
	'LBL_LOGIN' => '登入',
	'LBL_PHP_EXTENSION_LOADER_IS_NOT_AVAIABLE' => '請安裝擴展加載器',
	'LBL_INSTALL_EXTENSION_LOADER' => '安裝擴展加載器',
	'LBL_TO_CONTINUE_USING_EXTENSION_STORE' => '若要繼續使用擴展應用市集，請安裝 ',
	'LBL_DOWNLOAD' => '下載',
	'LBL_COMPATIABLE_EXTENSION' => ' 並啟用為zend_extension。',
	'LBL_MORE_DETAILS_ON_INSTALLATION' => '安裝的詳細資訊 ',
	'LBL_READ_HERE' => '了解這裡',
	'LBL_REVIEWS' => '意見',
	'LBL_SIGNUP_FOR_MARKET_PLACE' => '為市集註冊',
	'LBL_UNAUTHORIZED' => '未授權',
	'LBL_EXPIRY_DATE'  => '終止日期',
	'LBL_LOGOUT' => '登出',

	'firstname' => '名字',
	'lastname' => '英文名',
	'email' => 'Email',
	'company' => '公司',
	'Phone' => '電話',
	'Website' => '網站',
	'LBL_SECURITY_CODE' => '安全碼',
	'LBL_WHAT_IS_SECURITY_CODE' => '什麼是安全碼 ?',
	'LBL_CARD_NUMBER_PLACEHOLDER' => '信用卡上共16個數字',
	'LBL_SECURITY_CODE_HELP_CONTENT' => '確認信用卡背面後三碼 (CVV Number)為驗證碼',
	'LBL_ENTER_REGISTERED_EMAIL' => '輸入您註冊時電子郵件',
	'LBL_RESET_PASSWORD_LINK_EMAILED' => '重置密碼已發送到您的電子信箱！',
	'LBL_FORGOT_PASSWORD' => '忘記密碼',
	'LBL_ALREADY_INSTALLED_MODULE_BUILDER' => '已透過模組產生器建立',
	'LBL_REVIEW_RESTRICTED' => '審查受到限制',
);
$jsLanguageStrings = array(
	'JS_PLEASE_SETUP_CARD_DETAILS_TO_INSTALL_THIS_EXTENSION' => '要安裝這個擴展，請設定信用卡的詳細訊息',
	'JS_UPDATE_CARD_DETAILS' => '更新信用卡訊息',
	'JS_ON' => '於',
	'JS_RATINGS' => '評價',
	'JS_INSTALLED' => '已安裝',
	'JS_TRIAL_INSTALLED' => '試用安裝',
	'JS_PLEASE_INSTALL_EXTENSION_LOADER_TO_INSTALL_THIS_EXTENSION_FROM_BELOW_LINK' => '請安裝擴展加載器，以便從下面的連結安裝該擴展',
	'JS_PLEASE_LOGIN_TO_MARKETPLACE_FOR_INSTALLING_EXTENSION' => '請先登入市集才能安裝擴展',
	'JS_PLEASE_SETUP_CARD_DETAILS_TO_INSTALL_EXTENSION' => '請先設定信用卡才能安裝擴展',
	'JS_PLEASE_LOGIN_TO_MARKETPLACE_FOR_UNINSTALLING_EXTENSION' => '請先登入市集才能反安裝擴展',
	'JS_LBL_ARE_YOU_SURE_YOU_WANT_TO_INSTALL_THIS_EXTENSION' => '您確定要安裝此擴展嗎？',  
	'JS_CARD_DETAILS_UPDATED' => '信用卡訊息已更新！',  
'JS_LBL_ARE_YOU_SURE_YOU_WANT_TO_LOGOUT_FROM_EXTENSION' => '您確定要從擴展市集登出嗎？',
	'JS_PASSWORDS_MISMATCH' => "密碼不符合!",
	'JS_ARE_YOU_SURE_UNINSTALL' => '您確定要反安裝此擴展嗎',
	'JS_ARE_YOU_SURE_INSTALL' => '您確定要安裝次擴展嗎',
);
/*+***********************************************************************************
 * 臺灣繁體中文語言包 - Extension Store 擴展應用市集
 * 版本: 7.1.0 
 * 作者: Loki Jiang | https://www.facebook.com/groups/vTigerCRMtoTaiwan/
 * 更新日期: 2018-03-07
 *************************************************************************************/