<?php
/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 *************************************************************************************/
$languageStrings = array(
	'LayoutEditor' => '佈局編輯',
	'LBL_FIELDS_AND_LAYOUT_EDITOR' => '欄位和佈局編輯',
	'LBL_CREATE_CUSTOM_FIELD' => '建立自訂欄位',
	'LBL_DETAILVIEW_LAYOUT' => '詳細資訊顯示佈局',
	'LBL_ARRANGE_RELATED_TABS' => '排列相關標籤',
	'LBL_ADD_CUSTOM_FIELD' => '新增自訂欄位',
	'LBL_ADD_CUSTOM_BLOCK' => '新增自訂區塊',
	'LBL_SAVE_FIELD_SEQUENCE' => '儲存欄位順序',
	'LBL_BLOCK_NAME' => '區塊名稱',
	'LBL_ADD_AFTER' => '新增此樣板後面',
	'LBL_ACTIONS' => '啟動',
	'LBL_ALWAYS_SHOW' => '總是顯示',
    'LBL_SHOW_INACTIVE_FIELDS' => '顯示無效欄位',
	'LBL_SHOW_HIDDEN_FIELDS' => '顯示隱藏欄位',
	'LBL_DELETE_CUSTOM_BLOCK' => '刪除自訂區塊',
	'LBL_MANDATORY_FIELD' => '必填欄位',
	'LBL_ACTIVE' => '啟動',
	'LBL_QUICK_CREATE' => '快速建立',
	'LBL_SUMMARY_FIELD' => '摘要顯示',
    'LBL_KEY_FIELD_VIEW' => '關鍵欄位顯示',
	'LBL_MASS_EDIT' => '批次編輯',
	'LBL_DEFAULT_VALUE' => '預設值',
	'LBL_SELECT_FIELD_TYPE' => '選擇欄位類型',
	'LBL_LABEL_NAME' => '標籤名',
	'LBL_LENGTH' => '長度',
	'LBL_DECIMALS' => '小數',
	'LBL_ENTER_PICKLIST_VALUES' => '輸入下拉選單值..',
	'LBL_PICKLIST_VALUES' => '下拉選單值',
	'LBL_INACTIVE_FIELDS' => '隱藏的欄位', 
	'LBL_REACTIVATE' => '重新啟動',
	'LBL_ARRANGE_RELATED_LIST' => '排列相關列表',
	'LBL_SELECT_MODULE_TO_ADD' => '選擇要新增的模組',
    'LBL_SELECT_HIDDEN_MODULE' => '選擇隱藏的模組',
	'LBL_NO_RELATED_INFORMATION' => '沒有相關資訊',
	'LBL_RELATED_LIST_INFO' => '拖曳模組進行重新排序',
	'LBL_REMOVE_INFO' => '點擊關閉圖示將從列表中移除模組',
	'LBL_ADD_MODULE_INFO' => '從移除的模組中選擇模組可重新新增到列表中',
    'LBL_MANY_MANY_TEXT' => '多對多關係僅適用於 %s 和 %s',
	'LBL_SELECT_MODULE' => '選擇模組..',
	'LBL_DUPLICATES_EXIST' => '區塊名稱已存在',
	'LBL_NON_ROLE_BASED_PICKLIST' => '不是基於角色的選取列表',
	'LBL_DUPLICATE_FIELD_EXISTS' => '重覆的欄位已存在',
	'LBL_WRONG_FIELD_TYPE' => '欄位類型錯誤',
	'LBL_ROLE_BASED_PICKLIST' => '基於角色的選取列表',
	'LBL_CLICK_HERE_TO_EDIT' => '點擊此處編輯',
    'LBL_EDIT_FIELD' => '編輯欄位屬性：%s',

	//Field Types
	'Text'=>'文字',
	'Decimal'=>'小數',
	'Integer'=>'整數',
	'Percent'=>'百分比',
	'Currency'=>'幣別',
	'Date'=>'日期',
	'Email'=>'Email',
	'Phone'=>'電話',
	'PickList'=>'下拉選單',
	'MultiSelectCombo'=>'多選組合框',
	'URL' => '網址',
	'Checkbox' => '勾選方塊',
	'TextArea' => '文字區域',
	'Skype'=>'Skype',
	'Time'=>'時間',
	
	//Translation for module
	'Calendar' => '任務',
	'LBL_FIELD_COULD_NOT_BE_CREATED'=>'欄位 %s 無法建立',
	'SELECT_MODULE' => '選擇模組',
    
    //Related Lists 
    'LBL_RELATION_SHIPS' => '關聯',
    'LBL_ADD_RELATIONSHIP' => '增加關聯',
    'LBL_RELATED_MODULE' => '關聯模組',
    'LBL_ADDING_RELATIONSHIP' => '為 %s 增加關聯',
    'LBL_SELECTED_RELATED_MODULE' => '選擇相關模組',
    'LBL_SELECTED_RELATION_TYPE' => '選擇關聯類型',
    'ONE_ONE_AND_MANY_ONE_RELATIONSHIP' => '一對一 & 多對一關係',
    'ONE_MANY_RELATIONSHIP' => '一對多 & 多對多關係',
    '1-1' => '一對一',
    '1-N' => '一對多',
    'N-1' => '多對一',
    'N-N' => '多對多',
    
	
	//New layout translations
	'LBL_FIELD_TYPES'                   => '欄位類型', 
	'LBL_BASIC_FIELDS'             => '基本欄位', 
	'LBL_MANDATORY'                => '必填欄位', 
	'LBL_PROPERTIES'               => '屬性', 
	'LBL_DRAG_UI_TYPE'             => '拖曳欄位至此', 
	'LBL_RELATION_FIELDS'          => '關聯欄位', 
	'LBL_SELECT_BLOCK'             => '選擇區塊', 
    'LBL_RELATION_ADDED_SUCCESS'   => '添加關聯成功',
    
    'FIELD_NAME_IN_PRIMARY_MODULE' => '%s 的關聯欄位',
    'FIELD_NAME_IN_RELATED_MODULE' => '%s 的關聯欄位',
    'TAB_IN_PRIMARY_MODULE'        => '%s 的表格/標簽',
    'TAB_IN_RELATED_MODULE'        => '%s 的表格/標簽',
    
    'LBL_DETAIL_VIEW'              => '詳細視圖',
    'LBL_EXPANDED'                 => '展開',
    'LBL_COLLAPSED'                => '折疊',
    
    'LBL_FILED_IN_PRIMARY_HELP_TEXT' => '%s 模組的參考欄位',
    'LBL_TAB_IN_PRIMARY_HELP_TEXT'   => '%s 模組的表格/標簽',
    'LBL_FILED_IN_RELATED_HELP_TEXT' => '%s 模組的參考欄位',
    'LBL_TAB_IN_RELATED_HELP_TEXT'   => '%s 模組的表格/標簽',
    'LBL_NO_RELATION_TYPE'         => '這種類型的關係不存在',

	'LBL_CREATE_ITEM_CUSTOM_FIELD' => '建立行項目的自訂欄位',
	'LBL_MAP_PRODUCT_FIELD' => '映射到產品欄位',
	'LBL_MAP_SERVICE_FIELD' => '映射到服務欄位',
	'LBL_ENABLE_TO_MAP_PRODUCT_FIELD' => '啟用映射產品欄位',
	'LBL_ENABLE_TO_MAP_SERVICE_FIELD' => '啟用映射服務欄位',
    
    //Vtiger7 Strings
    'LBL_NO_RELATED_INFO' => '沒有關聯關係',
    'LBL_ADD_NEW_FIELD_HERE' => '增加新欄位',
    'LBL_SAVE_LAYOUT' => '儲存布局',
    'LBL_SHOW_FIELD' => '顯示欄位',
    'LBL_ENABLE_OR_DISABLE_FIELD_PROP' => '啟用/停用欄位屬性',
    'LBL_PROP_MANDATORY' => '必填',
    'LBL_DEFAULT_VALUE_NOT_SET' => '默認值未設置',
    'LBL_INFO' => '資訊',
    'LBL_PRODUCTFIELDDEFAULTVALUE' => ' (產品)',
    'LBL_SERVICEFIELDDEFAULTVALUE' => ' (服務)',
    'LBL_SHOW_THIS_FIELD_IN' => '點擊這裡在 %s 視圖中顯示此欄位',
    'LBL_MAKE_THIS_FIELD' => '點擊這裡使欄位 %s',
    'LBL_HIDE_THIS_FIELD_IN' => '點擊這裡在 %s 視圖中隱藏此欄位',
    'LBL_NOT_MAKE_THIS_FIELD' => '點擊這裡使欄位不 %s',
    'LBL_TAB_NAME_HELP_TEXT' => '%s 的列表顯示在 %s 記錄中',
    'LBL_TAB_NAME_TEXT' => '%s 的標簽名在 %s 記錄中',
    'LBL_FILED_NAME_HELP_TEXT' => '%s 的一個參考欄位在 %s 記錄中將被添加',
    'LBL_FIELD_NAME_TEXT' => '%s 的欄位名在 %s 記錄中',
	'LBL_COLLAPSE_BLOCK' => '折疊區塊',
	'LBL_COLLAPSE_BLOCK_DETAIL_VIEW' => '在詳細視圖中折疊區塊',
    'LBL_HEADER' => '頭部',
    'LBL_DETAIL_HEADER' => '記錄首項',
    'LBL_HEADER_FIELD' => '首項視圖',

	'LBL_DUPLICATE_HANDLING' => '防止重複',
	'LBL_DUPLICATE_CHECK' => '啟用重複檢查',
	'LBL_DUPLICATION_INFO_MESSAGE' => '預防重複功能只能防止用戶和擴展應用於建立新的重複記錄時作用。從匯入和工作流程所建立的記錄將不會被檢查到重複。<br> <br>可使用模組頁面的"查找重複"功能來刪除現有重複記錄。',
	'LBL_SELECT_FIELDS_FOR_DUPLICATION' => '選擇要檢查重複記錄的單一欄位',
	'LBL_SELECT_FIELDS' => '選擇欄位',
	'LBL_MAX_3_FIELDS' => '最多3個欄位',
	'LBL_SELECT_RULE' => '選擇處理重複時的規則',
	'LBL_ALLOW_DUPLICATES' => '允許重複',
	'LBL_DO_NOT_ALLOW_DUPLICATES' => '不允許重複',
	'LBL_DUPLICATES_IN_SYNC_MESSAGE' => '在與擴展應用同步時，當發現重複記錄時採取的操作',
	'LBL_PREFER_LATEST_RECORD' => '優選於最新記錄',
	'LBL_PREFER_INTERNAL_RECORD' => '優選於內部記錄',
	'LBL_PREFER_EXTERNAL_RECORD' => '優選於擴展記錄',
	'LBL_SYNC_TOOLTIP_MESSAGE' => '優選於最新記錄 - 最近修改的記錄數據將被保留<br>優選於內部記錄 - 現有記錄將保留為己<br>優選於外部記錄 - 將複製來自擴展應用的數據',
);

$jsLanguageStrings = array(
	'JS_BLOCK_VISIBILITY_SHOW' => '此區塊已設定為顯示',
	'JS_BLOCK_VISIBILITY_HIDE' => '此區塊已設定為隱藏',
	'JS_CUSTOM_BLOCK_ADDED' => '新的自訂區塊已新增',
	'JS_BLOCK_SEQUENCE_UPDATED' => '區塊順序已更新',
	'JS_SELECTED_FIELDS_REACTIVATED' => '所選定的欄位已重新啟動',
	'JS_FIELD_DETAILS_SAVED' => '欄位資訊已儲存',
	'JS_CUSTOM_BLOCK_DELETED' => '自訂區塊已刪除',
	'JS_CUSTOM_FIELD_ADDED' => '%s 欄位已新增',
	'JS_CUSTOM_FIELD_DELETED' => '自訂欄位已刪除',
	'JS_LENGTH_SHOULD_BE_LESS_THAN_EQUAL_TO' => '長度應該小於或等於',
	'JS_PLEASE_ENTER_NUMBER_IN_RANGE_2TO5' => '小數的取值範圍為2-5',
	'JS_SAVE_THE_CHANGES_TO_UPDATE_FIELD_SEQUENCE' => '欄位順序已更新',
	'JS_RELATED_INFO_SAVED' => '相關資訊已儲存',
	'JS_BLOCK_NAME_EXISTS' => '區塊名稱已存在',
	'JS_NO_HIDDEN_FIELDS_EXISTS' => '沒有隱藏的欄位',
	'JS_SPECIAL_CHARACTERS' => '特殊字符如',
	'JS_NOT_ALLOWED' => '不允許',
	'JS_FIELD_SEQUENCE_UPDATED' => '欄位順序已更新',
	'JS_DUPLICATES_VALUES_FOUND' => '發現重覆的值',
    'JS_FIELD_IN_RELATED_MODULE'  => '%s 的關聯欄位',
    'JS_TAB_IN_RELATED_MODULE' => '%s 的表格/標簽',
    'JS_FILED_IN_RELATED_HELP_TEXT' => '%s 模組的參考欄位',
    'JS_TAB_IN_RELATED_HELP_TEXT'   => '%s 模組的表格/標簽',
    'JS_TAB_FIELD_DELETION'   => '刪除關係將刪除 %s 模組中的 %s 欄位並在 %s 中刪除 %s 表和標簽。確定要繼續嗎？',
    'JS_ONE_ONE_RELATION_FIELD_DELETE' => '此操作將刪除 %s 模組中的 %s 欄位也將刪除 %s 模組的 %s 欄位。確定要繼續嗎？',
	'JS_CUSTOM_FIELDS_MAX_LIMIT' => '在 %s 塊中最多只能添加 %s 個自訂欄位',
    'JS_DEFAULT_VALUE_NOT_SET' => '未設置默認值',
    'JS_DEFAULT_VALUE' => '默認值',
    'JS_SAVE_MODULE_SEQUENCE' => '儲存將更新相關模組順序',
    'JS_PRODUCTFIELDDEFAULTVALUE' => ' (產品)',
    'JS_SERVICEFIELDDEFAULTVALUE' => ' (服務)',
    'JS_TAB_TAB_DELETION' => '此操作將刪除 %s 模組中的 %s 標簽和數據。確定要繼續嗎？',
    'JS_SHOW_THIS_FIELD_IN' => '點擊這裡在 %s 視圖中顯示此欄位',
    'JS_MAKE_THIS_FIELD' => '點擊這裡使欄位 %s',
    'JS_HIDE_THIS_FIELD_IN' => '點擊這裡在 %s 視圖中隱藏此欄位',
    'JS_NOT_MAKE_THIS_FIELD' => '點擊這裡使欄位不 %s',
    'JS_TAB_NAME_HELP_TEXT' => '顯示在 %s 記錄中的 %s 列表',
    'JS_TAB_NAME_TEXT' => '在 %s 記錄中的 %s 標簽名',
    'JS_FILED_NAME_HELP_TEXT' => '在 %s 記錄中的一個參考欄位 %s 將被添加',
    'JS_FIELD_NAME_TEXT' => '在 %s 記錄中的 %s 欄位名',
    'JS_PROP_MANDATORY' => '必填',
    'JS_SUMMARY' => '摘要',
    'JS_KEY_FIELD' => '關鍵欄位',
    
    'JS_QUICK_CREATE' => '快速建立',
    'JS_MASS_EDIT' => '批次處理',
    'JS_LBL_ARE_YOU_SURE_YOU_WANT_TO_DELETE' => '此操作將導致永久刪除數據。
                                                 當刪除欄位時，欄位中存儲的值也將被刪除，並且無法恢覆。
                                                 如果您不確定並希望將來能夠查看此數據，則可以將該欄位標記為非活動狀態，而不是刪除該欄位。非活動欄位可以在以後任何時間重新激活啟用。
                                                 您仍然確定要刪除此欄位嗎？'
    'JS_FIELD_DELETE_CONFIRMATION' => '刪除 - 我不再需要欄位中的數據。',
	'JS_STATUS_CHANGED_SUCCESSFULLY' => '狀態更改成功',
    'JS_FIELD_CAN_EITHER_BE_HEADER_OR_SUMMARY_ENABLED' => '欄位可以是首項欄位或關鍵欄位',
    'JS_DETAIL_HEADER' => '記錄標題',
    'JS_MAXIMUM_HEADER_FIELDS_ALLOWED' => '最多允許 %s 標題首項欄位',
    'JS_NAME_FIELDS_APPEAR_IN_HEADER_BY_DEFAULT' => '默認情況下，名稱欄位出現在標題中',
    'JS_FIELD_IS_HEADER_ENABLED_FOR_VTIGER7' => '此欄位作為標題首項僅限於 vtiger 7 中啟用，它會出現在摘要視圖中',

	'JS_DUPLICATE_HANDLING_SUCCESS_MESSAGE' => '預防重複性的選定欄位考量已更新成功',
	'JS_DUPLICATE_HANDLING_FAILURE_MESSAGE' => '預防重複性的選定欄位考量失敗',
	'JS_DUPLICATE_CHECK_DISABLED' => '重複檢查被停用',
);
/*+***********************************************************************************
 * 臺灣繁體中文語言包 - LayoutEditor 佈局編輯
 * 版本: 7.1.0 
 * 作者: Loki Jiang | https://www.facebook.com/groups/vTigerCRMtoTaiwan/
 * 更新日期: 2018-03-07
 *************************************************************************************/