<?php
/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.1
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is: vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 ************************************************************************************ */

$languageStrings = Array (
	'MailManager' => '郵件管理',    
	'LBL_Folders'         => '資料夾',
	'LBL_Newer'           => '新的',	
	'LBL_Older'           => '舊的',	
	'LBL_No_Mails_Found'  => '沒有找到郵件',	
	'LBL_Go_Back'         => '返回',
	'LBL_Reply_All'       => '回覆全部',
	'LBL_Reply'           => '回覆',
	'LBL_Mark_As_Unread'  => '標記為未讀',
	'LBL_Previous'        => '上一頁',
	'LBL_Next'            => '下一頁',
	'LBL_RELATED_RECORDS' => '相關記錄',
	'LBL_Mailbox'         => '郵箱',
	'LBL_Outbox'          => 'CRM 寄件箱',
	'LBL_Like'            => '包含',
	'LBL_Mail_Server'     => '郵件伺服器名稱或IP',
	'LBL_Refresh'         => '重新整理',
	'LBL_Cancel'          => '取消',
	'LBL_Send'            => '發送',
	'LBL_Compose'         => '撰寫',
	'LBL_Forward'         => '轉寄',
	'LBL_Remove'          => '刪除',
	'LBL_Associate'       => '關聯',
	'LBL_Create_Contact'  => '建立聯絡人',
	'LBL_No_Matching_Record_Found' => '未找到相關的記錄。',	
	'LBL_ACTIONS'         => '操作',
	'LBL_Search'          => '搜尋',
	'LBL_Delete'            =>  '刪除',
	'LBL_Username'             => '用戶名',
	'LBL_Your_Mailbox_Account' => '您的郵箱帳戶',
	'LBL_Password'             => '密碼',
	'LBL_Account_Password'     => '帳戶密碼',
	'LBL_Protocol'    => '協議',	
	'LBL_Imap2'       => 'IMAP2',
	'LBL_Imap4'       => 'IMAP4',
	'LBL_SSL_Options' => 'SSL 選項',
	'LBL_No_TLS'      => 'No TLS',
	'LBL_TLS'         => 'TLS',
	'LBL_SSL'         => 'SSL',
	'LBL_Certificate_Validations' => '允許驗證',
	'LBL_Validate_Cert'           => '允許驗證',
	'LBL_Do_Not_Validate_Cert'    => '不允許驗證',
	'LBL_SELECT_ACCOUNT_TYPE'     => '選擇帳戶類型',
	'LBL_FROM'        => '寄件人',
	'LBL_TO'          => '收件人',
	'LBL_CC'          => '副本',
	'LBL_BCC'         => '密件副本',
	'LBL_Date'        => '日期',	
	'LBL_Attachments' => '附件',	
	'LBL_EMAIL_TEMPLATES_LIST'=>'電子郵件範本',
	'LBL_SELECT_EMAIL_TEMPLATE'=>'選擇電子郵件範本',
	'LBL_ATTACHMENTS'  =>'附件：',	
	'LBL_SELECT_DOCUMENTS'=>'選擇文件',
	'LBL_IN' =>'在',	
	'LBL_FIND'=>'查找',
	'LBL_SAVE_NOW'=>'立即儲存',
	'LBL_Drafts'=>'草稿',
	'LBL_NO_EMAILS_SELECTED' => '沒有選擇郵件。',	
	'LBL_SUBJECT'	=>	'主題',
	'LBL_WRITE_ACCESS_FOR'	=>'寫入權限',
	'LBL_READ_ACCESS_FOR'	=>'讀取權限',
	'LBL_MODULE_DENIED' => '模組已停用!',
	'LBL_REFRESH_TIME'=>'更新時間',
	'LBL_NONE' => '不更新',	
	'LBL_5_MIN' => '5 分鐘',
	'LBL_10_MIN' => '10 分鐘',
	'LBL_MOVE_TO'=>'移動到...',
    'LBL_MAILMANAGER_ADD_Contacts' => '新增聯絡人',
   	'LBL_MAILMANAGER_ADD_Accounts' => '新增客戶',
  	'LBL_MAILMANAGER_ADD_Leads' => '新增潛在客戶',
    'LBL_MAILMANAGER_ADD_Calendar' => '新增待辦事項',
    'LBL_MAILMANAGER_ADD_HelpDesk' => '新增客服記錄',
   	'LBL_MAILMANAGER_ADD_Emails' => '附加 Email',
 	'LBL_MAILMANAGER_ADD_ModComments' => '新增評論',	
	'LBL_MAILMANAGER_ADD_Potentials' => '新增銷售機會',
    'LBL_ADD' => '新增',
	'JSLBL_Body_Cannot_Be_Empty' => '郵件內容不可留白',
	'LBL_ALLMAILS' => '全部郵件',
	'LBL_TO_CONTACTS' => '發給聯絡人',		
	'LBL_TO_ACCOUNTS' => '發給客戶',
	'LBL_TO_LEADS' => '發給潛在客戶',
	'LBL_TO_USERS' => '發給用戶',
	'LBL_SENT_MAILS' => '發送郵件',
	'LBL_Print' => '列印',	
	'LBL_SAVE_BUTTON_LABEL' => '儲存',
	'LBL_CANCEL_BUTTON_LABEL' => '取消',
	'LBL_CREATE_MAILBOX' => '建立郵箱',
	'LBL_WRITE_YOUR_COMMENT_HERE' => '新增您的評論...',	
	'LBL_MAILBOX_DETAILS' => '郵箱詳細資訊',
	'LBL_DELETE_Mailbox' => '刪除郵箱',
	'LBL_ACCOUNT_TYPE' => '帳戶類型',
	'LBL_MODULE_DESCRIPTION' => "郵件管理是一個客戶端的整合電子郵件，可讓您透過收到的電子郵件進行 CRM 相關操作。 幫助您從收件箱中收到的電子郵件建立潛在客戶、聯絡人、客戶，故障客服記錄和待辦事項。如果寄件人Mail ID 與 CRM 記錄符合，您可以執行更多操作，如：附加電子郵件，新增待辦事項，評論和客服記錄等。 此外，您還可以進行撰寫，回覆，轉寄郵件等操作。",
    'LBL_CHOOSE_EXISTING_FOLDER' => '選擇一個存在的資料夾',
    'LBL_CHOOSE_FOLDER_DESC' => '此帳戶已發送的郵件副本將儲存在預設的<b>已發郵件</ b>資料夾中。<br><br>如果想更改預設的已發郵件資料夾，建立郵箱後，點擊<B>設定</ b>標示<b>修改</ b>郵箱。',
    'LBL_CHOOSE_FOLDER' => '此賬戶發送郵件的副本將儲存在這個資料夾中。',
    'LBL_SELECTED_FOLDER' => '所選資料夾',
	'LBL_EDIT_MAILBOX' => '修改郵箱',
	'LBL_SELECT_ACCOUNT' => '選擇帳戶類型',
	'LBL_SAVE_SENT_MAILS_IN' => '保存已發送郵件',
	'LBL_CONFIGURE_MAILBOX' => '配置郵箱',
	'LBL_INBOX' => '收件箱',
	'LBL_SENT' => '發送',
	'LBL_TRASH' => '垃圾信',
	'LBL_TYPE_TO_SEARCH' => '輸入查詢...',
	'LBL_NO_MAIL_SELECTED_DESC' => '未選取郵件，請點選郵件瀏覽。',
	'LBL_FILES' => '檔案',
	'LBL_CC_SMALL' => '副本',
	'LBL_BCC_SMALL' => '密件副本',
	'LBL_MARK_AS_READ' => '標記為已讀',
	'LBL_ADD_CALENDAR' => '添加任務',
	'LBL_ADD_EVENTS' => '添加事件',
	'LBL_MAILMANAGER_ADD_Cases' => '添加案件',
);

$jsLanguageStrings = Array (
	'MailManager' => '郵件管理',
	'JSLBL_Loading_Please_Wait'  => '正在加載請稍候',
	'JSLBL_Loading'              => '截入中',	
	'JSLBL_Settings'             => '設定',	
	'JSLBL_Opening'              => '正在打開',
	'JSLBL_Deleting'              => '正在刪除',  
	'JSLBL_Updating'             => '正在更新',
	'JSLBL_Associating'          => '正在關聯',	
	'JSLBL_Saving_And_Verifying' => '儲存&驗證',
	'JSLBL_Failed_To_Open_Mail'  => '打開郵件失敗',
	'JSLBL_Finding_Relation'     => '正在查找相關郵件',	
	'JSLBL_Find_Relation_Now'    => '找到相關郵件',
	'JSLBL_Searching'            => '搜尋中',
	'JSLBL_Searching_Please_Wait'=> '搜尋中請稍候',
	'JSLBL_Sending'              => '正在發送',
	'JSLBL_Replied'              => '已回覆',
	'JSLBL_Failed_To_Send_Mail'  => '發送郵件失敗',
	'JSLBL_Recepient_Cannot_Be_Empty' => '未指定收件人',
	'JSLBL_Subject_Cannot_Be_Empty'     => '未填寫郵件主題',
	'JSLBL_Removing'                  => '正在移動',
	'JSLBL_Choose_Server_Type'        => '選擇郵件服務類型',
	'JSLBL_Other'                     => '自訂',		
	'JSLBL_Gmail'                     => 'Gmail',
	'JSLBL_Fastmail'                  => 'Fastmail',
	'JSLBL_Search_For_Email'          => '搜尋郵件',
	'JSLBL_Nothing_Found'             => '沒有找到',
	'JSLBL_Delete_Confirm'            =>'您確認要永久刪除此郵件？',
	'JSLBL_Delete_Mails_Confirm'      =>'真的要刪除這封郵件嗎？',
	'JSLBL_Receipents_Warning_Message'=>'請選擇收件人',
	'JSLBL_NO_MATCH'				  => '無符合的內容',
	'JSLBL_Saving'					=> '儲存中',
	'JSLBL_Failed_To_Save_Mail'		=>	'儲存郵件失敗',
	'JSLBL_ATTACHMENT_NOT_DELETED'	=>	'附件無法刪除',	
	'JSLBL_UPLOAD_CANCEL'	=> '取消',	
	'JSLBL_UPLOAD_DROPFILES'=>'將文件拖動到這裡上傳',
	'JSLBL_UPLOAD_FILE'=>'上傳',
	'JSLBL_UPLOAD_DELETE'=>'[x]',
	'JSLBL_UPLOAD_FAILED'=>'失敗',	
	'JSLBL_FILEUPLOAD_LIMIT_EXCEEDED'=>'文件大小超過上傳限制!!',
	'JSLBL_MAIL_SENT'=>'郵件發送',
	'JSLBL_EMAIL_FORMAT_INCORRECT'=>'請提供正確的郵件地址',
	//'JSLBL_Saving'=>'儲存中',
	'JSLBL_SaveWith_EmptySubject'=>'主題未填寫要繼續儲存?',
	'JSLBL_Delete'            =>  '刪除',	
	'JSLBL_Drafts'=>'草稿箱',	
		'JSLBL_PASSWORD_CANNOT_BE_EMPTY'=>'密碼不可空白',
	'JSLBL_SERVERNAME_CANNOT_BE_EMPTY'=>'伺服器名不可空白',
	'JSLBL_USERNAME_CANNOT_BE_EMPTY'=>'用戶名不可空白',
	'JSLBL_ACCOUNTNAME_CANNOT_EMPTY'=>'公司名稱不可空白',
	'JSLBL_FROM'=>'寄件人：',
	'JSLBL_DATE'=>'時間：',	
	'JSLBL_SUBJECT'=>'主題: ',
	'JSLBL_TO'=>'收件人: ',
	'JSLBL_CC'=>'副本: ',
	'JSLBL_FORWARD_MESSAGE_TEXT'=>'---------- 轉寄的郵件 ----------',
	'JSLBL_PLEASE_SELECT_ATLEAST_ONE_MAIL'=>'請至少選擇一個郵件',
	'JSLBL_PLEASE_SELECT_ATLEAST_ONE_RECORD'=>'請至少選擇一條記錄',
	'JSLBL_MAIL_MOVED'=>'郵件移動完成',	
	'JSLBL_MOVING'=>'正在移動郵件',	
	'JSLBL_LOADING_FOLDERS' => '載入資料夾..',
	'JSLBL_ADD_COMMENT'=>'新增評論',
    'JSLBL_Yahoo'=>'Yahoo',
	'JSLBL_CANNOT_ADD_EMPTY_COMMENT' => '你還沒有填寫評論哦',
	'JSLBL_NO_EMAILS_SELECTED' => '沒有選擇郵件',
	'JSLBL_ENTER_SOME_VALUE' => '輸入關鍵字搜尋',
	'JSLBL_DRAFT_MAIL_SAVED'=>'郵件已儲存到草稿箱',
	'JS_FUTURE_EVENT_CANNOT_BE_HELD' => '無法進行於未來',
    'JSLBL_ENTER_VALID_EMAIL_ADDRESS' => '請輸入有效的郵件位置',
	'LBL_DELETE_CONFIRMATION' => '您確認要永久的刪除郵件嗎?',
	'JS_DELETE_MAILBOX_SETTINGS_CONFIRMATION' => '您確定要刪除嗎?',
	'JSLBL_NO_MAIL_SELECTED_DESC' => '未選取郵件，請點選郵件瀏覽。',
	'JSLBL_FAILED_ADDING_COMMENT' => '添加評論失敗',
	'JSLBL_MAILS_DELETED' => '郵件已刪除完成。',
	'JSLBL_MAILS_MARKED_UNREAD' => '郵件已標記為未讀。',
	'JSLBL_MAILS_MARKED_READ' => '郵件已標記為已讀。.',
);

//Special Handling: Mix of language strings are used.
$languageStrings = array_merge($languageStrings, $jsLanguageStrings);
/*+***********************************************************************************
 * 臺灣繁體中文語言包 - MailManager 郵件管理
 * 版本: 7.1.0 
 * 作者: Loki Jiang | https://www.facebook.com/groups/vTigerCRMtoTaiwan/
 * 更新日期: 2018-02-27
 *************************************************************************************/