<?php

/* * *******************************************************************************
 * The content of this file is subject to the PDF Maker Free license.
 * ("License"); You may not use this file except in compliance with the License
 * The Initial Developer of the Original Code is IT-Solutions4You s.r.o.
 * Portions created by IT-Solutions4You s.r.o. are Copyright(C) IT-Solutions4You s.r.o.
 * All Rights Reserved.
 * ****************************************************************************** */

$languageStrings = Array(
    'MyExtension' => '我的擴展',
    "LBL_MODULE_NAME" => "PDF Maker",
    "LBL_TEMPLATE_GENERATOR" => "PDF Maker",
    "LBL_TEMPLATE_GENERATOR_DESCRIPTION" => "一般的PDF樣板可被用於任何模組。",
	"LBL_DELETE" => "刪除",
	"LBL_ADD_TEMPLATE" => "新增樣板",
	"LBL_LIST_SELECT" => "選擇",
	"LBL_MODULENAMES" => "主要模組",
	"LBL_DESCRIPTION" => "描述",
	"LBL_ACTION" => "啟動",
	"LBL_TEMPLATE" => "樣板",
	"LBL_EDIT" => "編輯",
	"LBL_NEW_TEMPLATE" => "新樣板",
	"LBL_PROPERTIES" => "屬性",
	"LBL_PDF_NAME" => "樣板名稱",
	"LBL_PDF_FORMAT" => "頁碼格式",
	"LBL_PDF_ORIENTATION" => "頁碼方向",
	"portrait" => "直式",
	"landscape" => "橫式",
	"LBL_MARGINS" => "邊界距離",
	"LBL_TOP" => "上",
	"LBL_BOTTOM" => "下",
	"LBL_LEFT" => "左",
	"LBL_RIGHT" => "右",
	"LBL_PLS_SELECT" => "請選擇 ...",
	"LBL_COMPANY_USER_INFO" => "公司與用戶資訊",
	"LBL_OTHER_INFO" => "其他資訊",
	"LBL_INSERT_TO_TEXT" => "插入版型",
	"LBL_INSERT_BARCODE_TO_TEXT" => "插入條碼至樣板",
	"LBL_COMPANY_INFO" => "公司資訊",
	"LBL_USER_INFO" => "分配到客戶",
	"LBL_LOGGED_USER_INFO" => "用戶登入",
	"LBL_PDF_TEMPLATE" => "PDF樣板",
	"LBL_DUPLICATE" => "重製",
//company information
	"LBL_COMPANY_NAME" => "公司名稱",
	"LBL_COMPANY_LOGO" => "Logo",
	"LBL_COMPANY_ADDRESS" => "地址",
	"LBL_COMPANY_CITY" => "鄉鎮市區",
	"LBL_COMPANY_STATE" => "縣/市",
	"LBL_COMPANY_ZIP" => "郵遞區號",
	"LBL_COMPANY_COUNTRY" => "國家",
	"LBL_COMPANY_PHONE" => "電話",
	"LBL_COMPANY_FAX" => "傳真",
	"LBL_COMPANY_WEBSITE" => "網站",
//user information
    "LBL_USER_USERNAME" => "用戶名",
    "LBL_USER_FIRSTNAME" => "名字",
    "LBL_USER_LASTNAME" => "姓名",
    "LBL_USER_EMAIL" => "Email",
    "LBL_USER_PHONE" => "電話",
    "LBL_USER_TITLE" => "暱稱",
    "LBL_USER_ADDRESS" => "地址",
    "LBL_USER_CITY" => "鄉鎮市區",
    "LBL_USER_STATE" => "縣/市",
    "LBL_USER_ZIP" => "郵遞區號",
    "LBL_USER_COUNTRY" => "國家",
//terms and conditions
	"TERMS_AND_CONDITIONS" => "條款及細則",
	"LBL_TERMS_AND_CONDITIONS" => "條款及細則",
//module available fields
	"LBL_MODULES_AVLBL" => "可用欄位",
	"LBL_SELECT_MODULE_FIELD" => "選擇 ...",
//related modules
	"LBL_RELATED_MODULES" => "關聯性模組",
	"LBL_SELECT_MODULE" => "選擇模組 ...",
//products
    "LBL_PRODUCT_POSITION" => "定位",
    "LBL_CURRENCY_NAME" => "幣別",
    "LBL_CURRENCY_CODE" => "幣別代碼",
    "LBL_CURRENCY_SYMBOL" => "幣別符號",
    "LBL_VARIABLE_PRODUCTNAME" => "名稱 (產品&服務的名稱與描述)",
    "LBL_VARIABLE_PRODUCTTITLE" => "產品&服務的名稱",
    "LBL_VARIABLE_PRODUCTDESCRIPTION" => "來自產品&服務模組的描述",
    "LBL_VARIABLE_PRODUCTEDITDESCRIPTION" => "產品&服務的描述",
    "LBL_VARIABLE_QUANTITY" => "數量",
    "LBL_VARIABLE_USAGEUNIT" => "單位",
    "LBL_VARIABLE_LISTPRICE" => "牌價",
    "LBL_PRODUCT_TOTAL" => "總價",
    "LBL_VARIABLE_DISCOUNT" => "折扣",
    "LBL_VARIABLE_PRODUCTTOTALAFTERDISCOUNT" => "折扣後總計",
    "LBL_PRODUCT_VAT_PERCENT" => "稅金 (%)",
    "LBL_PRODUCT_VAT_SUM" => "稅金",
    "LBL_PRODUCT_TOTAL_VAT" => "含稅總和",
    "LBL_VARIABLE_DISCOUNT_PERCENT" => "折扣 (%)",
    "LBL_VARIABLE_TOTALDISCOUNT_PERCENT" => "總折扣 (%)",
//invoice
    "LBL_VARIABLE_SUM" => "加",
    "LBL_VARIABLE_SUMWITHOUTVAT" => "小記",
    "LBL_VARIABLE_TOTALDISCOUNT" => "總折扣",
    "LBL_VARIABLE_TOTALAFTERDISCOUNT" => "未稅總和",
    "LBL_VARIABLE_VAT" => "稅金",
    "LBL_VARIABLE_VAT_PERCENT" => "稅金 (%)",
    "LBL_VARIABLE_VAT_BLOCK" => "稅金區域",
    "LBL_VARIABLE_SUMWITHVAT" => "含稅總和",
    "LBL_ADJUSTMENT" => "調整",
    "LBL_VARIABLE_TOTALSUM" => "累計",
    "LBL_DETAILS_BLOCK" => "明細",
    "LBL_CALL_INFORMATION" => "通話資訊",
//footer/header variables
    "LBL_CURRENT_PAGE" => "當前頁面",
    "LBL_ALL_PAGES" => "總頁數",
    "LBL_PAGE_PAGES" => "頁數/總頁數",
    "LBL_FILENAME" => "檔案名稱",
    "LBL_FILESIZE" => "檔案大小",
    "LBL_TIMESTAMP" => "時間戳記",
    "LBL_HEADER_VARIABLE" => "頁首參數",
    "LBL_FOOTER_VARIABLE" => "頁尾參數",
    "LBL_CURRENT_DATE" => "當前日期",
    "LBL_DATE_DD.MM.YYYY" => "dd.mm.yyyy",
    "LBL_DATE_DD-MM-YYYY" => "dd-mm-yyyy",
    "LBL_DATE_MM-DD-YYYY" => "mm-dd-yyyy",
    "LBL_DATE_YYYY-MM-DD" => "yyyy-mm-dd",
    "LBL_MODULE_FIELDS" => "模組欄位",
//labels
    "LBL_LABELS" => "標籤",
    "LBL_GLOBAL_LANG" => "通用語系",
    "LBL_MODULE_LANG" => "模組語系",
//other
    "LBL_CHANGE_MODULE" => "更改模組",
    "LBL_MARGIN_ERROR" => "錯誤的邊界設定！",
    'LBL_ARTICLE' => '產品區域',
    'LBL_ARTICLE_START' => '區域開始',
    'LBL_ARTICLE_END' => '區域結束',
    'LBL_PRODUCTS_AVLBL' => '產品與服務的常用欄位',
    'LBL_PRODUCTS_FIELDS' => '產品的可用欄位',
    'LBL_SERVICES_FIELDS' => '服務的可用欄位',
    'LBL_PRODUCT_FIELD_INFO' => '* 欄位將放置在產品區域內。PDF的產品區域部分將呈現所有產品與服務。',
    'LBL_DAYS' => '天',
    "LBL_SETTINGS_TAB" => "設定",
    "LBL_ENCODING" => "編碼",
    "LBL_PROPERTIES_TAB" => "屬性",
    "LBL_NOPRODUCT_BLOC" => "當前模組不包含產品區域。",
    "LBL_MODULE_ERROR" => "請選擇模組",
    "LBL_MISSING_FIELDS" => "缺少必要欄位：",
    "LBL_VIEWING" => "預覽",
    "LBL_PRODUCT_BLOC_TPL" => "產品區域樣板",
    "SELECT_TEMPLATE" => "請選擇PDF樣板",
    "LBL_VATBLOCK_VAT_PERCENT" => "稅率 %",
    "LBL_VATBLOCK_SUM" => "加",
    "LBL_VATBLOCK_VAT_VALUE" => "稅金",
    "LBL_TOTAL_AFTER_DISCOUNT" => "折扣後總計",
    "LBL_TOTAL_TAX_AMOUNT" => "總稅金",
    "LBL_SHTAXTOTAL" => "郵資包裝費之稅金",
    "LBL_SHTAXAMOUNT" => "郵資包裝費",
    "LBL_IGNORE_PICKLIST_VALUES" => "忽略選取列表值",
    "LBL_IGNORE_PICKLIST_VALUES_DESC" => "輸入以逗號分隔的選取列表值，這些值在PDF樣板中將被忽略。(i.e. --None--, --none--, --keine--)",
    "LBL_DECIMALS" => "數字格式",
    "LBL_DEC_POINT" => "小數點符號",
    "LBL_DEC_DECIMALS" => "小數點位數",
    "LBL_DEC_THOUSANDS" => "千位數符號",
    "LBL_HEADER_TAB" => "頁首",
    "LBL_FOOTER_TAB" => "頁尾",
    "ALERT_USE_FOOTER_EDITOR" => "使用上方頁尾編輯器。",
    "ALERT_USE_HEADER_EDITOR" => "使用上方頁首編輯器。",
    "CRM_TEMPLATES_DONT_EXIST" => "沒有針對此模組所建立的PDF樣板。",
    "CRM_TEMPLATES_ADMIN" => "您可以新增一組PDF樣板 ",
    "TEMPLATE_CREATE_HERE" => "此處。",
    "LBL_BODY" => "主內容",
    "LBL_ENCODING_TITLE" => "選取特定編碼，有利於縮減PDF生成時間與檔案大小。",
    "LBL_SAVEASDOC" => "儲存至文件",
    "ALERT_DOC_TITLE" => "文件標題不可留白。",
//installation
    "LBL_INSTALL" => "安裝",
    "LBL_EXPRESS" => "快速",
    "LBL_CUSTOM" => "自訂",
    "LBL_EXPRESS_DESC" => "標準化Vtiger安裝程序是必要的。",
    "LBL_CUSTOM_DESC" => "如提示的文件上所示，將對標準化Vtiger安裝程序進行一些修改。",
    "LBL_FINISH" => "完成",
    "LBL_NEXT" => "下一步",
    "LBL_INSTRUCTIONS" => "依據這些說明進行PDF Maker安裝。",
    "LBL_FILE" => "檔案",
    "LBL_AROUND_LINE" => "邊際線",
    "LBL_BEFORE" => '<font color="green">之前</font>',
    "LBL_AFTER" => '<font color="red">之後</font>',
    "LBL_ADD_FOLLOWING" => "加入追蹤",
    "LBL_INSTAL_ERROR" => "安裝PDF Maker過程中發生錯誤。",
    "LBL_ERROR_TBL" => "以下階段未完成",
    "LBL_ERROR_COPY_FILE" => "複製檔案",
    "LBL_CHANGE_PERMISSION" => "請修改檔案權限為777。",
    "LBL_RELOAD" => "重試",
    "LBL_INSERT_KEY" => "請輸入有效的信箱網址(需取得付費的許可權密鑰。",
    "LBL_VALIDATE" => "驗證",
    "LBL_INVALID_KEY" => "許可權密鑰無效，請聯絡PDF Maker供應商。",
    "LBL_ONLINE_ASSURE" => "請確認您的伺服主機具備網際網路連線進行驗證。",
    "LBL_ORDER_NOW" => "立即下單",
    "LBL_DOWNLOAD_SRC" => "為了PDF生成程序作業，需進行MPDF腳本的下載安裝。",
    "LBL_DOWNLOAD_SRC_DESC" => '點選下載按鈕進行下載安裝 <strong><a href="http://www.mpdf1.com/mpdf/index.php" target="_blank">mPDF</a></strong> 腳本並執行安裝作業。 請耐心等候這可能需要一點時間。<br /><br />如果您無法自動下載mPDF，您可以從此處手動下載 <pre>http://www.its4you.sk/images/extensions/PDFMaker/src/mpdf.zip</pre> 並解壓縮覆蓋到 <pre>~VTIGER_ROOT/modules/PDFMaker/resources/</pre>',
    "LBL_DOWNLOAD" => "下載",
    "LBL_VALIDATION" => "驗證",
    "LBL_CUSTOMIZATION" => "自訂",
    "LBL_INSTALL_SELECTION" => "選擇安裝模式",
    "DOWNLOAD_ERROR" => "正在從遠端伺服器下載mPDF",
    "UNZIP_ERROR" => "mpdf.zip 解壓縮中",
    "LBL_WELCOME" => "歡迎來到PDF Maker安裝精靈",
    "LBL_WELCOME_DESC" => "即將開始安裝PDF Maker到您的vtiger CRM。",
    "LBL_WELCOME_FINISH" => "強烈建議在安裝過程中不要中斷或離開此頁。",
    "LBL_TRY_AGAIN" => "重新嘗試",
    "LBL_MB_STRING_ERROR" => "mPDF腳本需要位於PHP安裝環境的 <strong>mb_string</strong> 擴展功能。請啟用此擴展功能以利於PDF Maker使用。",
    "LBL_BARCODES" => "條碼",
    "LBL_BARCODES_TYPE1" => "EAN-13 Barcodes (EAN-2 and EAN-5)",
    "LBL_BARCODES_TYPE2" => "EAN-8, UPC-A and UPC-E Barcodes",
    "LBL_BARCODES_TYPE3" => "EAN-2 and EAN-5 supplements, and combined forms",
    "LBL_BARCODES_TYPE4" => "EAN-8, UPC-A and UPC-E Barcodes",
    "LBL_BARCODES_TYPE5" => "Variable width Barcodes",
//copyright
    "PDF_MAKER" => "PDF Maker",
    "COPYRIGHT" => ":: IT-Solutions4You",
//additional
    "LBL_INVALID_FOPEN_CURL" => "在您的PHP環境中啟用 <strong>allow_url_fopen</strong> 設置或 <strong>cURL</strong> 擴展功能。",
    "LBL_PRODUCT_BREAKLINE" => "PDF產品分頁符號",
    "LBL_BREAKLINE_DESC" => "在所選產品後加入分頁符號。",
    "LBL_REACTIVATE" => "重新激活許可證",
    "LBL_REACTIVATE_DESC" => "在生成PDF文件過程中遇到了許可證密鑰問題。",
    "REACTIVATE_SUCCESS" => "您已經成功激活您的PDF Maker。",
    "LBL_GLOBAL_SETTINGS" => "全域設定",
    "LBL_SHOW_SUBTOTAL" => "在分頁符號前顯示小計",
    "LBL_SHOW_HEADER" => "在分頁符號後顯示表格標題",
    "LBL_PRODUCT_IMAGE" => "PDF 產品圖片",
    "LBL_NO_IMAGE" => "無圖片",
    "CUSTOM_FUNCTIONS" => "自訂函式",
    "CUSTOM_FUNCTION" => "自訂函式",
    "PDFMakerManual" => "PDF Maker手冊",
    "LBL_FILENAME" => "檔案名稱",
    "LBL_COMMON_FILEINFO" => "通用檔案資訊",
    "LBL_CURDATE_DD-MM-YYYY" => "當前日期 (dd-mm-yyyy)",
    "LBL_CURDATE_MM-DD-YYYY" => "當前日期 (mm-dd-yyyy)",
    "LBL_CURDATE_YYYY-MM-DD" => "當前日期 (yyyy-mm-dd)",
    "PDFMAKER_ATTACHMENT" => "PDF Maker附件",
    "LBL_UPDATE" => "更新",
    "LBL_UPDATE_INSTRUCTIONS" => "根據這些說明進行PDF Maker更新",
    "LBL_UPDATE_ERROR" => "更新PDF Maker時發生錯誤。",
    "LBL_UPDATE_SELECTION" => "選擇更新模式",
    "LBL_REPLACE" => '<font color="blue">更換</font>',
    "LBL_WITH_FOLLOWING" => "依據以下",
    "LBL_FINAL_INSTRUCTIONS" => "最終聲明",
    "LBL_RECALCULATE_RIGHTS" => "為了套用更改需 <b>重新計算</b> 權限。<br />點擊按鈕後將引導至 <b>共享訪問設定</b>.",
    "LBL_BATCH_PRINT" => "批次 PDF 匯出",
    "LBL_PDF_ACTIONS" => "PDF Maker 批次匯出",
    "LBL_UPDATE_SUCCESS" => "您已成功完成升級作業。",
    "LBL_PDFMAKER_IMPORT" => "匯入PDF樣板",
    "LBL_STEP_1" => "選擇 .XML 檔案",
    "LBL_SELECT_XML_TEXT" => "開始瀏覽並選取 .XML 檔案後進行匯入，然後點擊下一步按鈕繼續。 ",
    "LBL_FILE_LOCATION" => "檔案位置：",
    "LBL_SETASDEFAULT" => "設定為預設",
    "LBL_DEFAULT" => "(預設)",
    "LBL_SETASACTIVE" => "設定為啟用",
    "LBL_SETASINACTIVE" => "設定為停用",
    "LBL_UNSETASDEFAULT" => "取消為預設",
// v.1.29
    "LBL_CRMNOW_DESCRIPTION" => "PDF 參數描述",
// v.1.30
    "LBL_EXPORT_TO_RTF" => "匯出為 RTF",
    "LBL_RELATED_BLOCK_TPL" => "相關區域",
    "LBL_EDIT_RELATED_BLOCK" => "編輯區域",
    "LBL_EDIT_RELATED_BLOCK_BTN" => "管理區域",
    "LBL_MANAGE_RELATED_BLOCK" => "管理相關區域",
    "LBL_RELATED_BLOCK" => "相關區域",
    "LBL_RELATED_BLOCK_NAME" => "區域名稱",
    "LBL_BLOCK_STYLE" => "區域風格",
    'LBL_OR' => '或',
    'LBL_NEW_GROUP' => '新群組',
    'LBL_DELETE_GROUP' => '刪除群組',
    'LBL_NEW_CONDITION' => '新條件',
    'LBL_SHOW_STANDARD_FILTERS' => '顯示標準篩選',
// v.1.31
    "LBL_RECORD_ID" => "記錄 ID",
    "LBL_PS_NO" => "產品編號/服務編號",
    "LBL_DEACTIVATE" => "取消激活許可證",
    "LBL_DEACTIVATE_TITLE" => "取消激活許可證",

    "LBL_DEACTIVATE_DESC" => "停用後您仍可匯出PDF Maker樣板。<br /> 重新激活後可獲得標準功能。",
    "LBL_DEACTIVATE_ERROR" => "停用許可證密鑰時發生了錯誤",
// v.1.33
    "LBL_SETFORPORTAL" => "設置為客戶入口網",
    "LBL_WIDTH" => "寬 (mm)",
    "LBL_HEIGHT" => "高 (mm)",
    "LBL_CUSTOM_FORMAT_ERROR" => "不正確的自訂格式參數，最大值為 2000mm x 2000mm 以及最小值1mm x 1mm。",
    "LBL_UNSET_PORTAL" => "標準vTiger樣板將做於客戶入口網樣板使用。",
    "LBL_REPLACED_PORTAL_TEMPLATE" => "將被替換為",
    "LBL_VTIGER_TEMPLATE" => "標準 vTiger 樣板",
    "LBL_PDFMAKER_TEMPLATE" => "PDF Maker 樣板",
    "LBL_AS_PORTAL_TEMPLATE" => "作為客戶入口網樣板。",
    "LBL_TAC4YOU" => "Terms & Conditions 4You",
    "LBL_EXTENSIONS" => "擴展",
    "LBL_EXTENSIONS_DESC" => "來自PDF Maker下載的擴展應用。",
    "LBL_AVAILABLE_EXTENSIONS" => "來自PDF Maker的擴展應用",
    "LBL_MANUAL" => "手冊",
    "LBL_DOWNLOAD" => "下載",
    "LBL_CUSTOMERPORTAL" => "客戶入口網",
    "LBL_CUSTOMERPORTAL_DESC" => "允許您使用PDF Maker樣板做為標準客戶入口網的樣板，供給報價單與出貨單的模組使用。",
    "LBL_WORKFLOW" => "工作流程",
    "LBL_WORKFLOW_DESC" => "允許您在工作流程設置當中使用PDF Maker建立PDF文件。",
    "ALERT_DOWNLOAD_ERROR" => "文件下載時發生錯誤。",
    "LBL_INSTAL_EXT" => "安裝注意事項：",
    "LBL_EXPRESS_INSTAL_EXT" => "如果您的標準vTiger沒有安裝自定義的開源碼或資料庫，請改將擴展檔案自解壓縮到vTiger根目錄。",
    "LBL_CUSTOM_INSTAL_EXT" => "否則，請依據所描述的自定義安裝流程進行",
    "LBL_CP_EXPRESS_INSTAL_EXT" => "否則，請依據所描述的自定義安裝的開源碼或資料庫，請改將對應的擴展檔案自解壓縮到vTiger與CustomerPortal根目錄。",
// v.1.34
    "LBL_PROFILES_DESC" => "管理特定用戶的PDF Maker授權於不同規則。",
    "LBL_SETPRIVILEGIES" => "規範PDF Maker權限於所有配置之中",
    "LBL_PROFILES" => "配置",
    "LBL_CREATE_EDIT" => "建立/編輯",
    "LBL_VIEW" => "顯示",
    "LBL_DELETE" => "刪除",
    "LBL_SHARING_TAB" => "分享",
    "LBL_TEMPLATE_OWNER" => "樣板擁有者",
    "LBL_SHARING_ERROR" => "至少選擇一組允許的共用模板。",
    "LBL_ORDER" => "順序",
    "LBL_SAVE_ORDER" => "保存樣板順序",
    "LBL_ORDER_ERROR" => "請插入有效的樣板順序。",
    "LBL_ORDER_SAVE_OK" => "樣板順序已儲存成功。",
    "LBL_ORDER_SAVE_ERROR" => "儲存樣板順序時發生錯誤。",
    "LBL_DONT_DISPLAY_HEADER_ON_FIRST_PAGE" => "在第一頁不顯示頁首",
    "LBL_DONT_DISPLAY_FOOTER_ON_LAST_PAGE" => "在最後頁不顯示頁尾",
    "LBL_DISPLAY_FOOTER_ONLY_ON_LAST_PAGE" => "在最後頁顯示頁尾",
    "LBL_LISTVIEWBLOCK" => "列表顯示區塊",
    "LBL_COUNTER" => "計數",
    "LBL_HEADER_FOOTER_VARIABLES" => "頁首/頁尾 參數",
    "LBL_INSTALL_SUCCESS" => "PDF Maker已安裝成功。",
// v.1.35
    "LBL_NEW_PDFMAKER" => "新的 PDF Maker",
    "LBL_NEW_MPDF" => "新的 mPDF",
    "LBL_AVAILABLE" => "可用的",
    "LBL_CUSTOM_LABELS" => "自訂標籤",
    "LBL_CUSTOM_LABELS_DESC" => "管理您自己的標籤並建立您的PDF樣板做為完整自我語系。",
    "LBL_DEFINE_CUSTOM_LABELS" => "定義自己的可用標籤授予所有用戶",
    "LBL_KEY" => "標籤關鍵字",
    "LBL_VALUE" => "標籤內容",
    "LBL_NO_ITEM_FOUND" => "沒有找到任何項目。",
    "LBL_KEY_EXISTS" => "以下標籤關鍵字必需是唯一的：",
    "LBL_KEY_NAME_PREFIX" => "以下標籤關鍵字不需要前綴字首：",
    "LBL_KEY_HAS_EMPTY_VAL" => "以下標籤關鍵字不可為空：",
    "LBL_LISTVIEW_TEMPLATE" => "樣板只能做為’列表顯示樣板’",
    "LBL_FOR_DV" => "於細節顯示",
    "LBL_FOR_LV" => "於列表顯示",
    "LBL_DEFAULT_NOPAR" => "預設",
    "LBL_DISPLAY_HEADER" => "顯示頁首",
    "LBL_DISPLAY_FOOTER" => "顯示頁尾",
    "LBL_ALL_PAGES" => "所有頁面",
    "LBL_FIRST_PAGE" => "第一頁",
    "LBL_OTHER_PAGES" => "其他頁",
    "LBL_LAST_PAGE" => "最後頁",
    "LBL_DESC4YOU" => "Descriptions 4You",
    "LBL_PRODUCTBLOCKTPL_DESC" => "管理您的產品區域樣板。",
    "LBL_PRODUCTBLOCKTPL" => "產品區域樣板",
    "LBL_DEFINE_PBTPL" => "訂逤自己可用的產品區域樣板授予所有用戶",
    "LBL_QRCODE" => "QR code",
    "LBL_EDIT_PBTPL" => "編輯產品區域樣板",
    "LBL_CREATE_PBTPL" => "建立新的產品區域樣板",
    "LBL_SELECT_RELBLOCK" => "請選擇關聯區域",
    "LBL_DELETE_RELBLOCK_CONFIRM" => "您確定要刪除關聯區域",
    "LBL_MYPREF_DESC" => "管理您的PDF Maker全域偏好設定",
    "LBL_MYPREF" => "我的偏好設定",
    "LBL_DEFINE_MYPREF" => "定義您的PDF 通用設定。",
    "LBL_NOTIFICATION_SETT" => "通知設定",
    "LBL_SHOW_NOTIF" => "有新的PDF Maker/mPDF 版本時則顯示通知",
    "LBL_OTHER_LANG_VALUES" => "其他的語言內容",
    "LBL_CURR_LANG_VALUE" => "當前的語言內容",
    "LBL_OTHER_VALS" => "其他內容",
    "LBL_LANG" => "標籤語言",
// v.1.35.2
    "LBL_MODCOMMENTS" => "註解",
    "LBL_MODCOMMENTS_INFORMATION" => "註解資訊",
    "LBL_DEBUG_DESC" => "調整PDF Maker的除錯模式 開/關。顯示系統資訊。",
    "LBL_DEBUG" => "除錯中",
    "LBL_DB_TAB" => "資料庫表",
    "LBL_PHPINFO_TAB" => "PHP 資訊",
    "LBL_DEBUGGING_SETT" => "調整除錯模式 開/關",
    "LBL_DEBUGGING_INFO" => "其他除錯資訊",
    "LBL_DBG_MEMLIMIT" => "memory_limit",
    "LBL_ORIGINAL_VAL" => "原始內容",
    "LBL_NEW_VAL" => "更改內容",
    "LBL_DBG_MAXINVARS" => "max_input_vars",
    "LBL_LOWVAL" => "低標內容",
    "LBL_MINVAL" => "中階內容",
    "LBL_OK" => "確認",
    "LBL_DBG_SUHOSIN" => "suhosin",
    "LBL_DISABLED" => "禁",
    "LBL_ENABLED" => "啟用",
    "LBL_REQUEST_MV" => "request_max_vars",
    "LBL_POST_MV" => "post_max_vars",
    "LBL_PHPINFO" => "PHP 資訊",
    "LBL_DBG_DB_FIELD" => "欄位",
    "LBL_DBG_DB_TYPE" => "類型",
    "LBL_DBG_DB_NULL" => "無",
    "LBL_DBG_DB_KEY" => "密鑰",
    "LBL_DBG_DB_DEFAULT" => "預設",
    "LBL_DBG_DB_EXTRA" => "額外",
    "LBL_DEBUGGING_FILES_PERM" => "選取檔案權限",
    "LBL_DBG_FP_NOT_WRITABLE" => "遺失寫入權限",
    "LBL_NOT_WRITABLE" => "不可寫",
    "LBL_ACTIONS" => "操作",
    "LBL_DBG_SMARTY" => "刪除 Smarty/templates_c/*.*",
    "LBL_ON" => "開",
    "LBL_OFF" => "關",
    "LBL_SMARTY_DELETED" => "Smarty 臨時樣板尚未刪除。",
    "LBL_SMARTY_NOT_DELETED" => "警告！ 臨時樣板尚未刪除。",
    "LBL_DBG_EXPORT" => "匯出除錯資訊",
    "LBL_DBG_NOTIF" => "您的伺服器配置不符合最低需求，PDF Maker可能將無法正常運作。",
    "LBL_GOTO_DEBUG" => "開始除錯",
    "LBL_DBG_MAXEXTIME" => "max_execution_time",
// v.1.35.3
    "LBL_SORTING" => "排序",
    "LBL_SORT_BY" => "排序依據",
    "LBL_THEN_BY" => "然後",
    "LBL_ASC" => "升序",
    "LBL_DESC" => "降序",
    "LBL_SORTCOL_DUPLICATES" => "您選擇了多個重複列！",
    "LBL_DBG_VERSIONS" => "版本",
    "LBL_PHP" => "PHP",
    "LBL_LICENSE" => "許可設置",
    "LBL_LICENSE_DESC" => "允許您管理所有設置",
    "LBL_LICENSE_KEY" => "許可密鑰",
    "LBL_ACTIVATE_KEY" => "激活許可證",
    "REACTIVATE_ERROR" => "（重新）激活許可證密鑰時發生了些錯誤。",
    "LBL_DEACTIVATE_SUCCESS" => "許可證密鑰已停用成功",
    "LBL_UNINSTALL" => "反安裝 PDFMaker",
    "LBL_UNINSTALL_DESC" => "PDF Maker已完全從您的vTiger中移除",
    "LBL_UNINSTALL_CONFIRM" => "您確定要從vTiger中徹底移除PDF Maker並停用您的PDF Maker 授權許可嗎？",
// v.1.36.0
    "LBL_DOC_TITLE" => "文件標題",
    "LBL_DOC_DESC" => "文件說明",
    "LBL_FLD_NAME" => "資料夾名稱",
    "LBL_PDF_LANGUAGE" => "PDF語言",
    "LBL_MPDF" => "mPDF",
    "LBL_PLEASE_FINISH_INSTALLATION" => "請完成安裝",
    'LBL_EXPORT_TO_PDF' => '匯出為PDF',
    "LBL_PERMISSION" => " 您無法執行此操作",
    "ARE_YOU_SURE" => "您確定嗎?",
    "LBL_TEMPLATE_INFORMATIONS" => "樣板資訊",
    "LBL_TEMPLATE_CONTENT" => "樣板內容",
    "LBL_SELECT_XML" => "選擇 .XML 檔案",
    "LBL_APPLY" => "應用",
    "LBL_STATUS"=>"狀態",
    "Inactive"=>"Inactive",
    "PUBLIC_FILTER"=>"公開",
    "PRIVATE_FILTER"=>"私人",
    "SHARE_FILTER"=>"分享",
    "LBL_MEMBER_AVLBL"=>"可用的實體與人員",
    "LBL_MEMBER_SELECTED"=>"已選人員",
    "LBL_ENTITY"=>"實體",
    "LBL_ROLES"=>"角色",
    "LBL_ROLES_SUBORDINATES"=>"角色與附屬",
    "LBL_MEMBER_OF"=>"成員於 ",
// v.1.36.3
    "LBL_CURRENT_VALUES" => "當前值",
    "LBL_MIN_VALUES" => "最小（推薦）值",
    "LBL_STATUS" => "狀態",
// v.1.37.0
    "LBL_EXPORT_FISCAL" => "列印帳務文件",
    "LBL_CONFIRM_FISCAL" => "您想要列印帳務?",
// v.1.37.1
    "LBL_DBG_NOTIF_NEW" => "您的伺服器配置不符合最低需求。有關更多資訊，請點擊此處並連繫您的系統管理員。",
// v.2.1.0
    "LBL_RELATIVE_MODULE"=>"相關模組",
    "LBL_SELECT_COLUMNS"=>"選擇列",
    "LBL_FILTERS"=>"篩選",
    "LBL_STANDARD_FILTERS"=>"標準篩選",
    "LBL_SF_COLUMNS"=>"標準篩選列",
    "LBL_SF_STARTDATE"=>"開始日期",
    "LBL_SF_ENDDATE"=>"結束日期",
    "LBL_ADVANCED_FILTER"=>"進階篩選",
    "LBL_NONE" => "無",
    "LBL_UPGRADE" => "升級PDFMaker",
    "LBL_PDF_TEMPLATES_LIST" => "PDF 樣板列保",
    "LBL_EDIT_CUSTOM_LABEL" => "編輯自訂標籤",
    "LBL_ADD_NEW_CUSTOM_LABEL" => "新增自訂標籤",
    "LBL_ENTER_KEY" => "為自訂標籤添加密鑰",
    "LBL_ENTER_CUSTOM_LABEL_VALUE" => "輸入自訂標籤內容",
    "LBL_LABEL_KEY_EXIST" => "標籤密鑰已存在",
    "LBL_VALIDATION_ERROR" => "驗證許可證密鑰時發生錯誤",
    "LBL_PDF_ADDED_DOC" => "PDF已保存到文件",
// v.2.3.0
    "LBL_WORKFLOWS_ARE_ALREADY_INSTALLED"=>"已安裝工作流程。",
    "LBL_INSTALLATION_FAILED" => "安裝失敗",
    "LBL_CHANGE_PERMISSION" => "P請將文件夾權限更改為777 (modules/com_vtiger_workflow/tasks and layouts/vlayout/modules/Settings/Workflows/Tasks).",
    "LBL_PERMISSION_ERROR_PART_1" => "複製檔案來自",
    "LBL_PERMISSION_ERROR_PART_2" => "至",
    "LBL_PERMISSION_ERROR_PART_3" => "沒有成功",
    "LBL_EMAIL_DETAILS" => "電子郵件詳情",
    "LBL_EMAIL_CONTENT" => "電子郵件內容",
    "LBL_DUPLICATES_EXIST" => "樣板名稱已存在",
// v.2.5.1
    "LBL_SAME_ORGA" => "公司需相同。",
// v.2.5.3
    "LBL_CLASS_SOAPCLIENT2_DOES_NOT_EXIST" => "soapclient2 類別不存在",
// v.2.7.0
    'LBL_PRINT' => '列印',
// v.2.9.0
    "LBL_DISPLAY_TAB"=>"顯示條件",
    "LBL_DISPLAYED"=>"已顯示",
    "LBL_IF"=>"如果",
    "LBL_CONDITIONS"=>"條件",
// v.2.10.0
    "LBL_URL" => "您的vtiger網址",
    "LBL_COMPANY_LICENSE_INFO" => "您的公司資訊",
    "LBL_CHANGE_COMPANY_INFORMATION" => "更改公司資訊",
    "LBL_ACTIVATE_BTN" => "為了正確使用您的pdf Maker，您必須重新激活您的許可證。",
    "LBL_LICENSE_SETTINGS_INFO" => "管理您的PDF Maker許可證密鑰",
    "LBL_ACTIVATE_KEY_TITLE" => "設定許可證密鑰啟用",
// v.2.12.0
    "LBL_CURRENCY_ID" => "幣別 ID",
    "LBL_PRODUCTS_AND_SERVICES" => "產品與服務",
    "LBL_PRODUCTS_ONLY" => "產品限定",
    "LBL_SERVICES_ONLY" => "服務限定",
// v.2.13.0
    "LBL_MODIFIEDBY_USER_INFO" => "修改者",
    "LBL_CREATOR_USER_INFO" => "建立者",
// v.2.14.0
    "LBL_EXPORT_TO_RTF_DESC" => "PDF Maker可生成RTF文件，但我們無法保證您的樣板跟在PDF內有相同效果。這因為RTF與PDF的構造不同。<br>所以，默認情況下該功能為停用，但你可以自行啟用並嘗試確認是否符合您的需求。",
// v.2.16.0
    "LBL_CSS_STYLE_TAB"=>"CSS 樣式",
    "LBL_STYLES_LIST"=>"樣式",
    "ITS4YouStyles" => "Styles 4 You",
    "LBL_ITS4YOUSTYLES_DESC" => "此擴展應用允許您管理同一處的樣式並套用在您指定的樣板。",
    "LBL_ITS4YOUSTYLES_ARE_ALREADY_INSTALLED" => "Styles 4 You 已安裝存在",
    "LBL_ITS4YOUSTYLES_INSTALL_INFO" => "要安裝此擴展應用，請從右側下載按鈕執行，接著使用安裝按鈕獲通過模組管理進行安裝。",

    "LBL_CREATED_IN_OLD_LOOK_CANNOT_BE_EDITED"=>"此顯示條件採用舊有的外觀建立。舊有外觀建立的條件無法被編輯。您可以重新建立條件。",
    "LBL_USE_EXISTING_CONDITIONS"=>"使用現有條件",
    "LBL_RECREATE_CONDITIONS" => "重新建立條件",
    "LBL_OLD_CONDITIONS" => "舊有條件",
    "LBL_NO_DISPLAY_CONDITIONS_DEFINED" => "顯示尚未定義的條件",
    "LBL_DISPLAY_CONDITIONS_YES" => "該模板用於匯出時顯示",
    "LBL_DISPLAY_CONDITIONS_NO" => "該模板用於匯出時不顯示",
    "LBL_STYLES"=>"格式",
    "LBL_INSTALL_STEP_1"=>"歡迎",
);

$jsLanguageStrings = array(
    "LBL_MISSING_FIELDS" => "缺少明確欄位：",
    "LBL_SELECT_MODULE_FIELD" => "選擇 ...",
    "LBL_PDF_NAME"=>"樣板名稱",
    "CANNOT_BE_EMPTY"=>" 不能為空",
    "LBL_MODULE_ERROR"=>"請選擇模組。",
    "LBL_MARGIN_ERROR"=>"不正確的邊界設定！",
    "LBL_SELECT_RELBLOCK"=>"請選擇相關區域。",
    "LBL_DELETE_RELBLOCK_CONFIRM"=>"您確定要刪除此相關區域嗎",
    "LBL_UNSET_PORTAL"=>"標準vTiger樣板將做為客戶入口網樣板",
    "ARE_YOU_SURE"=>"您確定嗎？",
    "LBL_CUSTOM_FORMAT_ERROR"=>"不正確的自訂格式參數，最大值為 2000mm x 2000mm 以及最小值1mm x 1mm。",
    "LBL_SHARING_ERROR"=>"至少選擇一組允許的共用模板。",
    "BLOCK_NAME_CANNOT_BE_BLANK"=>"區域名稱不能為空",
    "COLUMNS_CANNOT_BE_EMPTY"=>"所選列不能為空",
    "LBL_NONE" => "無",
    "JS_CUSTOM_LABEL_SAVED_SUCCESSFULLY" => "自訂標籤參數已成功儲存",
    "JS_CUSTOM_LABEL_VALUES_SAVED_SUCCESSFULLY" => "自訂標籤參數已成功儲存",
    
    "LBL_OTHER_VALS" => "其他參數",
    "LBL_DEACTIVATE_QUESTION" => "您確定要停用您的許可證密鑰嗎?",
    "LBL_CHANGE_MODULE_QUESTION" => "您確定要更改主要模組?",
    "LBL_COMMON_FILEINFO" => "通用檔案資訊",
    "LBL_UNINSTALL_CONFIRM" => "您確定要從vTiger中徹底移除PDF Maker並停用您的PDF Maker 授權許可嗎？",
    "LBL_DUPLICATE_TEMPLATE_CREATION_CONFIRMATION" => "樣板名稱已存在。是否要建立重複的樣板?",
);
/*+***********************************************************************************
 * 臺灣繁體中文語言包 - PDF Maker
 * 版本: 7.1.0 
 * 作者: Loki Jiang | https://www.facebook.com/groups/vTigerCRMtoTaiwan/
 * 更新日期: 2018-03-15
 *************************************************************************************/