<?php
/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 *************************************************************************************/
$languageStrings = array(
	'LBL_ADD_RECORD' => '新增用戶',

	//MyPreference Blocks
	'LBL_MY_PREFERENCES'  =>  '個人偏好設定',
	'LBL_MORE_INFORMATION'  =>  '更多資訊',
	'LBL_USERLOGIN_ROLE'  =>  '用戶登入和角色',
	'LBL_USER_IMAGE_INFORMATION' => '用戶照片',
	'LBL_CURRENCY_CONFIGURATION' =>  '幣別與數字欄位配置',
	'LBL_ADDRESS_INFORMATION' => '用戶地址',
	'LBL_USER_ADV_OPTIONS' => '用戶進階選項',
	'Asterisk Configuration'  =>  'Asterisk 配置',
	'LBL_HOME_PAGE_COMPONENTS' => '首頁元件',
	'LBL_TAG_CLOUD_DISPLAY' => '標籤雲顯示',

	//MyPreference Fields
	'Role' => '職稱角色',
	'Admin' => '系統管理員',
	'User Name' => '用戶名稱',
	'Default Activity View' => '預設我的日曆顯示',
	'Default Calendar View' => '預設日曆顯示',
	'Default Lead View' => '預設潛在客戶顯示',
	'Title' => '頭銜',
	'Office Phone' => '辦公電話',
	'Department' => '部門',
	'Reports To' => '上級主管',
	'Yahoo id' => 'Yahoo id',
	'Home Phone' => '家裡電話',
	'User Image' => '用戶圖片',
	'Date Format' => '日期格式',
	'Tag Cloud' => '標籤雲',
	'Signature' => '簽名',
	'Street Address' => '街道',
	'Password' => '密碼',
	'Confirm Password' => '確認密碼',
	'LBL_SHOWN' => '顯示',
	'LBL_HIDDEN' => '隱藏',
	'LBL_SHOW' => '顯示',
	'LBL_HIDE' => '隱藏',
	'LBL_HOME_PAGE_COMPO' => '首頁元件',
	'LBL_LOGIN_HISTORY' => '登入記錄',
	'LBL_USERDETAIL_INFO' => '查看用戶細節',
	'LBL_DELETE_GROUP' => '刪除群組',
	'LBL_DELETE_GROUPNAME' => '群組已刪除',
	'LBL_TRANSFER_GROUP' => '將所有權轉交給：',
	'LBL_DELETE_USER' => '用戶將被刪除',
	'LBL_REMOVE_USER' => '刪除',
	'LBL_MORE_OPTIONS' => '更多選項',
	'LBL_TRANSFER_USER' => '轉讓所有權給其他用戶',
	'LBL_RESTORE_USER' => '恢復用戶',
	'LBL_DELETE_PROFILE' => '刪除權限配置',
	'LBL_TRANSFER_ROLES_TO_PROFILE' => '轉移角色到權限配置',
	'LBL_PROFILE_TO_BE_DELETED' => '權限配置將被刪除',
	'INTERNAL_MAIL_COMPOSER' => '內部郵件編輯器',
	'Asterisk Extension'  =>  'Asterisk 擴展應用',
	'Receive Incoming Calls'  =>  '接聽來電',
	'Webservice Access Key' => 'Access key',
	'Language' => '語言',
	'Theme' =>  '主題',
	'Time Zone'  =>  '時區',
	'Decimal Separator'  =>  '小數點符號',
	'Digit Grouping Pattern'  =>  '數字分組方式',
	'Digit Grouping Separator'  =>  '數字分組符號',
	'Symbol Placement'  =>  '幣別符號位置',
	'Number Of Currency Decimals'  =>  '幣別小數位數',
	'Truncate Trailing Zeros'  =>   '捨去尾數零',
	'Default Call Duration' => '預設通話時間（分鐘）',
	'Other Event Duration' => '其他事件持續時間（分鐘）',
	'Calendar Hour Format' => '日曆小時格式',
	//'Tag Cloud' => '標籤雲',

	//Time zones-Dont change any value
    'Kwajalein'  =>  '(UTC-12:00) 國際日期變更線以西',
    'Pacific/Midway'  =>  '(UTC-11:00) 協調世界時 Time-11',
    'Pacific/Samoa'  =>  '(UTC-11:00) 薩摩亞群島 Samoa',
    'Pacific/Honolulu'  =>  '(UTC-10:00) 夏威夷 Hawaii',
    'America/Anchorage'  =>  '(UTC-09:00) 阿拉斯加 Alaska',
    'America/Los_Angeles'  =>  '(UTC-08:00) 太平洋時間（加拿大和美國西海岸的標準時間）',
    'America/Tijuana'  =>  '(UTC-08:00) 提華納，加利福尼亞半島',
    'America/Denver'  =>  '(UTC-07:00) 山地時間(美國和加拿大)',
    'America/Chihuahua'  =>  '(UTC-07:00) 奇瓦瓦 Chihuahua,拉巴斯 La Paz,馬薩特蘭 Mazatlan',
    'America/Mazatlan'  =>  '(UTC-07:00) 墨西哥馬薩特蘭 Mazatlan',
    'America/Phoenix'  =>  '(UTC-07:00) 亞利桑那州 Arizona',
    'America/Regina'  =>  '(UTC-06:00) 薩斯喀徹溫省 Saskatchewan',
    'America/Tegucigalpa'  =>  '(UTC-06:00) 中美洲 Central America',
    'America/Chicago'  =>  '(UTC-06:00) 中部時間(美國和加拿大)',
    'America/Mexico_City'  =>  '(UTC-06:00) 墨西哥城',
    'America/Monterrey'  =>  '(UTC-06:00) 墨西哥蒙特雷 Monterrey',
    'America/New_York'  =>  '(UTC-05:00) 東部時間(美國和加拿大)',
    'America/Bogota'  =>  '(UTC-05:00) 波哥大，利馬，基多',
    'America/Lima'  =>  '(UTC-05:00) 秘魯利馬 Lima',
    'America/Rio_Branco'  =>  '(UTC-05:00) 巴西里約布蘭科 Rio Branco',
    'America/Indiana/Indianapolis'  =>  '(UTC-05:00) 印第安納州(東) Indiana (East)',
    'America/Caracas'  =>  '(UTC-04:30) 委內瑞拉加拉加斯 Caracas',
    'America/Halifax'  =>  '(UTC-04:00) 大西洋時間(加拿大)',
    'America/Manaus'  =>  '(UTC-04:00) 巴西馬瑙斯 Manaus',
    'America/Santiago'  =>  '(UTC-04:00) 聖地亞哥 Santiago',
    'America/La_Paz'  =>  '(UTC-04:00) 拉巴斯 La Paz',
    'America/Cuiaba'  =>  '(UTC-04:00) 巴西庫亞巴 Cuiaba',
    'America/Asuncion'  =>  '(UTC-04:00) 巴拉圭亞松森 Asuncion',
    'America/St_Johns'  =>  '(UTC-03:30) 加拿大紐芬蘭 Newfoundland',
    'America/Argentina/Buenos_Aires'  =>  '(UTC-03:00) 阿根廷布宜諾斯艾利斯 Buenos Aires',
    'America/Sao_Paulo'  =>  '(UTC-03:00) 巴西利亞 Brasilia',
    'America/Godthab'  =>  '(UTC-03:00) 格陵蘭群島 Greenland',
    'America/Montevideo'  =>  '(UTC-03:00) 烏拉圭蒙特維的亞 Montevideo',
    'Atlantic/South_Georgia'  =>  '(UTC-02:00) 中大西洋地區 Mid-Atlantic',
    'Atlantic/Azores'  =>  '(UTC-01:00) 亞述爾群島 Azores',
    'Atlantic/Cape_Verde'  =>  '(UTC-01:00) 佛得角群島 Cape Verde Is.',
    'Europe/London'  =>  '(UTC) 倫敦、愛丁堡、柏林、里斯本',
    'UTC'  =>  '(UTC) 通用協調時間，格林尼治標準時間',
    'Africa/Monrovia'  =>  '(UTC) 蒙羅維亞,雷克雅未克 Monrovia, Reykjavik',
    'Africa/Casablanca'  =>  '(UTC) 摩洛哥卡薩布蘭卡Casablanca',
    'Europe/Belgrade'  =>  '(UTC+01:00) 貝爾格萊德、布拉迪斯拉發、佈達佩斯、盧布爾雅那、布拉格',
    'Europe/Sarajevo'  =>  '(UTC+01:00) 薩拉熱窩,斯科普里,華沙,薩格勒布',
    'Europe/Brussels'  =>  '(UTC+01:00) 布魯塞爾、哥本哈根、馬德里、巴黎',
    'Africa/Algiers'  =>  '(UTC+01:00) 西部非洲中部',
    'Europe/Amsterdam'  =>  '(UTC+01:00) 阿姆斯特丹,柏林,伯爾尼,羅馬,斯德哥爾摩,維也納',
    'Europe/Minsk'  =>  '(UTC+02:00) 明斯克 Minsk',
    'Africa/Cairo'  =>  '(UTC+02:00) 開羅 Cairo',
    'Europe/Helsinki'  =>  '(UTC+02:00) 赫爾辛基,里加,索非亞,塔林,維爾紐斯',
    'Europe/Athens'  =>  '(UTC+02:00) 雅典,布加勒斯特 Athens, Bucharest',
    'Europe/Istanbul'  =>  '(UTC+02:00) 伊斯坦布爾 Istanbul',
    'Asia/Jerusalem'  =>  '(UTC+02:00) 耶路撒冷 Jerusalem',
    'Asia/Amman'  =>  '(UTC+02:00) 安曼 Amman',
    'Asia/Beirut'  =>  '(UTC+02:00) 貝魯特 Beirut',
    'Africa/Windhoek'  =>  '(UTC+02:00) 納米比亞溫特和克 Windhoek',
    'Africa/Harare'  =>  '(UTC+02:00) 津巴布韋哈拉雷 Harare',
    'Asia/Kuwait'  =>  '(UTC+03:00) 科威特,沙特',
    'Asia/Baghdad'  =>  '(UTC+03:00) 巴格達 Baghdad',
    'Africa/Nairobi'  =>  '(UTC+03:00) 肯尼亞內羅畢 Nairobi',
    'Europe/Moscow'  =>  '(UTC+03:00) 莫斯科、伏爾加格勒 Moscow, Volgograd',
    'Asia/Tehran'  =>  '(UTC+03:30) 德黑蘭 Tehran',
    'Asia/Tbilisi'  =>  '(UTC+04:00) 第比利斯 Tbilisi',
    'Asia/Muscat'  =>  '(UTC+04:00) 阿布扎比,馬斯喀特 Abu Dhabi, Muscat',
    'Asia/Baku'  =>  '(UTC+04:00) 巴庫 Baku',
    'Asia/Yerevan'  =>  '(UTC+04:00) 耶烈萬 Yerevan',
    'Asia/Karachi'  =>  '(UTC+05:00) 伊斯蘭堡、卡拉奇 Islamabad, Karachi',
    'Asia/Tashkent'  =>  '(UTC+05:00) 塔什干 Tashkent',
    'Asia/Kolkata'  =>  '(UTC+05:30) 欽奈,加爾各答,孟買,新德里',
    'Asia/Colombo'  =>  '(UTC+05:30) 斯里賈亞瓦德納普拉-科萊 Sri Jayawardenepura',
    'Asia/Katmandu'  =>  '(UTC+05:45) 加德滿都 Kathmandu',
    'Asia/Dhaka'  =>  '(UTC+06:00) 孟加拉達卡 Dhaka',
    'Asia/Almaty'  =>  '(UTC+06:00) 阿拉木圖 Almaty',
    'Asia/Yekaterinburg'  =>  '(UTC+06:00) 葉卡捷琳堡 Ekaterinburg',
    'Asia/Rangoon'  =>  '(UTC+06:30) 仰光 Yangon (Rangoon)',
    'Asia/Novosibirsk'  =>  '(UTC+07:00) 新西伯利亞 Novosibirsk',
    'Asia/Bangkok'  =>  '(UTC+07:00) 曼谷、雅加達 Bangkok, Jakarta',
    'Asia/Brunei'  =>  '(UTC+08:00) 北京, 重慶, 香港, 烏魯木齊',
    'Asia/Krasnoyarsk'  =>  '(UTC+08:00) 克拉斯諾雅茨克 Krasnoyarsk',
    'Asia/Ulaanbaatar'  =>  '(UTC+08:00) 烏蘭巴托 Ulaan Bataar',
    'Asia/Kuala_Lumpur'  =>  '(UTC+08:00) 吉隆坡,新加坡',
    'Asia/Taipei'  =>  '(UTC+08:00) 台北 Taipei',
    'Australia/Perth'  =>  '(UTC+08:00) 珀斯 Perth',
    'Asia/Irkutsk'  =>  '(UTC+09:00) 伊爾庫次克 Irkutsk',
    'Asia/Seoul'  =>  '(UTC+09:00) 韓國首爾 Seoul',
    'Asia/Tokyo'  =>  '(UTC+09:00) 東京 Tokyo',
    'Australia/Darwin'  =>  '(UTC+09:30) 澳大利亞達爾文 Darwin',
    'Australia/Adelaide'  =>  '(UTC+09:30) 阿德萊德 Adelaide',
    'Australia/Canberra'  =>  '(UTC+10:00) 堪培拉、墨爾本、悉尼 Canberra, Melbourne, Sydney',
    'Australia/Brisbane'  =>  '(UTC+10:00) 布里斯本 Brisbane',
    'Australia/Hobart'  =>  '(UTC+10:00) 霍巴特 Hobart',
    'Asia/Vladivostok'  =>  '(UTC+10:00) 海參崴 Vladivostok',
    'Pacific/Guam'  =>  '(UTC+10:00) 關島，莫爾茲比港 Guam, Port Moresby',
    'Asia/Yakutsk'  =>  '(UTC+10:00) 雅庫茨克 Yakutsk',
	'Etc/GMT-11' => '(UTC+11:00) 所羅門群島，新喀裡多尼亞 Solomon Is., New Caledonia',
    'Pacific/Fiji'  =>  '(UTC+12:00) 斐濟 Fiji',
    'Asia/Kamchatka'  =>  '(UTC+12:00) 勘察加半島 Kamchatka',
    'Pacific/Auckland'  =>  '(UTC+12:00) 新西蘭奧克蘭 Auckland',
    'Asia/Magadan'  =>  '(UTC+12:00) 馬加丹 Magadan',
    'Pacific/Tongatapu'  =>  '(UTC+13:00) 努庫阿洛法 Nukualofa',

	'Summary' => '摘要',
	'Detail' => '細節',
	'LBL_USER_LIST_DETAILS' => '細節',

	'LBL_OLD_PASSWORD' => '舊密碼',
	'LBL_CHANGE_PASSWORD' => '更改密碼',
	'LBL_NEW_PASSWORD' => '新密碼',
	'LBL_CONFIRM_PASSWORD' => '確認密碼',
	'LBL_CHANGE_ACCESS_KEY' => '修改Access key',
	'LBL_ACCESS_KEY_UPDATED_SUCCESSFULLY' => 'Access key更新成功',
	'LBL_FAILED_TO_UPDATE_ACCESS_KEY' => 'Access key更新失敗',
	'LBL_TRANSFER_OWNERSHIP' => '轉移所有權',
	'LBL_LOGIN_AS' => '登入身份 ',
	'LBL_USER_DELETED_SUCCESSFULLY' => '用戶刪除成功',
	'LBL_ACTIVE_USERS' => '已啟用的用戶',
	'LBL_INACTIVE_USERS' => '已停用的用戶',
	'LBL_CREATE_USER' => '建立用戶',
	'LBL_DELETE_USER_PERMANENTLY' => '永久刪除用戶',
	'LBL_DELETE_USER_PERMANENTLY_INFO' => '永久刪除用戶會將所有記錄包含評論與記錄一併轉移給新用戶。',
	'LBL_RESTORE' => '恢復',
	'LBL_USER_RESTORED_SUCCESSFULLY' => '恢復用戶成功',
	//Login strings
	'LBL_TO_CRM' => '登入 CRM',
	'LBL_INVALID_USER_OR_PASSWORD' => '用戶名或密碼無效。',
	'LBL_INVALID_USER_OR_EMAIL' => '用戶名或 Email 無效。',
	'LBL_EMAIL_SEND' => '我們已經向您發送重置密碼郵件。',
	'ForgotPassword' => '忘記密碼',
	'LBL_CONNECT_WITH_US' => '聯絡我們',
	'LBL_GET_MORE' => '了解更多 Vtiger',

	'LBL_TRANSFER_RECORDS_TO_USER' => '轉移記錄給其它用戶',
	'LBL_USER_TO_BE_DELETED' => '要刪除的用戶',
	'LBL_ALMOST_THERE'	=>	'快要完成了！',
	'LBL_ABOUT_ME'		=>	'關於我',
	'LBL_WE_PROMISE_TO_KEEP_THIS_PRIVATE'	=>	'(我們承諾保證個人隱私)',
	'LBL_ALL_FIELDS_BELOW_ARE_REQUIRED'		=>	'(以下各項均為必填)',
	'LBL_GET_STARTED'	=> '開始使用',
	'LBL_YOUR_CONTACT_NUMBER' => '你的聯絡電話',
	'LBL_WHERE_ARE_YOU_FROM' =>	'你來自哪裡？',
	'LBL_SELECT_COUNTRY'	=> '選擇國家',
	'LBL_COMPANY_SIZE'		=> '公司規模',
	'LBL_JOB_TITLE'			=> '職位',
	'LBL_DEPARTMENT'		=> '部門',
	'LBL_BASE_CURRENCY'		=> '基準幣別',
	'LBL_CHOOSE_BASE_CURRENCY'	=> '選擇基準幣別',
	'LBL_OPERATING_CURRENCY'	=> '基準幣別不能修改。請選擇您的操作幣別',
	'LBL_LANGUAGE' => '語言',
	'LBL_CHOOSE_LANGUAGE'	=> '選擇語言',
	'LBL_CHOOSE_TIMEZONE'	=> '選擇時區',
	'LBL_DATE_FORMAT'		=> '日期格式',
	'LBL_CHOOSE_DATE_FORMAT'=> '選擇日期格式',
	'LBL_PHONE'	=> '電話',
	'Space' => '空格',
	//picklist values for Default Calendar View field in MyPreference Page
	'ListView' => '列表顯示',
	'MyCalendar' => '我的日曆',
	'SharedCalendar' => '分享日曆',

	'LBL_CHANGE_OWNER' => '更改擁有者',
	//'LBL_TRANSFER_OWNERSHIP' => '轉移所有權',
	'LBL_TRANSFER_OWNERSHIP_TO_USER' => '轉移所有權給用戶',
	'LBL_OWNERSHIP_TRANSFERRED_SUCCESSFULLY' => 'CRM 擁有者已更改成功',
	'LBL_OWNERSHIP_TRANSFERRED_FAILED' => 'CRM 擁有者更改失敗',
	'Account Owner' => '帳戶所有人',
	'Starting Day of the week' => '每周起始日為',
	'Day starts at' => '每日起始時段為',
	'Default Event Status' => '預設事件狀態',
	'Default Activity Type' => '預設活動狀態',
	'Default Record View' => '預設記錄顯示',
	'Left Panel Hide' => '隱藏左側面板',
	'Row Height' => '行高',

	//Change Username labels
	'LBL_CHANGE_USERNAME' => '更改用戶名',
	'LBL_USERNAME_CHANGED' => '更改用戶名成功',
	'ERROR_CHANGE_USERNAME' => '更改用戶名失敗，請稍後再試',

	'LBL_RESTORE_USER_FAILED' => '無法還原用戶，已存在同名的CRM用戶。',

	'LBL_DUPLICATE_USER_EXISTS' => '用戶已存在',

	/* For Vtiger7*/
	'LBL_USERS_SETTINGS' => '用戶設定',
	'LBL_TEMPLATES' => '樣板',
);

$jsLanguageStrings = array(

	//Curency seperator validation messages
	'JS_ENTER_OLD_PASSWORD'=>'請輸入您的舊密碼。',
	'JS_ENTER_NEW_PASSWORD'=>'請輸入您的新密碼。',
	'JS_ENTER_CONFIRMATION_PASSWORD'=>'請確認您輸入的新密碼',
	'JS_REENTER_PASSWORDS'=>'密碼不匹配相同請重新輸入。',
	'JS_INVALID_PASSWORD'=>'你必須指定一個有效的用戶名和密碼。',
	'JS_PASSWORD_CHANGE_FAILED_1'=>'用戶密碼更改失敗 ',
	'JS_PASSWORD_CHANGE_FAILED_2'=>' 失敗。必須設定新密碼。',
	'JS_PASSWORD_INCORRECT_OLD'=>'指定了不正確的舊密碼。重新輸入密碼資訊。',
	'JS_ENTERED_CURRENT_USERNAME_MSG' => '您輸入了原有的用戶名，請輸入新的用戶名。',
	'JS_NEW_ACCESS_KEY_REQUESTED' => '新的 Access key 已整合',
	'JS_CHANGE_ACCESS_KEY_CONFIRMATION' => '您已整合新的Access Key。&lt;br&gt;&lt;br&gt;使用新的 Access key 設置，您須將所有已安裝的擴展程序中的Access key自行替換為新密碼。&lt;br&gt;&lt;br&gt;您要繼續嗎？',
);
/*+***********************************************************************************
 * 臺灣繁體中文語言包 - User 用戶
 * 版本: 7.1.0 
 * 作者: Loki Jiang | https://www.facebook.com/groups/vTigerCRMtoTaiwan/
 * 更新日期: 2018-03-05
 *************************************************************************************/