<?php
/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.1
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is: vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 *************************************************************************************/
$languageStrings = array(

	// Footer
	'APPTITLE' => 'Vtiger CRM',
	'POWEREDBY'=> 'Powered by vtiger CRM',
	'LBL_READ_LICENSE' => '閲讀許可協議',
	'LBL_PRIVACY_POLICY' => '隱私條款',

	// Common Actions
	'LBL_NEW' => '新增',
	'LBL_LINKED' => '連結',
	'LBL_SELECT_ALL' => '選擇所有',
	'LBL_SELECT_TO_LOAD_LIST' => '選擇並載入列表',	
	'LBL_CREATING_NEW' => '新建',
	'LBL_ADDING_NEW' => '新增中',
	'LBL_EDITING' => '編輯中',
	'LBL_SAVE' => '儲存',
	'JS_LBL_CANCEL' => '取消',
	'LBL_BACK' => '返回',
	'LBL_IMPORT' => '匯入',
	'LBL_EXPORT' => '匯出',
	'LBL_FIND_DUPLICATES' => '查找重複項',
	'LBL_MORE' => '更多',
	//'LBL_LESS_THAN' => '小於',
	'LBL_ACTIONS' => '操作',
	'LBL_ADD' => '增加',
	'LBL_EDIT' => '編輯',
	'LBL_DELETE' => '刪除',
	'LBL_COMMENT' => '評論',
	'LBL_STARRED' => '取消追蹤',
	'LBL_NOT_STARRED' => '追蹤',
	'LBL_QUICK_VIEW' => '快速顯示',
	'LBL_NOTIFICATION_CENTER' => '通知中心',
	'LBL_NOTIFICATION' => '通知',
	'LBL_STARRED_RECORD_TO' => '%s 至 %s',
	'LBL_STARRED_RECORD_UPDATED' => '%s 升級到 %s',
	'LBL_SETTINGS'=> '設定',
	'LBL_ADD_COMMENT' => '新增評論',
	'LBL_EDIT_FIELDS' => '%s 欄位 & 佈局',
	'LBL_EDIT_WORKFLOWS' => '%s 工作流程',
	'LBL_EDIT_PICKLIST_VALUES' => '編輯下拉選單項',
	'LBL_EDIT_MAILSCANNER' => '郵件轉換',	
	'LBL_RECORD_DELETE' => '你正在試圖查看的記錄已被刪除。',
	'LBL_RECORD_NOT_FOUND' => '你正在嘗試訪問的記錄未找到。',
	'LBL_EDIT_REASON' => '編輯原因',	
	//'LBL_EDIT_CURRENT_FILTER' => 'Edit Current Filter',
	//'LBL_DELETE_CURRENT_FILTER' => 'Delete Current Filter',
	'LBL_SELECT' => '選擇',	
	'LBL_CLEAR' => '清除',	
	'LBL_YES' => '是',	
	'LBL_NO' => '沒有',
	'LBL_SHOW_COMPLETE_DETAILS' => '完整細節',
	'LBL_MINILIST_FIELDS_ARE_NOT_AVAILABLE_FOR_YOU' => '抱歉！ 多重欄位不適合於您',
	'LBL_MASS_EDITING' => '全域編輯',
	'LBL_DESELECT_ALL_RECORDS' => '取消選擇所有記錄',
	'LBL_QUICK_CREATE' => '快速建立',
	'LBL_QUICK_EDIT' => '快速編輯',
	'LBL_SEND_EMAIL' => '發送電子郵件',
	//SEND EMAIL translations
	'LBL_ALL_EMAILS' => '所有 email 帳戶',
	'LBL_MUTIPLE_EMAIL_SELECT_ONE' => 'LBL_MUTIPLE_EMAIL_SELECT_ONE',
	//SEND EMAIL translations
	'LBL_GO_TO_FULL_FORM' => '切換為完整編輯',
	'LBL_SEND_SMS' => '發送 SMS',
	'LBL_FOUND' => '被找到',
	'LBL_CLICK_ADD' => '點擊新增',
	'LBL_ADD_MORE_FIELDS' => '新增更多欄位',
	'LBL_ADD_NOTE' => '新增文件',
	'LBL_CREATE_NEW' => '新建',
	'LBL_ADD_EVENT' => '新增事件',
	'LBL_ADD_TASK' => '新增任務',
	'LBL_MARKETING_AND_SALES' => '市場行銷&銷售',
	'LBL_TOOLS_HEADER' => '工具',
	'LBL_SUPPORT' => '支援',
	'LBL_INVENTORY' => '庫存',
	'LBL_ANALYTICS' => '分析',
	'LBL_CONTACT' => '聯絡人管理',
	'LBL_HOME' => '首頁',
	'LBL_NO_ATTACHMENTS' => '沒有附件',
	'LBL_COMPOSE_EMAIL_WARNING' => ' 警告 : 您的電子郵件可能會被當作垃圾信件。將Vtiger添加到您網域的可信任來源。了解更多',
	// Common Link Labels
	'LBL_REARRANGE_DASHBOARD_TABS' => '重新排列頁籤',
	'LBL_DONE' => '完成',
	'LBL_DELETE_DASHBOARD_TAB' =>'刪除標籤',
	'LBL_DASHBOARD_TAB_ALREADY_EXIST' => '標籤名稱已存在',
	'LBL_TABS_LIMIT_EXCEEDED' => '抱歉！無法添加10個以上標籤',
	'LBL_TODOS' => '任務',
	'LBL_LAST_VIEWED_RECORDS' => '最近瀏覽記錄',
	'LBL_DASHBOARD' => '資訊主頁',
	'LBL_USER_SETTINGS' => '用戶設定',	
	'LBL_MY_PREFERENCES' => '個人偏好設定',
	'LBL_SIGN_OUT' => '登出',	
	'LBL_HELP' => '幫助',	
	'LBL_DOCUMENTATION' => '文件',
	'LBL_VIDEO_TUTORIAL' => '視頻教程',
	'LBL_FEEDBACK' => '回饋',
	'LBL_CHAT_SUPPORT'=>'線上支援',
	'LBL_CRM_SETTINGS' => 'CRM 設定',
	'LBL_ON_DEMAND_ADMIN' => '新增 / 刪除用戶',
	'LBL_ANNOUNCEMENT' => '公告',
	'LBL_CALENDAR' => '日曆',
	'LBL_POST' => '提交',
	'LBL_GUIDER' => '引導',
	'LBL_VIDEOS' => '影片',
	'LBL_DISPLAY_TYPE' => '顯示類型',
	'LBL_DISPLAY_WIDETYPE' => '寬',
	'LBL_DISPLAY_MEDIUMTYPE' => '中',
	'LBL_DISPLAY_NARROWTYPE' => '窄',	
	'LBL_TAG_THIS_RECORD' => '標籤此記錄',	
	'LBL_SAME_TAG_EXISTS' => '存在重複的標籤',
	'LBL_MAKE_PUBLIC' => '公開',
	'LBL_PAGE' => '頁',
	'LBL_LISTVIEW_PAGE_JUMP' => '跳頁',
	'LBL_LISTVIEW_JUMP_TO' => '跳轉到',
	'LBL_PROFILE_PASSWORD' => '配置 / 密碼',
	'LBL_INFO' => '資訊',
	'LBL_CANT_MOVE_FROM_PUBLIC_TO_PRIVATE' => '無法將公用標籤轉為私人標籤',
	'LBL_EDIT_TAG'=>'編輯標籤',
	//'LBL_NO_TAG_EXISTS' => '標籤不存在' ,
	'LBL_RELATED_USERS' => '關聯用戶',

	// Common Fields
	'LBL_USER' => '用戶',
	//'LBL_GROUP' => '合併計稅',
	'Last Modified By' => '最後修訂者',
	'Created Time' => '建立時間',
	'Modified Time' => '修改時間',
	'Description' => '描述',
	'Assigned To'=>'負責人',

	//Loading Labels
	'LBL_LOADING' => '載入中',
	'LBL_LOADING_WIDGET' => '小工具載入中',
	'LBL_LOADING_LISTVIEW_CONTENTS'	=> '載入中，請稍候。',

	// Detail View
	'LBL_HISTORY' => '歷史記錄',
	'LBL_UPDATES' => '更新',
	'LBL_SHOW_FULL_DETAILS' => '顯示完整細節',
	'LBL_SUMMARY_DETAILS' => '摘要細節',
	'LBL_ADD_NEW_COMMENT' =>'新增評論',
	'LBL_NO_UPDATES' => '沒有更新',
	'LBL_ACTIVITIES' => '活動',
	'LBL_NO_PENDING_ACTIVITIES' => '沒有待辦活動',	
	'LBL_SUMMARY' => '摘要',	
	'LBL_KEY_FIELD' => '重點欄位',
	'LBL_DETAILS' => '細節',
	'LBL_NAME_EMAIL' => '名稱和電子郵件',

	// Popup window
	'LBL_SEARCH_FOR' => '搜尋',
	'LBL_IN' => 'in',
	'LBL_TYPE_SEARCH' => '查找',
	'LBL_SEARCH_BUTTON' => '搜尋按鈕',
	'LBL_ADVANCE_SEARCH' => '進階搜尋',
	'LBL_LOADING_PLEASE_WAIT' => '載入中，請稍候。',
	'LBL_PLEASE_SELECT_MODULE' => '請選擇模組搜尋',

	//DropDown Category
	'LBL_USERS' => '用戶',
	'LBL_GROUPS' => '群組',

	//EditView Form Links
	'LBL_FULL_FORM' => '完整表單',	
	'LBL_SIMPLE_FORM' => '簡易表單',

	//Recent Comments
	'LBL_IS_REMOVED' => '已刪除',
	'LBL_ADD_YOUR_COMMENT_HERE' => '在這裡新增你的評論...',
	'LBL_REASON_FOR_CHANGING_COMMENT' => '修改評論的原因',	
	'LBL_REPLY' => '回覆',
	'LBL_VIEW_THREAD' => '查看主題',	
	'LBL_NO_COMMENTS' => '沒有評論',	
	'LBL_REPLIES' => '回覆',	
	'LBL_REPLY_ALL' => '回覆全部',

	//Translation for all modules
	'Accounts' => '客戶',
	'Assets' => '保固合約',
	'Calendar' => '日曆',
	'Campaigns' => '行銷活動',
	'Contacts' => '聯絡人',
	'Documents' => '文件',
	'Leads' => '潛在客戶',
	'ModComments' => '評論',
	'Potentials' => '銷售機會',
	'PriceBooks' => '價目表',
	'Products' => '產品',
	'Project' => '專案',
	'ProjectMilestone' => '專案里程碑',
	'ProjectTask' => '專案任務',
	'ServiceContracts' => '服務合約',
	'Services' => '服務',
	'Vendors' => '供應商',
	'Rss' => 'RSS',
	'Quotes'=>'報價單',
	'PurchaseOrder'=>'採購訂單',
	'SalesOrder'=>'銷售訂單',
	'Invoice'=>'出貨單',
	'MailManager' => '郵件管理',
	'Activities' => '活動',
	'Portal' => '我們的網站',
	'Email Templates' => '電子郵件樣板',
	'Recycle Bin' => '垃圾桶',

	//Basic String Translation
	'LBL_ADD_RECORD' => '新增記錄',
	'LBL_RECENTLY_MODIFIED' => '最近修改',
	'LBL_RECORDS_LIST' => '記錄列表',
	'LBL_RECORD_SUMMARY' => '模組摘要',
	//'LBL_RECORD_SUMMARY' => '模組細節',
	'LBL_ACCESS_DENIED_FOR' => '訪問被拒',
	'LBL_GO_BACK' => '返回',
	'LBL_NO_DATA_AVAILABLE' => '無可用資料',

	// Global Search
	'LBL_GLOBAL_SEARCH' => '輸入關鍵字並按下ENTER',
	'LBL_ALL_RECORDS' => '所有記錄',
	'LBL_NO_RECORDS_FOUND' => '未找到記錄',

	//Filters & Advance Filter
	'LBL_AND' => '和',
	'LBL_OR' => '或',
	'LBL_APPLBL_NONEROVE' => '同意',
	'LBL_DENY' => '拒絶',
	'LBL_EQUALS' => '等於',
	'LBL_NOT_EQUAL_TO' => '不等於',
	'LBL_STARTS_WITH' => '開始於',
	'LBL_ENDS_WITH' => '結束於',
	'LBL_CONTAINS' => '包含',
	'LBL_DOES_NOT_CONTAIN' => '不包含',
	'LBL_LESS_THAN' => '小於',
	'LBL_GREATER_THAN' => '大於',
	'LBL_LESS_THAN_OR_EQUAL' => '小於等於',
	'LBL_GREATER_OR_EQUAL' => '大於等於',
	'LBL_BEFORE' => '之前',
	'LBL_AFTER' => '之後',
	'LBL_BETWEEN' => '之間',
	'LBL_SEARCH' => '搜尋',
	'LBL_SEARCH_IN' => '搜尋範圍',
	'LBL_ADD_CONDITION' => '新增條件',
	'LBL_ADD_GROUP' => '新增條件組',
	'LBL_FILTER_CONDITIONS' => '篩選條件',
	'LBL_ALL_CONDITIONS' => '所有條件',
	'LBL_ALL_CONDITIONS_DESC' => '所有條件都必須滿足',
	'LBL_ANY_CONDITIONS' => '任意條件',
	'LBL_ANY_CONDITIONS_DESC' => '必須至少一個條件滿足',
	'LBL_SELECT_FIELD' => '選擇欄位',
	'LBL_SELECT_MODULE' => '選擇模組',
	'LBL_CREATE_NEW_FILTER' => '建立新篩選',
	'All' => '所有',
	'Others' => '其它',
	'Pending' => '待定',
	'Public' => '公開',

	//Advance Search
	'LBL_SAVE_FILTER' => '儲存篩選',
	'LBL_SAVE_MODIFY_FILTER' => '儲存/修改篩選',
	'LBL_SEARCH_RESULTS' => '搜尋結果',
	'LBL_SAVE_AS_FILTER' => '另存為篩選',

	//Exception String Translation
	'LBL_NOT_ACCESSIBLE' => '拒絶訪問',

	//Line Items
	'LBL_ITEM_DETAILS'=> '產品明細',
	'LBL_CURRENCY' => '幣別',
	'LBL_TAX_MODE' => '稅制模式',
	'LBL_INDIVIDUAL' => '單項計稅',
	'LBL_GROUP' => '合併計稅',
	'LBL_TOOLS' => '工具',
	'LBL_ITEM_NAME' => '項目名稱',
	'LBL_QTY_IN_STOCK' => '庫存',
	'LBL_QTY' => '數量',
	'LBL_LIST_PRICE' => '定價',
	'LBL_TOTAL' => '合計',
	'LBL_NET_PRICE' => '淨價',
	'LBL_DISCOUNT' => '折扣',
	'LBL_TOTAL_AFTER_DISCOUNT' => '折扣後總計',
	'LBL_TAX' => '稅金',
	'LBL_ADD_PRODUCT' => '新增產品',
	'LBL_ADD_SERVICE' => '新增服務',
	'LBL_LI_ADD_PRODUCT' => '產品',
	'LBL_LI_ADD_SERVICE' => '服務',
	'LBL_ITEMS_TOTAL' => '項目總計',
	'LBL_SHIPPING_AND_HANDLING_CHARGES' => '郵資包裝費',
	'LBL_PRE_TAX_TOTAL' => '稅前合計',
	'LBL_TAX_FOR_SHIPPING_AND_HANDLING' => '郵資包裝費之稅金',
	'LBL_SET_SHIPPING_AND_HANDLING_TAXES_FOR' => '設定郵資包裝費的稅金為',
	'LBL_ADJUSTMENT' => '調整',
	'LBL_DEDUCT' => '減少',
	'LBL_GRAND_TOTAL' => '合計',
	'LBL_ZERO_DISCOUNT' => '無折扣',
	'LBL_OF_PRICE' => '價格',
	'LBL_DIRECT_PRICE_REDUCTION' => '直接降價',
	'LBL_SET_DISCOUNT_FOR' => '設定折扣為',
	'LBL_STOCK_NOT_ENOUGH' => '庫存不足',
	'LBL_MAX_QTY_SELECT' => '最大值為',
	'LBL_DRAG' => '按住滑鼠拖曳',
	'LBL_TOTAL_TAX_AMOUNT' => '稅金總額',
	'LBL_DIRECT_AMOUNT_DISCOUNT' => '直接金額折扣',
	'LBL_FINAL_DISCOUNT_AMOUNT' => '最終折扣金額',
	'LBL_MORE_CURRENCIES' => '更多幣別',
	'LBL_SET_TAX_FOR' => '設定稅金為',
	'LBL_GROUP_TAX' => '合併計稅為',
	'LBL_BILLING_ADDRESS_FROM' => '複製帳單地址從',
	'LBL_SHIPPING_ADDRESS_FROM' => '複製收貨地址從',
	'LBL_COPY_SHIPPING_ADDRESS' => '出貨地址',
	'LBL_COPY_BILLING_ADDRESS' => '帳單地址',
	'LBL_OVERALL_DISCOUNT' => '整體折扣',
	'LBL_CHARGES' => '費用',
	'LBL_CHARGES_TOTAL' => '費用合計',
	'LBL_TAXES_ON_CHARGES' => '費用 (稅金)',
	'LBL_DEDUCTED_TAXES' => '扣除稅金',
	'LBL_DEDUCTED_TAXES_TOTAL' => '扣除稅金總額',
	'LBL_DEFAULT' => '預設',
	'LBL_ITEM' => '項目',
	'LBL_ADD_DASHBOARD' =>'新增資訊主頁',

	//DetailView Actions
	'LBL_CREATE' => '建立',
	'LBL_GENERATE' => '產生',	
	'LBL_DUPLICATE' => '複製',
	'Add Note' => '新增文件',

	//Dashboard String
	'LBL_ADD_WIDGET' => '新增小工具',
	'LBL_COMMENTS' => '評論',
	'LBL_REFRESH' => '重新整理',
	'LBL_CLOSE' => '關閉',
	'LBL_ALL' => '全部',
	'LBL_UPDATED' => '已更新',
	'LBL_VIA_TASK' => '通過任務',
	'LBL_form' => '從',
	'LBL_FROM' => '來自',
	'LBL_TO' => 'To',
	'LBL_to' => 'to',
	'LBL_ON' => '在',
	'LBL_OF' => 'of',
	'LBL_BY' => '由',
	'LBL_ADDED' => '已添加',
	'LBL_FOR' => '為',
	'LBL_CREATED' => '已建立',
	'LBL_DELETED' => '已刪除',
	'LBL_RESTORED' => '已還原',
	'LBL_COMMENTED' => '已評論',
	'LBL_REMOVED' => '已移除',
	'LBL_REMOVE' => '移除',
	'LBL_AT' => '在',
	'LBL_MINE' => '我的',
	'LBL_ME' => '我',
	'History' => '歷史記錄',
	'Upcoming Tasks' => '即將開始的任務',
	'LBL_YEAR' => '年',
	'LBL_YEARS' => '年',
	'LBL_MONTH' => '月',
	'LBL_MONTHS' => '月',
	'LBL_DAY' => '日',
	'LBL_DAYS' => '天',
	'LBL_DAY(S)' => 'LBL_DAY',
	'LBL_HOUR' => '小時',
	'LBL_HOURS' => '小時',
	'LBL_HOUR(S)' => '小時',
	'LBL_MINUTE' => '分',
	'LBL_MINUTES' => '分',
	'LBL_SECOND' => '秒',
	'LBL_SECONDS' => '秒',
	'LBL_JUSTNOW' => '剛才',
	'LBL_CUSTOM_INFORMATION' => '自訂資訊',
	'LBL_NO_RECENT_UPDATES' => '最近沒有更新',
	'LBL_NO_DATA' => '沒有資料',
	'LBL_PERMISSION_DENIED' => '權限被拒',
	'LBL_HANDLER_NOT_FOUND' => '處理程序未找到',
	'LBL_FILTER' => '過濾器',
	'LBL_DUE' => '待收',
	//'LBL_DAYS' => '天',
	'LBL_COMPLETED' => '已完成',
	'LBL_AGO' => '以前',
	'LBL_CHANGED' => '變更',	
	'Single_Users' => '用戶',	
	'LBL_MATCHED_THIS_CRITERIA' => '條件符合',
	'LBL_NO_SCHEDULED_ACTIVITIES' => '沒有預定的活動',
	'LBL_NO_OVERDUE_ACTIVITIES' => '無逾期活動',
	'LBL_NO_UPDATES_OR_COMMENTS' => '沒有更新或評論',	
	'LBL_MINI_LIST' => '迷你清單',	
	'LBL_NOTEPAD' => '記事本',
	'LBL_NOTEPAD_NAME' => '記事本名稱',		
	'LBL_NOTEPAD_CONTENT' => '記事本內容',
	'LBL_LAST_SAVED_ON' => '最後儲存於',
	'Mini List' => '迷你清單',
	'Notebook' => '記事本',
	'LBL_RESULT_FOR_THE_TAG' => '此標籤的結果',	
	'LBL_ALL_USERS' => '所有用戶',
	'LBL_BOTH' => '都',
	'LBL_SHOW' => '顯示',
	'LBL_MY' => '我的',
	'LBL_SELECT_DATE_RANGE' => '選擇日期範圍',

	// Basic Strings- custom view
	'LBL_VIEW_NAME' => '查看名稱',	
	'LBL_CREATE_VIEW' => '建立新顯示',
	'LBL_BASIC_DETAILS' => '基本細節',	
	'LBL_CHOOSE_COLUMNS' => '選擇列和順序',
	'LBL_MAX_NUMBER_FILTER_COLUMNS' => '最大 15',    	
	'LBL_FILTER_ON_DATE' => '篩選日期',
	'LBL_CHOOSE_FILTER_CONDITIONS' => '選擇篩選條件',
	//'LBL_ADD_CONDITION' => '新增條件',
	'LBL_SET_AS_DEFAULT' => '設為預設',	
	'LBL_LIST_IN_METRICS' => '在首頁的關鍵指標中顯示',	
	'LBL_SET_AS_PUBLIC' => '設為公開',	
	//'LBL_AND' => '和', 
	//'LBL_OR' => '或',
	'LBL_ADD_MORE_COLUMNS' => '新增更多列',
	//'LBL_ADD_GROUP' => '新增條件組',

	//DateFilter Conditions
	'LBL_CUSTOM' => '自訂',
	'LBL_PREVIOUS_FY' => '上一財年',	
	'LBL_CURRENT_FY' => '本財年',
	'LBL_NEXT_FY' => '下一財年',
	'LBL_PREVIOUS_FQ' => '上一財季',
	'LBL_CURRENT_FQ' => '本財季',
	'LBL_NEXT_FQ' => '下一財季',
	'LBL_YESTERDAY' => '昨天',
	'LBL_TODAY' => '今天',
	'LBL_TOMORROW' => '明天',
	'LBL_LAST_WEEK' => '上週',	
	'LBL_CURRENT_WEEK' => '本週',
	'LBL_NEXT_WEEK' => '下周',
	'LBL_LAST_MONTH' => '上月',
	'LBL_CURRENT_MONTH' => '本月',
	'LBL_NEXT_MONTH' => '下月',	
	'LBL_LAST_7_DAYS' => '最近7天',
	'LBL_LAST_14_DAYS' => '最近14天',
	'LBL_LAST_30_DAYS' => '最近30天',
	'LBL_LAST_60_DAYS' => '最近60天',	
	'LBL_LAST_90_DAYS' => '最近90天',
	'LBL_LAST_120_DAYS' => '最近120天',
	'LBL_NEXT_30_DAYS' => '未來30天',	
	'LBL_NEXT_60_DAYS' => '未來60天',
	'LBL_NEXT_90_DAYS' => '未來90天',	
	'LBL_NEXT_120_DAYS' => '未來120天',

	//advanced Filter Options
	'LBL_NONE' => '無',
	//'LBL_EQUALS' => '等於',
	//'LBL_NOT_EQUAL_TO' => '不等於',
	//'LBL_STARTS_WITH' => '開始於',
	//'LBL_ENDS_WITH' => '結束於',
	//'LBL_CONTAINS' => '包含',
	//'LBL_DOES_NOT_CONTAIN' => '不包含',
	//'LBL_LESS_THAN' => '小於',
	//'LBL_GREATER_THAN' => '大於',
	//'LBL_LESS_THAN_OR_EQUAL' => '小於等於',
	//'LBL_GREATER_OR_EQUAL' => '大於等於',
	//'LBL_BEFORE' => '之前',
	//'LBL_AFTER' => '之後',
	//'LBL_BETWEEN' => '之間',
	'LBL_IS_EMPTY' => '為空',
	'LBL_IS_NOT_EMPTY' => '不為空',
	'LBL_APPROVE' => '批准',
	'LBL_HAS_CHANGED' => '已更改',
	'LBL_HAS_CHANGED_TO' => '已更改於',
	'LBL_HAS_CHANGED_FROM' => '已更改自',
	'LBL_LESS_THAN_OR_EQUAL_TO' => '小於或等於',
	'LBL_GREATER_THAN_OR_EQUAL_TO' => '大於或等於',
	'LBL_IS_NOT' => '不為',
	'LBL_IS_ADDED' => '已增加',
	'LBL_IS_TODAY' => '為今天',
	'LBL_IS_TOMORROW' => '為明天',
	'LBL_IS_YESTERDAY' => '為昨天',
	'LBL_LESS_THAN_DAYS_LATER' => '小於幾天後',
	'LBL_MORE_THAN_DAYS_LATER' => '大於幾天後',

	//Detail view summary widgets
	'LBL_OWNER' => '我的',	
	'LBL_CREATED_ON' => '建立於',
	'LBL_MODIFIED_ON' => '修改於',
	'LBL_MODIFIED' => '已修改',	
	//'LBL_COMMENTED' => '已評論',

	//calender set-reminder
	'LBL_BEFORE_EVENT' => ' 事件之前',

	//Dashboard widgets
	//'History' => '歷史記錄',
	'Upcoming Activities' => '近期活動',
	'Overdue Activities' => '逾期活動',
	'Funnel' => '銷售漏斗',	
	'Potentials by Stage' => '銷售機會階段統計',
	'Pipelined Amount' => '銷售渠道',
	'Total Revenue' => '總營收',
	'Top Potentials' => '熱門銷售機會',
	'Forecast' => '預測',	
	'Leads Created' => '已建立的潛在客戶',
	'Leads by Status' => '依狀態顯示潛在客戶',
	'Leads by Source' => '依來源顯示潛在客戶',
	'Leads by Industry' => '依行業顯示潛在客戶',
	'Tickets by Status' => '依狀態顯示客服記錄',
	'Open Tickets' => '待處理的客服記錄',
	'Funnel Amount' => '分階段統計的總金額',
	'Key Metrics' => '關鍵指標',
	//'Mini List' => '迷你清單',
	'Tag Cloud' => '標籤雲',
	//'Notebook' => '記事本',

	//Exports strings
	'LBL_EXPORT_ALL_DATA' => '匯出所有數據',
	'LBL_EXPORT_DATA_IN_CURRENT_PAGE' => '匯出當前頁數據',
	'LBL_EXPORT_SELECTED_RECORDS' => '匯出選定的記錄',	
	'LBL_EXPORT_RECORDS' => '匯出記錄',	
	'LBL_NO_RECORD_SELECTED' => '未選擇記錄',
	'LBL_CAN_NOT_REMOVE_DEFAULT_WIDGET' => '不能移除預設小工具',	
	'LBL_CUSTOM_VIEW_NAME_DUPLICATES_EXIST' => '篩選器已經存在',
	'LBL_TYPE_AND_SEARCH' => '類型搜索',
		'LBL_EXPORT_CURRENCY_TOOLTIP_TEXT'=>'為了匯出項目中的幣別值，Vtiger將使用此設定匯出為幣別。訂單項目中的任何幣別將以用戶的首選幣別為主 (修改在 \'我的偏好選項\')',
		'LBL_EXPORT_LINEITEM_CURRENCY'=>'選擇幣別 (針對訂單項目)',
		'LBL_EXPORT_USER_CURRENCY' =>'我的首選幣別',
		'LBL_EXPORT_RECORD_CURRENCY'=>'在記錄中指定幣別',
	'LBL_EXPORT_FORMAT' => '匯出格式',
	'LBL_EXPORT_DATA' => '匯出日期',

	'LBL_CUSTOMIZE' => '自訂',
	'LBL_ADD_MANAGE_MODULES' => '模組',
	'LBL_CUSTOMIZE_MAIN_MENU' => '左選單',
	'LBL_LABELS' => '標籤',
	'LBL_WORKFLOWS' => '工作流程',
	'LBL_PICKLIST' => '下拉選單',

	// Added Common Keys for all modules
	'Account Name' => '公司名稱',
	'Add Comment' => '新增評論',
	'Adjustment' => '調整',
	'Annual Revenue' => '年度營收',
	//'Apparel'=>'服飾業',
	//'Banking'=>'銀行業'
	'Billing Address' => '帳單地址',
	'Billing City' => '鄉鎮市區 (帳單)',
	'Billing Code' => '郵遞區號 (帳單)',
	'Billing Country' => '國家 (帳單)',
	'Billing Po Box' => '郵政信箱 (帳單)',
	'Billing State' => '縣/市 (帳單)',
	//'Biotechnology'=>'生物技術', 

	//for SO PO and Quotes
	'FedEx'=>'FedEx (聯邦快遞)',	
	'UPS'=>'UPS(聯合包裹)',
	'USPS'=>'USPS (美國郵政)',
	'DHL'=>'DHL (德國郵政)',
	'BlueDart'=>'BlueDart(藍標快遞)',
	'Carrier' => '快遞公司',
	'Category'=>'分類',
	//'Chemicals'=>'化工',
	'City' => '鄉鎮市區',

	'Cold Call'=>'電話行銷',
	'Existing Customer'=>'老客戶推薦',	
	'Self Generated'=>'自動產生',
	'Employee'=>'員工推薦',
	'Partner'=>'合作夥伴',
	'Public Relations'=>'公關傳媒',
	'Direct Mail'=>'郵件推銷',
	'Conference'=>'論壇會議',
	'Trade Show'=>'展場會',	
	'Web Site'=>'網站',
	'Word of mouth'=>'口碑',
	'Other' => '其它',	

	//for leads and accounts
	'--None--'=>'--無--',
	'Acquired'=>'已獲得',
	'Active'=>'啟用',
	'Market Failed'=>'行銷失利',
	'Project Cancelled' => '已取消的專案',
	'Shutdown'=>'中斷',
	'Apparel'=>'服飾業',
	'Banking'=>'銀行業',
	'Biotechnology'=>'生物技術', 
	'Chemicals'=>'化工',
	'Communications'=>'交通',
	'Construction'=>'建築',
	'Consulting'=>'諮詢',
	'Education'=>'教育',
	'Electronics'=>'電子',
	'Energy'=>'能源',
	'Engineering'=>'工程',
	'Entertainment'=>'娛樂',
	'Environmental'=>'環保',
	'Finance'=>'金融',
	'Food & Beverage'=>'食品與飲料',
	'Government'=>'政府',	
	'Healthcare'=>'保健',	
	'Hospitality'=>'飯店',
	'Insurance'=>'保險',
	'Machinery'=>'機械',
	'Manufacturing'=>'製造',
	'Media'=>'媒體',	
	'Not For Profit'=>'非盈利機構',
	'Recreation'=>'遊憩',	
	'Retail' => '零售',	
	'Shipping'=>'航運',	
	'Technology'=>'科技',
	'Telecommunications'=>'電信',
	'Transportation' => '運輸',
	'Utilities'=>'公用事業',	

	'Contact Name' => '聯絡人',
	'Conversion Rate' => '匯率',

	'Shipping Address' => '收貨地址',
	'Shipping City' => '鄉鎮市區 (運貨)', 
	'Shipping State' => '縣/市 (運貨)',
	'Shipping Code' => '郵遞區號 (運貨)',
	'Shipping Country' => '國家 (運貨)',
	'Shipping Po Box' => '郵政信箱 (運貨)',
	'Country' => '國家',
	//'Description' => '描述',

	'Created'=>'已建立',
	'Approved'=>'已批准',
	'Delivered'=>'已發送',
	'Cancelled'=>'已取消',

	'Currency' => '幣別',
	'LBL_BASE_CURRENCY' => '基準幣別',

	'Discount Percent' => '折扣率',
	'Discount Amount' => '折扣金額',
	'Item Discount Amount' => '折扣額項',
	'Net Price' => '淨價', 
	'Item Discount Percent' => '折扣率項',

	'Due Date' => '給付日期',
	'Due Date & Time' => '給付日期及時間',
	'Email' => '電子郵件',	
	'Secondary Email' => '備用 Email',
	'Other Email' => '其它 Email',
	'Email Opt Out' => '拒絶 Email 騷擾',
	'Is Converted From Lead' => '是否由潛在客戶轉換而來',
	'Expected Close Date' => '預計關閉日期',
	'Fax' => '傳真',	

	'Last Name' => '姓名',
	'First Name' => '英文名',	

	'High' => '高',
	'Low' => '低',
	'In Progress' => '處理中',

	'Subject' => '主題',
 	//'Shipping Address' => '收貨地址',
	//'Shipping Po Box' => '郵政信箱(運送)',
	//'Shipping City' => '鄉鎮市區(運送)', 
	//'Shipping State' => '縣/市(運送)',
	//'Shipping Code' => '郵遞區號(運送)',
	//'Shipping Country' => '國家(運送)',
	'Terms & Conditions' => '條款及細則',
	'Item Name' => '項目名稱',
	'Quantity' => '數量',
	'List Price' => '標價',
	'Image' => '圖片',
	'Purchase Cost' => '採購成本',
	'Margin' => '保證金',
	'Item Comment' => '項目註釋',
	'Tax1' => '稅1',
	'Tax2' => '稅2',
	'Tax3' => '稅3',
	'Excise Duty' => '貨物稅',	
	'Total' => '總計',
	'Sub Total' => '小計',
	'Tax Type' => '稅務類型',
	//'S&H Amount' => '郵資包裝附加費',
	'Status' => '階段',	
	'Vendor Name'=>'供應商名稱',

	'LBL_ADDRESS_INFORMATION' => '詳細地址',
	'LBL_DESCRIPTION_INFORMATION' => '詳細介紹',
	'LBL_TERMS_INFORMATION' => '條款及細則',
	'LBL_PRICING_INFORMATION' => '價格資訊',
	'LBL_RELATED_PRODUCTS' => '產品細節',
	'LBL_REMINDER_INFORMATION' => '提醒資訊',	

	'LBL_FOLDER_SAVED' => '資料夾已儲存',
	'LBL_FOLDER_EXISTS' => '資料夾已存在',		
	'LBL_FOLDER_DELETED' => '資料夾已刪除',
	'LBL_EDIT_FOLDER' => '編輯資料夾',

	'Lead Source' => '潛在客戶來源',
	'Mobile' => '手機',

	'Notify Owner' => '提醒負責人',
	'Other Phone' => '備用電話',
	'Phone' => '常用電話',

	'State' =>  '縣/市',
	'Po Box' => '郵政信箱',
	'Postal Code' => '郵遞區號',

	'Potential Name' => '銷售機會名稱',
	'Priority'=>'優先級',

	'Product Name' => '產品名稱',
	'Rating' => '評價',

	'Related To'=>'關聯於',
	'Type' => '類型',

	'Reviewed' => '評論',
	'Salutation' => '稱謂',
	'Street' => '地址',	
	'Support Start Date' => '支援開始日期',
	'Support Expiry Date' => '支援到期日',
	'Sales Start Date'=>'銷售開始日期',
	'Sales End Date'=>'銷售結束日期',	

	//Dashboard list of widgets translation
	//'Open Ticktes' => '待處理的客服記錄',
	'LBL_SELECT_STATUS' => '選擇狀態',	
	'LBL_BLANK' => '-空-',

	//PageTitle translations
	'LBL_VTIGER_CRM_HONEST_OPEN_SOURCE' => 'vtiger CRM On Demand',

	//Translations used in inventory modules for sopy address
	'SINGLE_Accounts' => '客戶',
	'SINGLE_Contacts' => '聯絡人',

	//Weekdays in 3 letters translations
	'LBL_Sun' => '週日',	
	'LBL_Mon' => '週一',
	'LBL_Tue' => '週二',
	'LBL_Wed' => '週三',
	'LBL_Thu' => '週四',
	'LBL_Fri' => '週五',
	'LBL_Sat' => '週六',

	//Months in 3 letters translations
	'LBL_Jan' => '1月',
	'LBL_Feb' => '2月',	
	'LBL_Mar' => '3月',
	'LBL_Apr' => '4月',	
	'LBL_May' => '5月',
	'LBL_Jun' => '6月',
	'LBL_Jul' => '7月',
	'LBL_Aug' => '8月',
	'LBL_Sep' => '9月',	
	'LBL_Oct' => '10月',
	'LBL_Nov' => '11月',	
	'LBL_Dec' => '12月',	

	'LBL_CALENDAR_SETTINGS' => '日曆設定',	
	'Reminder Interval' => '彈出提醒時間間隔',

	//Translations used in inventory modules for address
	//'SINGLE_Accounts' => '客戶',
	//'SINGLE_Contacts' => '聯絡人',
	'HelpDesk' => '客服記錄',	
	'LBL_TAG_CLOUD' => '標籤雲',

	'LBL_NO_RECORDS' => '沒有記錄',
	'LBL_NO_RELATED' => '沒有相關',		
	'LBL_GLOBAL_SEARCH_MAX_MESSAGE' => '僅顯示在所有模組中查詢的前 100 條記錄。如果要查看特定模組的結果，請選擇相應模組並搜尋。',
	'LBL_GLOBAL_SEARCH_MAX_MESSAGE_FOR_MODULE' => '僅顯示前 100 條記錄。如果未找到滿意的記錄，請使用進階搜尋。',

	// used in reports detail view
	'LBL_ACTION' => '操作',	
	'LBL_NOTE' => '注意',
	'LBL_SELECT_OPTION' => '請選擇',	

	//Module Manager
	'LBL_TOOLTIP' => '提示工具管理',
	'LBL_MODULE_SEQUENCE_NUMBERING' => '%s 序列編號',
	'LBL_CUSTOM_FIELD_MAPPING' => '自訂欄位映射',
	'LBL_WEBFORMS' => 'Web 表單',

	//Compose Email Strings
	'SINGLE_Emails' => '電子郵件',
	'Emails' => '電子郵件',
	'LBL_SELECT_EMAIL_IDS' => '選擇電子郵件地址',
	'LBL_SUBJECT' => '主題',
	'LBL_ATTACHMENT' => '附件',	
	'LBL_BROWSE_CRM' => '瀏覽 CRM',	
	'LBL_SEND' => '發送',
	'LBL_SAVE_AS_DRAFT' => '另存為草稿',
	'LBL_GO_TO_PREVIEW' => '預覽',
	'LBL_SELECT_EMAIL_TEMPLATE' => '選擇郵件樣板',
	'LBL_COMPOSE_EMAIL' => '撰寫電子郵件',
	'LBL_CC' => '副本',
	'LBL_BCC' => '密件副本',
   	'LBL_ADD_CC' => '新增副本',
	'LBL_ADD_BCC' => '新增密件副本',
	'LBL_MAX_UPLOAD_SIZE' => '最大上傳限制',
	'LBL_EXCEEDED' => '已超出限制',	
	'LBL_OPERATION_NOT_PERMITTED' => '不允許操作',	
	'LBL_MERGE' => '合併',
	//'LBL_FIND_DUPLICATES' => '查找重複項',
	'LBL_MERGING_CRITERIA_SELECTION' => '合併條件選擇',
	'LBL_AVAILABLE_FIELDS' => '可用欄位',	
	'LBL_MERGE_RECORDS_DESCRIPTION' => '合併後的主要記錄將被保留。您可以選擇的列值保留。其他的記錄將被刪除，但相關資訊將被合併。',	
	'LBL_MERGE_RECORDS_IN' => '合併記錄在',
	'LBL_FIELDS' => '欄位',	
	'LBL_RECORD' => '記錄',	
	'LBL_NO_DUPLICATED_FOUND' => '沒有找到重複的記錄',
	'LBL_MERGE_SELECT' => '合併選擇',	

	//sbproducts translation
	'LBL_BACK_TO_PRODUCTS' => '返回產品',	

	//Translations used for Export to Pdf
	'Valid Date' => '有效日期',
	'Phone: ' => '電話: ',
	'Issued Date' => '簽發日期',
	'Shipping & Handling Charges' => '郵資包裝費',
	'Shipping & Handling Tax:' => '郵資包裝費稅:',	
	'Discount'=>'折扣',
	'Net Total' => '總淨額',
	'Product Code' => '產品代碼',
	'Customer Name'=>'客戶名稱',
	'Price'=>'價格',
	'Tax:' => '稅金:',
	//'Contact Name' => '聯絡人姓名',
	'Grand Total:' => '累計:',	
	'Fax: ' => '傳真: ',
	'Website: ' => '網址: ',
	'Tax' => '稅金',
	'LBL_ALPHABETS' => 'A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z',

	//Realted tab strings
	'Service Contracts' => '服務合約',
	'Projects' => '專案',
	'Sales Order' => '銷售訂單',			
	'Purchase Order' => '採購訂單',
	'Payments' => '付款',
	'List and Campaigns' => '行銷活動列表',		
	'Project Tasks' => '專案任務',
	'Project Milestones' => '專案里程碑',

	'Labels Editor' => '標籤編輯器',
	'LBL_IGNORE_EMPTY_VALUES' =>'忽略空值',	

	//Related tabs of Products
	'Product Bundles' => '產品搭售',
	'Parent Product' => '父產品',	
	'LBL_PRODUCT_BUNDLE' => '產品搭售',
	'LBL_EDIT_QUANTITY' => '編輯數量',
	'LBL_ADD_TO_PRODUCTS' => '新增產品',

	'LBL_MANAGE_USERS' => '管理用戶',
	'LBL_TRANSFER_OWNERSHIP' => '轉移所有權',
	'LBL_SELECT_RELATED_MODULES' => '選擇相關的模組',
	'LBL_ASSIGNED_TO' => '指派給',
	//Comments Field Labels for Workflow
	'Comment' => '評論',
	'Last Comment' => '最新評論',
	'Last 5 Comments' => '最新 5 條評論',
	'All Comments' => '所有評論',

	//Feedback on removing old version
	'LBL_OLD_VERSION_REMOVED_SOON' => '關於舊介面的注意事項',
	'LBL_FEEDBACK_ON_REMOVING_OLD_VERSION' => '我們很高興與您分享，2014年2月之前將會拋棄舊款。我們在最近的新介面中增加了以下功能<br><br>1. 樞紐報表<br>2. 自訂圖表<br>3. 快速搜尋列表<br><br>如果您有關於新介面的建議，請在下面與我們分享。',
	'LBL_FEEDBACK_PLACEHOLDER' => '在此分享你的建議..',
	'LBL_SUBMIT_FEEDBACK' => '提交反應',
	'LBL_DONT_SHOW_AGAIN' => '不再顯示',
	'LBL_CONTINUE_TO_OLD_LOOK' => '沿用舊介面',
	'LBL_LEFT_PANEL_SHOW_HIDE' => '左側面板 顯示/隱藏',

	//Products Popup View
	'NOT_A_BUNDLE' => '不是產品搭售',
	'LBL_SUB_PRODUCTS' => '子產品',	
	'LBL_MARK_AS_HELD' => '標記為已進行',
	'LBL_MARK_AS_COMPLETED' => '標記為已完成',
	'LBL_SMS_MAX_CHARACTERS_ALLOWED' => '允許最多 160 個字元的文字資訊',
	'LBL_HIDE_COMPLETED_EVENTS' => '隱藏已完成的日曆事件',
	'LBL_SETUP_WEBFORMS' => '設定 Web 表單',
	'LBL_SPECIAL_OPTIONS' => '特殊選項',
	'LBL_PARENT_OWNER' => '父記錄所有者',
	'LBL_PASSWORD_LINK_EXPIRED_OR_INVALID_PASSWORD' => '密碼連結已經過期或您輸入了無效密碼',

	// Recurring Invoice
	'Half-Yearly' => '每半年',
	'LBL_FULLSCREEN' => '全畫面',
	//'LBL_SETUP_WEBFORMS' => '設定 Web 表單',
	'LBL_MODULE_DISABLED' => '模組已停用',
	'Organization Name' => '客戶名稱',
	'LBL_SOCIAL_TWITTER_WIDGET' => 'Twitter 活動',
	'LBL_WEEK' => '星期',
	//Convert Lead and Potential
	'CANNOT_CONVERT' => '不能轉換',
	'LBL_CONVERT_ERROR_TITLE' => '模組已停用',
	'LBL_FOLLOWING_ARE_POSSIBLE_REASONS' => '可能的原因包括：',
	'LBL_MANDATORY_FIELDS_ARE_EMPTY' => '必填欄位為空',

	// SMSNotifier Phone Format Warning
	'LBL_PHONE_FORMAT_WARNING' => '請確認電話號碼採 E.164 通信編碼格式',
	'LBL_PHONEFORMAT_WARNING_CONTENT' => 'E.164 編碼格式最多可有15個數字，通常寫成如下： [+][國碼][所在地區用戶號碼]
										 例如，要將美國電話號碼 (415 599 2671) 轉為 E.164 格式，需在號碼前加上\'+\' 跟國碼 (美國為1) (+1 415 599 2671)。在台灣和其他許多國家上，通常地區號碼在前面先增加一個0。但是，使用E.164 編碼格式必須刪除這個0。某台灣號碼02 2311 3731應該編碼為+886 2 2311 3731。',
	'LBL_WARNING' => '警告',
	'LBL_ORIGIN' => '來源',
	'SENT' => '發送',
	'RECEIVED' => '收到',
	'QUEUED'=> '排隊',
	'FAILED'=> '失敗',
	'SAVED' => '草稿',
	//'MailManager' => '郵件管理',
	'MAILSCANNER' => '郵件轉換',
	'LBL_SENDER_NAME' => '寄件人名稱',
	'SMSNotifier'=>'SMS發送',

	'Mobile Call' => '手機通話',
	'LBL_NO_MORE_RESULTS' => '沒有更多結果！',
	//'Related To' => '關聯於',

	// Date Conditions
	'LBL_LESS_THAN_DAYS_AGO' => '小於幾天前',
	'LBL_MORE_THAN_DAYS_AGO' => '大於幾天前',
	'LBL_IN_LESS_THAN' => '小於',
	'LBL_IN_MORE_THAN' => '大於',
	'LBL_DAYS_AGO' => '天之前',
	'LBL_DAYS_LATER' => '天之後',
	'LBL_LESS_THAN_HOURS_BEFORE' => '小於幾小時前',
	'LBL_LESS_THAN_HOURS_LATER' => '小於幾小時後',
	'LBL_MORE_THAN_HOURS_BEFORE' => '大於幾小時前',
	'LBL_MORE_THAN_HOURS_LATER' => '大於幾小時後',
	'LBL_INTERNAL_COMMENT' => '內部評論',
	'LBL_NOTE_EXISTING_ATTACHMENTS_WILL_BE_REPLACED' => '注意：將替換所有附件（圖／檔案）',

	//common standard fields
	'Created By' => '建立者',
	'LBL_SEND_PDF_FOR_SIGNING' => '傳送PDF簽名',
	'LBL_CLICK_TO_EDIT' => '點擊編輯',
	'LBL_SIGNATURE_BLOCK' => '簽名',
	'LBL_INCLUDE_SIGNATURE_INFO' => '個人偏好設定的簽名設定將加入到郵件底處',
	'LBL_INCLUDE_SIGNATURE' => '包含簽名',

	// module builder created module first block label 
	'LBL_BASIC_INFORMATION' => '基本資訊',
	'LBL_CLICK_HERE'=>'點選這裡',

	//Recipient preferences labels
	'LBL_SELCT_EMAIL_RECIPIENTS' => '選擇郵件收件人',
	'LBL_REMEMBER_MY_PREF' => '記住我的個人偏好',
	'LBL_RECIPIENT_PREFS'=>'收件人選項',
	'LBL_EMAIL_RECIPIENT_PREFS'=>'郵件收件人選項',
	'LBL_ERROR_SAVING_PREF' => '儲存偏好設定錯誤，請稍後再試！',
	'LBL_NO_PREF_GIVEN' => '沒有指定偏好設定！',
	'LBL_PLEASE_ADD_EMAIL_FIELDS' => '請添加郵件欄位並稍後再試',
	'LBL_RECIPIENT_SAVE_MESSAGE'=>'儲存成功。當您從模組發送郵件時，這些偏好設定將被設為郵件地址。',
	'LBL_PREF_RESET_MESSAGE' => '您的收件人郵件偏好設定已被重置！',

	'LBL_COMPANY_DETAILS' => '公司細節',
	'COMPANY_LOGO_HELP_TEXT' => '請上傳您喜愛的公司LOGO。<br>除了會在CRM上顯示公司LOGO外，<br>您的公司名稱與地址資訊也被使用在<br>廣告郵件 (須符合規定)<br>與報價單中。',
	'COMPANY_LOGO_HELP_TEXT_2' =>"您可稍後編輯公司細節<br>
									'CRM 設定 > 樣板 > 公司細節' 頁面",
	'LBL_CHOOSE_PREFERENCES' => '選擇您的個人偏好設定',
	'PREFERENCES_HELP_TEXT' => '基準幣別 - 選擇您的主要幣別。如果您擁有多種幣別<br> 
								所有的數據都透過CRM配置的匯率轉為基準幣別儲存。',
	'PREFERENCES_HELP_TEXT_2' => '個人偏好設定可透過團隊中的個人用戶進行獨立配置。<br>
									包含時區、語言、日期隔日、數字編碼等。<br>
									數字編碼常用於幣別與CRM的其他欄位。<br>
									您可稍後編輯您的個人偏好選項 \'用戶名稱 > 我的個人偏好設定 \'',
	'LBL_CANNOT_BE_CHANGED_LATER' => '以後無法再更改',
	'IMPORT_CONTACTS_GOOGLE_HELP_TEXT' => '我們可從Google導入聯絡人<br>您還可以啟用雙向同步來保留<br>Vtiger聯絡人跟Google聯絡人(選定群組中)同步更新<br>點擊按鈕進行授權並開始導入Google聯絡人',
	'IMPORT_CONTACTS_CSV_HELP_TEXT' => '您可以從CSV檔案匯入聯絡人。',
	'IMPORT_CONTACTS_CSV_HELP_TEXT2' => '進行匯入銷售機會、潛在客戶、客服記錄，請任一個列表顯示中查看 \'操作 > 匯入\' 按鈕',
	'LBL_DOEST_FIRST_ROW_HEADER' => '請問您的檔案中第一行是否為標題列?',
	'LBL_SELECT_CSV_FILE' => '選擇 CSV 檔案',
	'LBL_START_IMPORTING' => '開始匯入',
	'LBL_PRIMARY' => '主要',
	'LBL_GOOGLE_SYNC_INTIATED_MSG' => '您的匯入已列入排程，您的聯絡人很快便開始匯入。<br> 繼續執行下一步將不影響此匯入中斷。',
	'LBL_IMPORT_SYNC_INTIATED_MSG' => '您的匯入正在進行。完成匯入後您將收到一封郵件。<br> 繼續執行下一步將不影響此匯入中斷。',
	'LBL_TELL_US_ABOUT_YOU' => '告知我們依些關於您公司的資訊',
	'TELL_US_ABOUT_YOU_HELP_TEXT' => '我們將繼許改進CRM系統。<br>
									 更加了解我們的用戶幫助我們持續優化效能。',
	'TELL_US_ABOUT_YOU_HELP_TEXT_2' => '您在此提交的任何資料我們不會透漏給Vtiger以外的任何人。',
	'LBL_INVALID_IMAGE' => '無效圖片',
	'LBL_IMPORT_CONTACTS' => '匯入聯絡人',
	'LBL_FROM_GOOGLE' => '從 Google',
	'LBL_FROM_CSV' => '從 CSV 檔案',
	//'LBL_NEXT' => '下一步',
	'LBL_FINISH' => '完成',
	'LBL_GET_CONTACTS_FROM_GOOGLE' => '從 Google 取得聯絡人',
	'LBL_PHONE_NUMBER' => '手機號碼',
	'LBL_NUMBER_OF_EMPLOYEES' => '員工人數',
	'LBL_INDUSTRY' => '行業',
	'LBL_HELP_DESK_EMAIL_HELP_TEXT' => '客服記錄相關的通知將透過此郵件地址發送',
	'LBL_SOCIAL_DETAILS' => '連接到社交網路進行查找新客戶，並回應諮詢',
	'LBL_SOCIAL_AUTHORIZE_HELP'=>'連結到您的twitter公司帳戶作為發布資訊與加入追蹤',
	'LBL_SOCIAL_AUTHORIZE' => '連線到twitter',
	'LBL_SOCIAL_LINKED' => '您的 Vtiger 已連結到',
	'LBL_ENTER_KEYWORDS_HELP'=>'Vtiger 將偵測twitter並使用這些單字找到資訊',
	'LBL_ENTER_KEYWORDS' => '輸入關鍵字',

	 // Social Module Strings
	'LBL_TWEETS' => '推文',
	'LBL_FAVOURITES' => '收藏',
	'LBL_FOLLOWING' => '追蹤',
	'LBL_FOLLOWERS' => '關注',
	'LBL_VIEW_FULL_PROFILE' => '查看完整用戶資料',
	'LBL_LOCATION' => '位置',
	'LBL_DESCRIPTION' => '描述',
	'LBL_JOINED' => '加入',
	'LBL_SEARCH_PROFILES_IN_TWITTER' => '查找Twitter上的用戶資料',
	'LBL_CHOOSE_ANOTHER_PROFILE' => '選擇作者用戶資料',
	'LBL_ADD_TICKET' => '加入客服記錄',
	'LBL_ADD_OPPORTUNITY' => '加入銷售機會',
	'LBL_RETWEET' => '轉寄',
	'LBL_RETWEETS' => '轉寄',
	'LBL_UNDO_RETWEET' => '取消轉寄',
	'LBL_FAVOURITE' => '收藏',
	'LBL_UNDO_FAVOURITE' => '取消收藏',
	'LBL_TWITTER_HANDLER_MSG' => '要查看此聯絡人的用戶資料摘要與歷史記錄，請使用以下連結加入他們的Twitter用戶名或搜尋用戶資料。',
	'LBL_ADD_EVENT_OR_TODO' => '加入事件/任務',
	'LBL_ADD_TICKET_CONTACT' => '加入客服記錄 + 聯絡',
	'LBL_ADD_CASE_CONTACT' => '加入案例 + 聯絡人',
	'LBL_ADD_OPPORTUNITY_CONTACT' => '加入銷售機會 + 聯絡人',
	'LBL_TWITTER_HANDLER_DETAILS' => 'Twitter 用戶名細節',
	'LBL_PRIMARY_TWITTER' => 'Twitter 用戶名',
	'LBL_ADD_TWITTER_HANDLER' => '加入 Twitter 用戶名',
	'LBL_VIEW_TICKET' => '查看客服記錄',
	'LBL_VIEW_CASE' => '查看案例',
	'LBL_VIEW_OPPORTUNITY' => '查看銷售機會',
	'LBL_CLICK_TO_SELECT_PROFILE' => '點擊選擇用戶資料',
	//'LBL_INVALID_IMAGE' => '無效圖片',
	//'LBL_NEXT' => '下一步',
	//'LBL_FINISH' => '完成',
	// Module field to store Source of Record
	'Source' => '來源',

	'LBL_DEFAULT_REPLY_TO' => '預設回復郵件', 
	'outgoing_server_from_email' => '郵件寄送伺服器', 
	'hepldesk_support_email' => '客服記錄支援Email-Id', 
	'user_primary_email' => '戶主要電子郵件', 
	'LBL_DEFAULT_REPLY_TO_INFO' => '此設定僅適用於來自CRM的電子郵件。他不會影響來自工作流程的郵件廣告等郵件發送。', 
	'search_in_all_fields'=>'搜尋所有欄位',
	'search_in_name_field'=>'搜尋名稱欄位',
	'LBL_LOOKUP_SEARCH_MODE_INFO'=>'例如：在聯絡人建立表單中，當您從客戶名稱位置輸入文字時，此設定調整出被搜尋客戶的欄位',

	'VAT' => '稅金',
	'Sales' => '銷售',
	'Service' => '服務',
	'Pre Tax Total' => '稅前合計',
	'Received' => '收到',
	'Balance' => '餘額',
	'S&H Amount' => '郵資包裝附加費',
	'S&H Percent' => '郵資包裝稅率',
	'Tax Region' => '稅區',

	//Singular Modulenames
	'SINGLE_Potentials' => '銷售機會',
	'SINGLE_HelpDesk' => '客服記錄',
	//'SINGLE_Accounts' => '客戶',
	//'SINGLE_Contacts' => '聯絡人',
	'SINGLE_Project' => '產品',
	'LBL_ROLLUP_COMMENTS_INFO' => "如果總匯此設定為ON，相關的評論記錄將會顯示。
								 例如，如果您正查看客戶記錄的評論，會連帶一併顯示相關的聯絡人、銷售機會、客服記錄等相關記錄中的評論。",
	'LBL_ROLLUP_COMMENTS' => "總匯評論",

	//others
	'Engagement Score' => '參與評分',
	'group' => '合併計稅',
	'individual' => '單項計稅',
	'LBL_VIEW_FILE'=>'查看檔案',
	'LBL_DOWNLOAD_FILE' => '下載檔案',
	'LBL_PREVIEW_NOT_AVAILABLE' => '無法預覽',
	'LBL_PREVIEW_SUPPORTED_FILES' => '<b><strong>支援的檔案類型 : </strong></b><br><br><b>Pdf 檔案</b><br><b>文字檔案 - </b>txt,csv,ics<br><b>OpenDocument檔案 - </b>OpenDocument 文字(odt),OpenDocument 試算表(ods) 和 OpenDocument 簡報(odp)<br><b>媒體檔案 - </b>圖片, 聲音 & 影片等檔案<br>',
	'Mailing Address' => '郵寄地址',
	'Other Address' => '其他地址',
	'LBL_PREVIOUS' => '上一步',
	'LBL_NEXT' => '下一步',
	'Workflows' => '工作流程',
	'Primary Twitter' => 'Twitter 用戶名',

	/* Vtiger7 Language Strings */
	'LBL_CLICK_HERE_TO_SELECT_ALL_RECORDS'=>'選擇此頁面的所有記錄',
	'LBL_CLICK_HERE_TO_MANAGE_LIST_COLUMNS'=>'點擊此處管理列表列',
	'LBL_SHOW_MORE' =>'顯示更多',
	'LBL_DISPLAYING_RESULTS' => '顯示結果',
	'LBL_ADD_STAR' => '添加星記',
	'LBL_REMOVE_STAR' => '移除星記',
	'LBL_UPDATE_LIST' => '更新列表',
	'LBL_SHARE_THIS_LIST' => '分享此列表',
	'LBL_ADD_USERS_ROLES' => '新增用戶與角色',
	'LBL_LISTS' => '列表',
	'LBL_SEARCH_FOR_LIST' => '搜尋列表',
	'LBL_MY_LIST' => '我的列表',
	'LBL_SHARED_LIST' => '分享列表',
	'LBL_MERGE_SELECTED_RECORDS' => '合併所選記錄',
	'LBL_MATCH_CRITERIA' => '重複的搜尋條件',
	'LBL_MATCH_FIELDS' => '匹配的欄位',
	'LBL_EDIT_CUSTOM'=>'編輯列表',
	'LBL_SHOW_MAP'=>'顯示地圖',
	'LBL_ADD_TAB'=>'新增標籤',
	'LBL_TAB_NAME'=>'資訊主頁名稱',
	'LBL_SHARED_TAGS_ACCESS'=>'所有Vtiger用戶都可使用共享標籤',
	'LBL_GOTO_TAGS'=>'前往設定 > 個人偏好選項 > 我的標籤 進行編輯或刪除您的私人標籤',
	'LBL_UNLINK'=>'取消連接',
	'LBL_SWITCH_TO_OLD'=>'切回舊版本',
	'LBL_SLA_INFORMATION' => '服務層級協議(SLA)',

	//configure columns
	//'LBL_UPDATE_LIST' => '更新列表',
	'LBL_CONFIG_COLUMNS' => '配置列',
	'LBL_SELECTED_FIELDS' => '選取欄位',
	//'LBL_AVAILABLE_FIELDS' => '可用欄位',
	'LBL_SEARCH_FIELDS' => '搜尋欄位',

	// Extensions
	'ExtensionStore' =>'擴展應用市集',
	'LBL_EXTENSIONS' => '擴展應用',
	'LBL_SYNC_LOG' => '同步日誌',
	'LBL_SYNC_SETTINGS' => '同步設定',
	'LBL_SYNC_NOW' => '立即同步',
	'LBL_DATE' => '日期',
	'LBL_TIME' => '時間',
	'LBL_SKIPPED' => '略過',
	'vt_create' => '在Vtiger中建立記錄',
	'vt_update' => '在Vtiger中更新記錄',
	'vt_delete' => '在Vtiger中刪除記錄',
	'vt_skip' => '在Vtiger中略過記錄',
	'app_create' => '在 %s 中建立記錄',
	'app_update' => '在 %s 中更新記錄',
	'app_delete' => '在 %s 中刪除記錄',
	'app_skip' => '在 %s 中略過記錄',
	'LBL_DOWNLOAD_AS_CSV' => '下載為 CSV',
	'LBL_SOURCE_MODULE' => '來源模組',
	'LBL_RECORD_NAME' => '記錄名稱',
	'LBL_REASON' => '原因',
	'LBL_SELECT_MODULES_TO_SYNC' => '選擇要同步的模組',
	'LBL_DATA' => '數據',
	'LBL_ENABLE_SYNC' => '啟用同步',
	'LBL_FIELD_MAPPING' => '欄位映射',
	'LBL_SYNC_DIRECTION' => '同步方向',
	'LBL_SYNC_BOTH_WAYS' => '雙向同步',
	'LBL_SAVE_SETTINGS' => '儲存設定',
	'LBL_CONFIGURE' => '配置',
	'LBL_VIEW' => '查看',
	'LBL_CHANGE_USER' => '更改用戶',

	'LBL_CREATE_LIST' => '建立新列表',
	'sent' => '送出',
	'accepted' => '接受',
	//'SINGLE_Users' => '用戶',
	'LBL_RECENT_COMMENTS' => '最近評論',
	'LBL_ENGAGEMENT_HISTORY' => '參與歷史記錄',
	'LBL_NO_ENGAGEMENTS_FOUND' => '無關聯的接觸點',
	'LBL_MARKETING' => '市場行銷',
	'LBL_SALES' => '銷售',
	'LBL_PROJECT' => '專案',
	'LBL_TAGS' => '標籤',
	'LBL_SHARE_TAGS' => '公用標籤',
	'LBL_SHARE_TAG' => '分享標籤',
	'private' => '私人',
	'Tags' => '標籤',
	'public' => '公開',
	'Private/Shared' => '私人/共享',
	'LBL_TAG_FOR' => '%s 的標籤',
	'LBL_CURRENT_TAGS' => '當前標籤',
	'LBL_CREATE_NEW_TAG'=> '建立新標籤',
	'LBL_ADD_TAG' => '新增標籤',
	'LBL_REMOVE_TAG' => '移除標籤',
	'LBL_TAG_SEPARATOR_DESC' => '使用逗號分隔多個標籤',
	'LBL_ENTER_TAG_NAME'=> '輸入標籤名稱',

	'LBL_SELECT_COLOR' => '選擇顏色',
	'LBL_NO_TAG_EXISTS' => '標籤不存在',
	'LBL_ADD_NEW_TAG' => '新增標籤',
	'LBL_SELECT_EXISTING_TAG' => '選擇一個已存在的標籤',
	//'LBL_CREATE_NEW_TAG' => '建立新標籤',
	'LBL_ADD_OR_SELECT_TAG' => '新增/選擇 標籤',
	'LBL_SELECT_FROM_AVAIL_TAG' => '從可用標籤中選擇',
	'LBL_MARKET_PLACE' => '市集',

	//'LBL_SHARE_THIS_LIST' => '分享此列表',
	//'LBL_ADD_USERS_ROLES' => '新增用戶與角色',
	'EmailTemplates' => '電子郵件範本',
	'LBL_BILLING' => '帳單地址',
	'LBL_ENABLED' => '啟用',

	//Title added for buttons
	'LBL_CREATE_FILTER' => '建立篩選',
	'LBL_IS' => 'is',
	'LBL_CREATION' => '建立',
	'LBL_UPLOAD' => '上傳',
	'LBL_ATTACH_FILES' => '附加檔案',
	'LBL_KEY_FIELDS' => "重點",
	'LBL_ADD_TODO' => '新增任務',

	"LBL_VIEW_DETAILS" => "查看細節",

	//Engagements History
	"LBL_HAPPENED_ON" => "發生於",
	"LBL_HAPPENED" => '已發生',
	"LBL_TYPE" => "類型",
	"LBL_STATUS" => "狀態",
	"LBL_CUSTOMER" => "關聯於",
	//"LBL_SUMMARY" => "摘要",
	"LBL_ENGAGEMENTS" => "接觸點",

	'LBL_PLEASE_SELECT_ATLEAST_ONE_OPTION' => '請至少選擇一組選項',
	//'LBL_STARRED' => '取消追蹤',
	'LBL_UNSTARRED' => '追蹤',
	'LBL_EDIT_EMAIL_PREFERENCE_TOOLTIP' => '從模組細節或列表顯示的下拉選單設定中編輯這些偏好選項',
	'LBL_SYSTEM' =>'系統',
	//'LBL_SHOW_MAP' => '顯示地圖',
	'LBL_GOOGLE_MAP' => 'Google Map',
	//'LBL_CREATION' => '建立',
	//'LBL_ADD_TODO' => '新增任務',

	'LBL_KEY_METRICS' => '關鍵指標',

	//Print template strings
	'LBL_TEMPLATE_NAME' => '樣板名稱',
	'LBL_MODULE' => '模組',
	'LBL_IS_DEFAULT' => '預設樣板',
	'LBL_SELECT_RECORD_FIELD' => '選擇記錄欄位',
	'LBL_PREVIEW' => '預覽',
	'LBL_UNLINKED' => '未連結',

	'LBL_FOLLOW' => '追蹤',
	'LBL_UNFOLLOW' => '取消追蹤',
	'Any' => '任何',
	'LBL_NA' => '-NA-',
	'LBL_DISABLED' => '停用',

	//help
	'LBL_HELP_ANSWERS' => '答案',
	'LBL_HELP_ARTICLES' => '文章',
	'LBL_HELP_TOUR' => '導覽',
	'LBL_NO_HELP_ARTICLE_FOUND' => '抱歉，沒找到文章',
	'LBL_HELP_SEARCH' => '搜尋幫助',
	'LBL_HELP_BROWSE_ALL' => '遊覽全部',

	'LBL_EXPORT_FILE_NAME' => '匯出檔案名稱',
	'LBL_EXTENSION_NOT_ALLOWED_FOR_NONADMIN' => '%s 同步只允許系統管理員',
	'SINGLE_Invoice' => '出貨單',
	'SINGLE_SalesOrder' => '銷售訂單',
	'SINGLE_PurchaseOrder' => '採購訂單',
	'SINGLE_Quotes' => '報價單',
	'LBL_POST_YOUR_COMMENT_HERE' => '發表您的評論',
	// Phone Calls
	'LBL_CLICK_TO_CALL' => '點擊通話',
	'LBL_SHOW_TOTAL_NUMBER_OF_RECORDS' => '點擊此列表大小',

	'LBL_GENERAL_FIELDS' => '基本欄位',
	'LBL_ROLL_UP' => '收起',

	'LBL_TOUCH_POINTS' => '接觸點',
	//'LBL_HISTORY' => '接觸點',
	//'LBL_ENGAGEMENT_HISTORY' => '接觸歷史記錄',
	//'LBL_SETTINGS' => '設定',

	//List View and thumbnail view button labels
	'LBL_LIST_VIEW'=>'列表顯示',
	'LBL_THUMBNAIL_VIEW'=>'縮圖顯示',
	'LBL_CHART_VIEW'=>'圖表顯示',
	'LBL_EMAIL_SUPPORT' => '郵件支援',
	'LBL_NO_ENTITIES_FOUND' => '未找到 %s',

	'LBL_TRANSFER_ALL_CASES_TO' => '傳送所有案例到',
	'LBL_SLA_TO_BE_DELETED' => '要刪除的服務層級協議(SLA)',
	'LBL_TO_USE_SWITCH_TO_NEW_LOOK' => '要使用 <b>%s</b>，我們建議您切換到新介面',
	'LBL_INTERNAL_COMMENT_INFO' => '如果啟用了內部評論的勾選框，此評論只有CRM用戶可見。若要通報客戶(藉由可編輯的工作排程或客戶入口網) 請取消此勾選框',
	'LBL_CHANGE' => '更改',
	'LBL_REVOKE_ACCESS' => '取消訪問',
	'GOOGLE_REVOKE_ACCESS_MESSAGE' => '點擊操作將刪除來自現有Google驗證的聯絡人與日曆，這不會刪除已同步的記錄。',
	'OFFICE_REVOKE_ACCESS_MESSAGE' => '點擊操作將刪除來自現有Office365驗證的聯絡人、日曆跟電子郵件，這不會刪除已同步的記錄。',
	'LBL_EMAIL_DOMAIN_HELPTEXT' => '郵件網域名稱應該與從電子郵件所創立的案例或聯絡人一致。譬如，新的支援郵件為john@apple.com，那麼它將歸類具有apple.com網域的客戶。多重網域應用逗號分隔',
	'LBL_START_GUIDED_TOUR' => '開始導覽',
	'LBL_MENU' => '選單',
	//'LBL_EMAIL_DOMAIN_HELPTEXT'=>'郵件網域名稱應該與從電子郵件所創立的案例或聯絡人一致。譬如，新的支援郵件為john@apple.com，那麼它將歸類具有apple.com網域的客戶。多重網域應用逗號分隔',

	'LBL_SHARED_LIST_NON_ADMIN_MESSAGE' => '這裡為共享列表。請聯絡您的CRM管理員配置所有列表的行項',
	'LBL_SHARED_LIST_OWNER_MESSAGE' => '這裡為共享列表。請聯絡 %s 配置所有列表的行項',

	'Mr.' => '先生',
	'Ms.' => '小姐',
	'Mrs.' => '女士',
	'Dr.' => 'Dr.',
	'Prof.' => '教授',
	'SINGLE_Cases'=>'案例',
	'LBL_TAX_MODE_INFO' =>'如果單項計稅，稅金將從個別產品記錄中所算。 如果合併計稅, 稅金將從全域設定中所算',
	'LBL_CURRENCY_INFO' =>'根據配置的匯率，值將改為所選的幣別。',
	'LBL_TAX_REGION_INFO' =>'根據變動稅，稅率將根據所選稅區調整。',
	'LBL_TAX_CONFIGURE' =>'設定稅區',
	'LBL_SEND_MSG_TO_SUPPORT' => '傳送郵件到支援',
	'LBL_CHAT_WITH_SUPPORT' => '與CRM專家線上交談',

	'LBL_ROLES' => '角色',
	'LBL_ROLEANDSUBORDINATE' => '角色與附屬',
	'LBL_YOUR_LEARNING_SCORE' => '您的CRM學習表現',
	'LBL_SWITCH_TO_VTIGER7_NOW' => '在2/15日之前切換到Vtiger 7',
	'LBL_VTIGER6_RETIREMENT_NOTICE' => '此版本將在2016/02/15日停用',
	'ModTracker' => '更新',
	'LBL_MAIL_SENT_SUCCESSFULLY' => '郵件傳送成功',
	'LBL_FAILED_TO_SEND' => '傳送失敗',

	'LBL_ESSENTIALS' => '要點',
	'LBL_ALL_SETTINGS' => '所有設定',
	'On' => 'On',
	'LBL_OPEN_IN_NEW_TAB' => '在新標籤中打開',
	'LBL_DELETE_FOREVER'=>'永久刪除',
	'LBL_PLEASE_CLICK_ON_EDIT_TO_ADD_NOTE' =>'請點擊編輯添加備註',
	'LBL_PLEASE_ENTER_YOUR_NOTE' => '請輸入備註於此..',
	'LBL_PORTAL' => '入口網',
	'LBL_SESSION' =>'會議',
	'LBL_SESSIONS' => '會議',
	'week days later' => '週之後',
	'more than week days later' => '大於週之後',
	'less than week days later' => '小於週之後',
	'week days ago' => '週以前',
	'more than week days ago' => '大於週之前',
	'less than week days ago' => '小於週之前',

	'LBL_DUPLICATES' => '重複',
	'LBL_DUPLICATES_DETECTED' => '偵測到重複！',
	'LBL_DUPLICATES_FOUND_MESSAGE' => ' %s 無法儲存，因為系統已存在重複的 %s 且數據與 %s 匹配。',
	'LBL_VTIGER_NOTIFICATION' => '消息來自 : Vtiger 系統通知',
	'LBL_DUPLICATION_FAILURE_FROM_WORKFLOWS' => '無法從 "%s" 工作流程中儲存以下 %s , 因為另一個 %s 已存在相同數據。',
	'LBL_DUPLICATION_FAILURE_FROM_WEBFORMS' => '無法從 "%s" web表單中儲存以下 %s , 因為另一個 %s 已存在相同數據。',
	'LBL_DUPLICATION_FAILURE_FOR_ADMIN' => '可以使用 %s 修改重複性規則。',
	'LBL_DUPLICATION_FAILURE_FOR_NON_ADMIN' => '聯絡您的系統管理員修改重複性規則',
	'LBL_DUPLICATE_RECORD_LISTS' =>'重複 %s :',
	'LBL_COLUMNS_ADDED'=>'%s 的列項已增加',
	'LBL_SHOW_ALL'=>'顯示全部',
	'LBL_LanguageEditor_WEBTITLE' => '標籤編輯器',
	'LBL_TAX_CALCULATIONS_WEBTITLE' => '稅務管理',
	'LBL_Tags_WEBTITLE' => '我的標籤',
	'LBL_HIDE' => '隱藏',
	'LBL_PRINT' => '列印',
	'LBL_FORWARD' => '向前',
	'LBL_NO_DEDUCTED_TAX'=>'沒有扣除稅金',
	'LBL_CLICK_TO_CONFIGURE'=>'點擊這裡配置',
	'LBL_KANBAN_VIEW_INFO' => '看板視圖僅顯示符合此列表條件的銷售機會',
	'LBL_CUSTOM_FIELDS_MAX_LIMIT' => '您最多只能添加 %s 自訂欄位',
	'LBL_EXCEEDED_MODULE_RECORD_LIMIT' => '已超過 %s 個記錄限制',
	'LBL_EXCEEDED_MODULE_RECORD_LIMIT_TEXT' =>'我們發現您在 %s 中有超過 %s 條記錄。 <br>超過此版本的上限。<br>請刪除多於記錄後重試',
	'LBL_TEMPLATE_INFO_PART1'=>'要查看其他模組的樣板，請在模組名稱搜尋框輸入模組名稱或"全部"。', 
	'LBL_TEMPLATE_INFO_PART2'=>'如果TO欄位的收件人與樣板來自不同模組，那麼將不會對這些收件人進行追蹤，同時合併欄位不會進行合併。',
	'LBL_HIDDEN_BECAUSE_OF_DEPENDENCY' => '欄位根據依賴規則而隱藏',
	'MAILCHIMP_REVOKE_ACCESS_MESSAGE' => '點擊此處將刪除現有MailChimp 身分驗證。它不會刪除任何已同步的記錄',
	// Added for Event Forms
	'LBL_VIEW_ANSWERS' => '查看答案',
	'LBL_ANSWERS' => '答案',

	//Default sort order translations
	'LBL_DEFAULT_SORT_ORDER' => '默認排序列與排序順序',
	'LBL_SELECT_COLUMN' => '選擇列',
	'LBL_SELECT_SORT_ORDER' => '選擇排序順序',
	'LBL_ASCENDING' => '升序',
	'LBL_DESCENDING' => '降序',
	'LBL_DEFAULT_SORT_MESSAGE' => '默認下對每個新用戶會議，列表永遠在此列上排序',
	'LBL_QUEUED' => '排序',
	// End
	//Added for Inbox
	'LBL_EMAILS'=>'郵件',
	'LBL_CONVERSATIONS'=>'對話',
	'LBL_FROM_DISABLED_MESSAGE'=>'在寄件伺服器配置頁面中選擇郵件伺服器不允許更改寄件人地址。',
	// End
	'LBL_MODULE_MANDATORY' => '模組為必要',
	'Online' => '線上',
	'Busy' => '忙碌',
	'LBL_BETA'=>'BETA',
	'JS_SHARED_WITH'=>'分享於',
	 'LBL_REPLY_TO' =>'回覆',
	'LBL_MODULE_ASSIGNMENT_RULES' => '%s 分配規則',

	'LBL_RECENT_UPDATES' => '最近更新',
	'LBL_VIEW_UPDATES_IN_DETAIL' => '了解更多 ...',
	'LBL_DEFAULT_DASHBOARD_TOOLTIP'=>'重新排序為第一個標籤作為此資訊主頁的默認設置！',
	
	
	//Optimized by Loki in 7.1.0
	'starred' => '追蹤',
	'Relation' => '關聯模組',
	'Tasks' => '任務',
);

$jsLanguageStrings = array(
	'JS_EMAIL_SERVER_CONFIGURATION' => '請在此頁配置您的寄件伺服器',
	'JS_SMS_SERVER_CONFIGURATION' => '請在SMS發送頁面配置您的SMS發送',
	'JS_PLEASE_SELECT_ONE_RECORD' => '請選擇至少一個記錄',
	//dropdown categary
	'JS_USERS' => '用戶',
	'JS_GROUPS' => '群組',
	'JS_ALL' => '全部',
	//Validation Error Message
	'JS_PLEASE_ENTER_VALID_VALUE' => '請輸入有效值',
	'JS_PLEASE_ENTER_VALID_TAG_NAME' => '有輸入有效標籤名稱',
	'JS_TAG_SAVED_SUCCESSFULLY' => '標籤儲存成功',
	'JS_PLEASE_ENTER_VALID_EMAIL_ADDRESS' => '請輸入有效郵件地址',
	'JS_CONTAINS_ILLEGAL_CHARACTERS' => '含有非法字元',
	'JS_PHONE_NUMBER_LENGTH_EXCEEDED' => '電話號碼超過上限',
	'JS_ACCEPT_POSITIVE_NUMBER' => '只接受正數',
	'JS_ACCEPT_WHOLE_NUMBERS' => '只接受整數',
	'JS_VALUE_SHOULD_BE_GREATER_THAN_ZERO' => '值應大於零',
	'JS_NUMBER_SHOULD_BE_LESS_THAN_32' => '數字應小於32',
	'JS_PLEASE_ENTER_VALID_DATE' => '請輸入有效日期',
	'JS_PLEASE_ENTER_VALID_TIME' => '請輸入有效期時間',
	'JS_INVALID_PAGE_NUMBER' => '頁碼無效',
	'JS_SUBJECT_VALUE_CANT_BE_EMPTY' => '主題不能為空',
	'JS_PERCENTAGE_SHOULD_BE_LESS_THAN_100' => '百分比應小於100',


	'INVALID_NUMBER_OF' => '數字無效',
	'INVALID_NUMBER' => '數字無效',
	'JS_LBL_ARE_YOU_SURE_YOU_WANT_TO_DELETE' => '您確定要刪除嗎？',

	'OVERWRITE_EXISTING_MSG1' => '需要用指定的地址資訊 ',
	'OVERWRITE_EXISTING_MSG2' => '覆蓋現有地址嗎？',
	'SINGLE_Accounts' => '客戶',
	'SINGLE_Contacts' => '聯絡人',
	'SINGLE_Project' => '產品',
	'SINGLE_ProjectMilestone' => '專案里程碑',

	'LBL_DELETE_CONFIRMATION' => '您確定要刪除嗎？', // This is added as duplicate as we need to show different message for different modules. Ex:Accounts has different message
	'LBL_UNLINK_CONFIRMATION' => '您確定要取消連結嗎？',
	'LBL_DELETE_USER_CONFIRMATION' => '當用戶被刪除時將標示為"未激活"，且新的記錄不再分配給該用戶，用戶將無法登入。您確定要刪除嗎？',
	'LBL_DELETE_CONFIRMATION_NOTE' => '注意 : 刪除的記錄將保存在垃圾桶中並於 %s 後清除',
	'LBL_MASS_DELETE_CONFIRMATION' => '您確定要刪除所選記錄嗎？',
	'JS_LBL_SAVE' => '儲存',
	'JS_LBL_CANCEL' => '取消',
	'JS_DUPLICTAE_CREATION_CONFIRMATION' => '客戶名稱已存在，您還要建立重複的記錄嗎？',

	'SHOULD_BE_LESS_THAN_TODAY' => '必須發生在今天之前',
	'JS_PLEASE_SELECT_ATLEAST_ONE_OPTION' => '請選擇至少一個選項',
	'JS_SELECT_MODULE' => '請選擇模組',
	'JS_PLEASE_SELECT_ATLEAST_ONE_MANDATORY_FIELD' => '請選擇至少一個必填欄位',
	//'JS_SELECT_MODULE' => '請選擇一個模組',
	'JS_PLEASE_ENTER_INTEGER_VALUE' => '請輸入整數',
	'JS_PLEASE_ENTER_DECIMAL_VALUE' => '請輸入十進位的值',
	'JS_PLEASE_ENTER_POSITIVE_DECIMAL_VALUE' => '請輸入正十進位的值',

	'JS_START_TIME_SHOULD_BE_GREATER_THAN_CURRENT_TIME' => '開始時間應該晚於當前時間',
	'JS_SHOULD_BE_LESS_THAN_CURRENT_DATE' => '應早於當前日期',
	'JS_SHOULD_BE_GREATER_THAN_CURRENT_DATE' => '應晚於當前日期',
	'JS_SHOULD_BE_GREATER_THAN_OR_EQUAL_TO' => '應大於或等於',
	'JS_SHOULD_BE_LESS_THAN_OR_EQUAL_TO' => '應小於或等於',
	//'JS_SHOULD_BE_GREATER_THAN_OR_EQUAL_TO' => '應大於或等於',
	'JS_CURRENT_DATE' => '當前日期',
	'JS_PERCENTAGE_VALUE_SHOULD_BE_LESS_THAN_100' => '百分比的值應小於100',
	'JS_ACCEPT_ONLY_NUMBER' => '只接受數字',
	'JS_THIS_FILE_HAS_ALREADY_BEEN_SELECTED' => '該檔案已被選取',
	'JS_MAX_FILE_UPLOAD_EXCEEDS' => '超過檔案上傳限制',
	'JS_THIS_DOCUMENT_HAS_ALREADY_BEEN_SELECTED' => '此文件已附加',
	'JS_LIST_EXIST' => '列表已存在',


	//Roles
	'JS_FAILED_TO_SAVE' => '修改儲存到伺服器失敗',

	//Import Translations
	'JS_IMPORT_FILE_CAN_NOT_BE_EMPTY' => '匯入檔案不能為空',
	'JS_PLEASE_SELECT_ONE_FIELD_FOR_MERGE' => '請選擇至少一個符合欄位',
	'JS_MAP_NAME_CAN_NOT_BE_EMPTY' => '映射名稱不能為空',
	'JS_MAP_NAME_ALREADY_EXISTS' => '映射名稱已存在',
	'JS_SELECT_FILE_EXTENSION' => '請選擇以下擴展的檔案：',
	'JS_UPLOADED_FILE_SIZE_SHOULD_BE_LESS_THAN' => '上傳檔案容量應小於',
	'JS_UPLOADED_FILE_SIZE_EXCEEDS' => '上傳檔案容量超過',
	'JS_PLEASE_SPLIT_FILE_AND_IMPORT_AGAIN' => '請將檔案進行分割為較小檔案再行上傳。',
	'JS_FIELD_MAPPED_MORE_THAN_ONCE' => '欄位映射超過一次',
	'JS_MAP_MANDATORY_FIELDS' => '請映射必填欄位',
	'JS_MAP_MERGE_CRITERIA_FIELDS' => 'P請映射對應欄位',
	'JS_PLEASE_ENTER_SOME_VALUE' => '請輸入一些數據進行搜尋',
	'JS_VCF_FILE_IMPORT_WARNING' => '您已選擇 VCF 檔案。只能從VCF檔案中匯入聯絡人。要匯入此檔案，請從聯絡人模組中啟用匯入',
	'JS_ICS_FILE_IMPORT_WARNING' => '您已選擇 ICS 檔案。只能從VCF檔案中匯入聯絡人。要匯入此檔案，請從聯絡人模組中啟用匯入',
	//Select2 elements validation message
	'JS_YOU_CAN_SELECT_ONLY'=> '您只能選擇',
	'JS_ITEMS' => '項目',

	'JS_LBL_PERMISSION' => '權限',
	'JS_CHECK_FILE_INTEGRITY' => '檢查檔案完整性',
	'JS_DUPLICATE_RECORD' => '重複記錄',

	//advance filter checkbox type condition values
	'JS_IS_ENABLED' => '已啟用',
	'JS_IS_DISABLED' => '已停用',

	'JS_PLEASE_ENTER_SOME_TEXT_FOR_COMMENT' => '請輸入一些文字進行評論',
	'JS_LBL_COMMENT_VALUE_CANT_BE_EMPTY' => '評論不能為空',
	'JS_REQUIRED_FIELD' => '此欄位為必填',
	'JS_CAN_NOT_REMOVE_DEFAULT_WIDGET' => '不能刪除預設的小工具',
	//'JS_SHOULD_BE_LESS_THAN_CURRENT_DATE' => '應早於當前日期',
	'JS_NO_CREATE_OR_NOT_QUICK_CREATE_ENABLED' => '無建立權限或沒有啟用快速建立',

	//Image Action
	'LBL_IMAGE_DELETED_SUCCESSFULLY' => '圖片刪除成功',
	'LBL_IMAGE_NOT_DELETED' => '圖片未刪除',
	'LBL_YES' => '是',
	'LBL_NO' => '無',
	'AM' => '上午',
	'PM' => '下午',
	'JS_ERROR' => '錯誤',
	'JS_INFORMATION' => '資訊',
	'JS_DO_NOT_HAVE_AN_EMAIL_ID' => '沒有郵件地址',
	'NONE_OF_THE_FIELD_VALUES_ARE_CHANGED_IN_MASS_EDIT' => '批量編輯中沒有任何欄位被修改',

	//Notification messages for inventory module
	'JS_PLEASE_SELECT_AN_ACCOUNT_TO_COPY_ADDRESS' => '請選一個客戶複製地址',
	'JS_PLEASE_SELECT_AN_CONTACT_TO_COPY_ADDRESS' => '請選擇一個聯絡人複製地址',
	'JS_SELECTED_ACCOUNT_DOES_NOT_HAVE_AN_ADDRESS' => '選定的公司沒有可複製的地址',
	'JS_SELECTED_CONTACT_DOES_NOT_HAVE_AN_ADDRESS' => '選定的聯絡人沒有可複製的地址',
	'JS_PLEASE_ENTER_PRIMARY_EMAIL_VALUE_TO_ENABLE_PORTAL_USER' => '請輸入主電子郵件地址以啟用​​入口網帳戶',
	'JS_PRIMARY_EMAIL_FIELD_DOES_NOT_EXISTS' => '常用Email 欄位未填寫而無法啟用入口網帳戶',

	//Tag Cloud validation messages
	'JS_PLEASE_ENTER_A_TAG' => '請輸入一個標籤',
	'JS_TAG_NAME_ALREADY_EXIST' => '標籤名稱已存在',
	'JS_MAX_TAG_LENGTH_EXCEEDS' => '標籤長度超過上限',

	'JS_NO_VIEW_PERMISSION_AFTER_SAVE'=> '儲存後你將沒有權限查看此記錄。你想繼續嗎？',
	'JS_NO_RECORDS_RELATED_TO_THIS_FILTER' => '此篩選器沒有相關記錄',

	// Calendar Reminder popup
	'JS_START_DATE_TIME' => '開始日期和時間',
	'JS_END_DATE_TIME' => '結束日期及時間',	
	'JS_POSTPONE' => '推遲',
	'JS_MESSAGE' => '資訊',

	//'JS_NO_VIEW_PERMISSION_AFTER_SAVE'=> '儲存後你將沒有權限查看此記錄。你想繼續嗎？',

	//Settings page translations
	'JS_SUCCESSFULLY_PINNED' => '快捷方式新增成功',
	'JS_SUCCESSFULLY_UNPINNED' => '快捷方式刪除成功',
	'JS_SHORTCUT_ALREADY_ADDED' => '此快捷方式已新增',
	//'JS_MESSAGE' => '資訊',
	'JS_MASS_EDIT_LIMIT' => '批次編輯一次只能操作 500 條或者更少的條目',

	//Module Manager
	'JS_MODULE_ENABLED' => '啟用模組',
	'JS_MODULE_DISABLED' => '停用模組',

	//Crom tasks
	'JS_VALUE_SHOULD_NOT_BE_LESS_THAN' => '例行性任務的頻率應不小於',
	'JS_MINUTES' => '分鐘',

	//PickList
	'JS_ITEM_RENAMED_SUCCESSFULLY' => '選單項更名成功',
	'JS_ITEM_ADDED_SUCCESSFULLY' => '選單項新增成功',
	'JS_NO_ITEM_SELECTED' => '未選擇選單項',
	'JS_MORE_THAN_ONE_ITEM_SELECTED' => '選擇了多個選單項',
	'JS_ITEMS_DELETED_SUCCESSFULLY' => '選單項刪除成功',
	'JS_DUPLICATE_ENTRIES_FOUND_FOR_THE_VALUE' => '找到重複的項',
	'JS_SELECT_RECORDS_TO_MERGE_FROM_SAME_GROUP' => '你必須選擇同組中的記錄進行合併',
	'JS_SELECT_ATLEAST_TWO_RECORD_FOR_MERGING' => '至少選擇兩個記錄合併',
	'JS_ALLOWED_TO_SELECT_MAX_OF_THREE_RECORDS' => '你可以選擇最多三個記錄',	
	//Notification message for dashboard widget delete
	'JS_ARE_YOU_SURE_TO_DELETE_WIDGET' => '您確定要刪除小工具 - %s ？',
	'JS_ARE_YOU_SURE_TO_DELETE_DASHBOARDTAB' => '您確定要刪除資訊主頁標籤 - %s?',
	'JS_TABS_LIMIT_EXCEEDED' => '抱歉!無法添加10以上的標籤',
	//'JS_DUPLICATE_ENTRIES_FOUND_FOR_THE_VALUE' => '找到重複的項',
	//'JS_SELECT_RECORDS_TO_MERGE_FROM_SAME_GROUP' => '你必須選擇同組中的記錄進行合併',
	//'JS_SELECT_ATLEAST_TWO_RECORD_FOR_MERGING' => '至少選擇兩個記錄合併',
	//'JS_ALLOWED_TO_SELECT_MAX_OF_THREE_RECORDS' => '你可以選擇最多三個記錄',	
	'JS_TOTAL_RECORDS' => '記錄合計',
	'JS_PAGE_NOT_EXIST' => '頁面不存在',
	'JS_YOU_ARE_IN_PAGE_NUMBER' => '您現在的頁碼',

	//More currencies message
	'JS_PLEASE_ENABLE_BASE_CURRENCY_FOR_PRODUCT' => '請啟用產品的基準幣別',
	'JS_PLEASE_SELECT_BASE_CURRENCY_FOR_PRODUCT' => '請選擇產品的基準幣別',	
	'JS_BASE_CURRENCY_CHANGED_TO_DISABLE_CURRENCY' => '基準幣別必須改為停用 ',

	//Delete Records message
	'JS_RECORDS_ARE_GETTING_DELETED' => '記錄將被刪除',
	'JS_RECORD_GETTING_DELETED' => '記錄已被刪除',
	'JS_NO_RESULTS_FOUND' => '未找到結果',

	'JS_RECORDS_TRANSFERRED SUCCESSFULLY' => '記錄的所有權已經成功轉移',

	//TextSearch Language String
	'LBL_SEARCHING' => '搜尋 ',
	'JS_RECORDS_TRANSFERRED_SUCCESSFULLY' => '記錄的所有權成功轉移。',
	'JS_USER_DELETED_SUCCESSFULLY' => '用戶刪除成功。',

	'JS_MAX_RECORDS_LIMIT' => '列印最大記錄是 :',
	'JS_USER_EXISTS' => '用戶已存在',
	'JS_REENTER_PASSWORDS' => '重新輸入密碼',
	'LBL_SIGN_IN_AS_USER'=>'請用另一個用戶身分登入將停止當前繪畫。您確定繼續嗎？',
	//'JS_REENTER_PASSWORDS' => '重新輸入密碼',
	'SINGLE_Vendors' => '供應商',

	//Feedback on removing old version
	'JS_PLEASE_GIVE_YOUR_FEEDBACK' => '請填寫您的回應',
	'JS_PBX_CALL_FROM' => '通話來自',
	'JS_PBX_INCOMING_CALL' => '來電',
	'JS_PBX_OUTGOING_SUCCESS'=>'拿起分機撥打號碼',
	'JS_PBX_OUTGOING_FAILURE'=>'通話失敗',
	'JS_PBX_FILL_ALL_FIELDS'=>'請填寫全部欄位',
	'JS_PBX_CAMPAIGN_NAME' => '行銷活動名稱',
	'JS_PBX_CAMPAIGN_NUMBER' => '行銷活動編號',
	'JS_MIN_SEARCH_KEY_LENGTH' => '關鍵字搜尋至少要三個字元',
	'JS_NO_MATCH' => '找不到符合記錄',
	'JS_PBX_OUTGOING_CALL' => '撥打通話',
	'JS_PBX_CALL_TO' => '撥話至',
	'JS_REQUIRED' => '需要',
	'JS_PHONE_NUMBER' => '電話號碼',
	'JS_NO_CREATE_PERMISSION' => '通話需要在建立記錄之前回應',
	'HelpDesk' => '客服記錄',
	'Potentials' => '銷售機會',
	'JS_CALL_NOT_ANSWERED_UPDATE_PERMISSION' => "通話需要在關聯記錄之前回應", 
	'JS_CALL_NOT_ANSWERED' => "通話需要在執行操作之前回應",
	// ends
	'JS_NO_EDIT_PERMISSION' => '您沒有編輯此事件的權限',

	//Google Synchronization
	'SYNC_REMOVED_SUCCESSFULLY' => 'Google 同步移除成功',
	'REMOVE_SYNCHRONIZATION_MESSAGE' => '點擊此按鈕將刪除現有的Gmail驗證。但它不會刪除已同步的記錄。',
	'REMOVE_SYNCHRONIZATION' => '移除同步',
	'FIELD_MAPPING' => '欄位映射',
	'LBL_SYNC_BUTTON' => '立即同步',
	'LBL_SYNCRONIZING' => '同步中....',
	'LBL_NOT_SYNCRONIZED' => '您尚未同步',
	'LBL_FIELD_MAPPING' => '欄位映射',

	'LBL_RESTORE_CONFIRMATION' => '以前分配給此用戶的記錄將不會被還原。您確定要還原此用戶嗎？',
	'LBL_DELETE_USER_PERMANENT_CONFIRMATION' => '一但刪除此用戶將無法復原。您確定要永久刪除此用戶嗎？',

	'LBL_LANGUAGE_LABEL_VALIDATION' => '標籤值不能為空，您必須輸入一些值。',
	'JS_CHANGES_WILL_BE_LOST' => '您的修改將會丟失！',
	'JS_RECORD_DELETED' => '記錄已刪除',
	'JS_NO_DELETE_PERMISSION' => '沒有刪除權限',
	'JS_CONFIRM_MARK_AS_HELD' => '您確定要將事件標記為已進行嗎？',
	'JS_CONFIRM_MARK_AS_COMPLETED' => '您確定要將任務標記為已完成嗎？',
	'JS_TODO_MARKED_AS_COMPLETED' => '任務標記為已完成',
	'JS_EVENT_MARKED_AS_HELD' => '事件標記為已進行',
	'JS_FUTURE_EVENT_CANNOT_BE_MARKED_AS_HELD' => '未來事件無法標記為已進行',
	'JS_PERMISSION_DENIED' => '權限拒絕',
	'LBL_SMS_MAX_CHARACTERS_ALLOWED' => '允許最多160個字元的文字區域',
	'JS_VIEWNAME_ALERT' => '列表名稱最多允許40個字元',
	'JS_EXCEEDS_MAX_UPLOAD_SIZE' => '上傳大小超過上限',
	'JS_FUTURE_EVENT_CANNOT_BE_HELD' => '將來的事件不能為已完成',
	'LBL_WARNING' => '僅告',
	'DELETE_USER_PERMANENT_WARNING' => '永久刪除用戶會將所有記錄(包含評論與歷史記錄)轉移給新用戶。',
	'JS_CLOSE' => '關閉',
	'JS_DECIMAL_SEPARATOR_AND_GROUPING_SEPARATOR_CANT_BE_SAME' => '小數點分隔符號跟分組分隔符號不能相同',
	//'JS_FUTURE_EVENT_CANNOT_BE_HELD' => '將來的事件不能為已完成',
	//'JS_CLOSE' => '關閉',

	// For Line Iteam Currency Symbol select while Import
	'JS_CURRENCY_TOOLTIP_CONTENT_TITLE' => '行項目幣別',
	'JS_CURRENCY_TOOLTIP_CONTENT_MESSAGE' => '再行項目幣別中匯入貨幣值，Vtiger將使用此設置來辨識幣別。行項目表外的任何貨幣值都假定為用戶的主要幣別(在 \'我的個人偏好選項\'修改)',
	'LBL_CANT_SELECT_CONTACT_FROM_LEADS' => '不能對潛在客戶選擇相關聯絡人',
	'JS_TRY_LATER' => '請稍後再試！',
	'JS_FILE_NAME' => '檔案名稱',
	'JS_EXTERNAL_FILE_URL' => '檔案位置',
	'JS_PLEASE_SELECT_A_FILE' => '請選擇檔案',
	// SMSNotifier Phone Format Warning
	'JS_PHONEFORMAT_ERROR' => '請檢察電話號碼為國際 E.164 格式需前述 \'+\' 國碼，例如 +886 2 2311 3731',

	// Leads and Potentials Field Mapping
	'JS_NONE' => '無',
	'JS_IS_ALREADY_BEEN_MAPPED' => '已經映射',
	'JS_CANT_MAP' => '不能映射',
	'JS_WITH' => 'with',
	'JS_MAPPING_DELETED_SUCCESSFULLY' => '映射刪除成功',

	//JS Field Type Translation
	'JS_phone' => '電話',
	'JS_picklist' => '下拉列表',
	'JS_email' => 'Email',
	'JS_text' => '文字',
	'JS_currency' => '幣別',
	'JS_multiSelectCombo' => '多選組合框',
	'JS_time' => '時間',
	'JS_textArea' => '文字區域',
	'JS_url' => '網址',
	'JS_string' => '字串',
	'JS_checkBox' => '勾選方塊',
	'JS_date' => '日期',
	'JS_decimal' => '十進位數字',
	'JS_percent' => '百分比',
	'JS_skype' => 'Skype',
	//'JS_None' => '無',
	'JS_integer' => '整數',
	'JS_double' => '高精度浮點數',
	'JS_reference' => '引用',
	'JS_image' => '圖片',

	// AutoFill Overwriting message
	'JS_OVERWRITE_AUTOFILL_MSG1' => '您確定要對所選的',
	'JS_OVERWRITE_AUTOFILL_MSG2' => '進行覆蓋數據？',

	//Demo Data Module Translatios
	'JS_ADD_DEMO_DATA_CONFIRMATION'=> '您確定要將範例記錄添加到所有模組嗎？',
	'JS_ADD_DEMO_DATA_INFO'=> '透過點擊"清除範例資料"按鈕進行刪除範例記錄。',
	'JS_CLEAR_DEMO_DATA_CONFIRMATION'=> '您確定要清除所有模組裡的範例記錄嗎？',
	'JS_CLEAR_DEMO_DATA_INFO'=> '透過點擊"增加範例資料"按鈕進行添加範例記錄。',
	'JS_DEMO_DATA_GETTING_POPULATED'=> '範例資料已開始加入，請稍後...',
	'JS_DEMO_DATA_GETTING_CLEARED'=> '範例資料已開始清除，請稍後...',
	'JS_DEMO_DATA_ADDED' => '所有模組的範例資料已加入。',
	'JS_DEMO_DATA_CLEARED' => '所有模組的範例資料已清除。',
	'JS_HOME_DASH_BOARD_CLEAR_INFO'=>'注意: 您可以重啟範例資料從',
	'JS_SETTINGS_PATH'=>'設定 > 配置 > 配置編輯器。',
	'JS_PRINT' => '列印',
	'JS_SAVE_AS_IMAGE' => '另存為圖片',
	'JS_DIRECTORY_IS_EMPTY' => '資料夾為空',
	'JS_PLEASE_SELECT_AN_RELATED_TO_COPY_ADDRESS' => '請選擇一個潛在客戶/聯絡人模組來進行地址複製',
	'SINGLE_Leads' => '潛在客戶',
	'JS_SELECTED_LEAD_DOES_NOT_HAVE_AN_ADDRESS' => '所選的潛在客戶不包含欲複製的地址',
	'JS_INVALID_EMAILS' => '電子郵件無效',
	//'JS_DIRECTORY_IS_EMPTY' => '資料夾為空',
	'JS_INTERNAL_COMMENT' => '內部評論',
	'JS_INTERNAL_COMMENT_INFO' => '如果啟用了內部評論的勾選框，此評論只有CRM用戶可見。若要通報客戶(藉由可編輯的工作排程或客戶入口網) 請取消此勾選框',
	'JS_NO_LINE_ITEM' =>'Line items cannot be empty.',
	//'JS_INTERNAL_COMMENT' => '內部評論',
	//'JS_INTERNAL_COMMENT_INFO' => '如果啟用了內部評論的勾選框，此評論只有CRM用戶可見。若要通報客戶(藉由可編輯的工作排程或客戶入口網) 請取消此勾選框',

	'JS_NO_TAXES_EXISTS' => '稅值不存在',
	'JS_CONFIRM_TAXES_AND_CHARGES_REPLACE' => '您要更新此所選區域相對應的稅金與費用嗎？',
	'JS_PRINTTEMPLATEMODULE_DISABLED' => '列印樣板之模組已停用，無法執行操作',
	'JS_SENT_FOR_SIGNATURE' => '傳送簽名',
	'JS_FAILED_TO_SEND_FOR_SIGNATURE' => '傳送簽名失敗',
	'JS_SUITABLE_VTIGER_FIELD_NOT_AVAILABLE_FOR_MAPPING' => 'vtiger欄位不可用於映射',
	'JS_SAVED_SUCCESSFULLY' => '設定儲存成功',
	'phone' => '電話',
	'email' => '電子郵件',
	'url' => '網址',
	'home' => '家裡',
	'work' => '工作',
	'custom' => '自訂',
	'mobile' => '手機',
	'main' => '主要',
	'work_fax' => '傳真',
	'home_fax' => '家裡傳真',
	'pager' => 'BBcall',
	'profile' => '簡介',
	'blog' => '部落格',
	'home-page' => '主頁',
	'address' => '地址',

	// Cron
	'JS_NONE_OF_THE_VALUES_ARE_CHANGED' => '這些數據皆未改變',
	'JS_REMOVE_SYNC_CONFIRMATION' => '刪除同步僅會刪除現有的驗證，他不會刪除同步記錄。如果您再次與同一個Google帳戶同步，則會建立重複的記錄，您確定要刪除同步嗎？',

	//Recipient preferences labels
	'JS_LBL_GETTING_RECIPIENT_PREFS' => '讀取收件人偏好設定..',
	'JS_LBL_SAVING_PREFERENCES' => '偏好設定儲存中..',
	// Social Module Strings
	'JS_PLEASE_WAIT' => '請稍後...',
	'JS_SOCIAL_FIELD_ERROR' => '欄位必填',
	// Twitter Specific
	'JS_ADD_FAVOURITE_SUCCESS_MSG' => '新增推文到最愛列表成功',
	'JS_UNDO_FAVOURITE_SUCCESS_MSG' => '移除推文自最愛列表成功',
	'JS_UNDO_RETWEET_SUCCESS_MSG' => '取消轉寄成功',
	'JS_STATUS_UPDATE_SUCCESS_MSG' => '更新成功',
	'JS_TWEET_DELETE_MSG' => '狀態刪除成功',
	'JS_INVALID_TWITTER_HANDLER_NAME' => '無效的Twitter 用戶名',
	'JS_RELATION_ADDED_SUCESSFULLY' => '關聯添加成功',
	'JS_FAILED_TO_ADD_RELATION' => '關聯添加失敗',
	'JS_SOCIAL_POST_DELETE_CONFIRMATION' => '您確定要刪除？',
	'JS_EVENT_OR_TODO_ADDED_SUCCESS_MSG' => '事件/任務新增成功',
	'JS_LEAD_ADDED_SUCCESS_MSG' => '潛在客戶新增成功',
	'JS_OPPORTUNITY_ADDED_SUCESS_MSG' => '銷售機會新增成功',
	'JS_TICKET_ADDED_SUCESS_MSG' => '客服記錄新增成功',
	'JS_CASE_ADDED_SUCESS_MSG' => '案例新增成功',
	'JS_SELECT_OPTION' => '選擇一個項目',

	'JS_LOADING_PLEASE_WAIT' => '讀取中... 請稍後..',
	'JS_SAVING_PLEASE_WAIT' => '儲存中.. 請稍後..',
	'JS_DUPLICATE_EMAILS_PLEASE_CHECK' => '重複的電子郵件地址。請檢查',
	//'JS_USER_EXISTS' => '用戶已存在',
	'JS_ALERT' => '警告',
	'JS_SUCCESS' => '成功',
	'JS_REMOVE_MASS_TAG_WARNING' => '您確定要移除所選記錄的 %s 標籤',
	'JS_VIEW_ALREADY_EXISTS' => '試圖已存在',
	'JS_PLEASE_ENTER_NUMBER_IN_RANGE' => '請輸入範圍內數據',
	'JS_UPLOAD' => '上傳',
	'JS_TODO_ADDED_SUCCESS_MSG' => '任務新增成功',
	'JS_EVENT_ADDED_SUCCESS_MSG' => '事件新增成功',
	'JS_ACTIVE' => '啟用',
	'JS_SNOOZED' => '已延遲',
	'JS_INVALID_URL' => '無效網址',
	'JS_MAX_ALLOWED_CHARACTERS' => '允許最大字元數為',
	'JS_ARE_YOU_SURE_YOU_WANT_TO_DELETE' => 'A您確定要刪除嗎？',
	'JS_TAB_LABEL_EXCEEDS_CHARS' => '標籤長度應小於 %s 個字元',
	'JS_STARRED' => '取消追蹤',
	'JS_NOT_STARRED' => '追蹤',
	//Tags
	'JS_NO_TAG_EXISTS' => '無標籤存在' ,
	//help wizard
	'JS_HELP_AND_SUPPORT' => '幫助 & 支援',
	'JS_WHAT_DO_YOU_NEED_HELP_WITH' => '您需要甚麼幫助？',
	'JS_SUBMIT' => '提交',

	/** Vtiger7 translations **/
	'JS_ADD_MAX_15_ITEMS' => '您只能新增15個項目',
	'SINGLE_SLA' => '服務層級協議(SLA)',

	'JS_DEFAULT_ENABLED' => '默認啟用',
	'JS_DEFAULT_DISABLED' => '默認停用',
	'JS_EDIT_FIELDS' => '%s 欄位 & 佈局',
	'JS_MORE_VTIGER' => 'vtiger中有更多記錄需要同步',
	'JS_MORE_GOOGLE' => 'Google中有更多記錄需要同步',
	'JS_MORE_OFFICE365' => 'Office365中有更多記錄需要同步',
	'JS_TOKEN_EXPIRED' => 'Office365身份驗證已過期。點擊Office365登入按鈕重新授權。',
	//'JS_EDIT_FIELDS' => '%s 欄位 & 佈局',
	'JS_WISH_TO_PROCEED' =>"你確定要繼續嗎？",
	'JS_SWITCH_TO_OLD_LOOK_CONFIRMATION_MESSAGE' => '某些功能（包括通知，選項列表顏色，關註記錄）在舊版本中不可用。您可以通過從右上選單選擇新版本切換回新版本。',
	'JS_PROCEED_OLD_VERSION' => '沿用舊版本',
	'JS_STAY_WITH_NEW_VERSION' => '停留在新版本',

	//TimeAgo plugin Strings
	'JS_AGO' => '之前',
	'JS_FROM_NOW' => '從現在',
	'JS_LESSTHAN_A_MINUTE' => '不到1分鐘',
	'JS_A_MINUTE' =>'1 分鐘',
	'JS_MINUTES' => '分鐘',
	'JS_AN_HOUR' => '1 小時',
	'JS_HOURS' => '小時',
	'JS_A_DAY' => '1 天',
	'JS_DAYS' => '天',
	'JS_A_MONTH' => '1 個月',
	'JS_MONTHS' => '個月',
	'JS_A_YEAR' => '1 年',
	'JS_YEARS' => '年',
	'JS_TODAY' => '今天',
	'JS_TOMORROW' => '明天',
	'JS_YESTERDAY' => '昨天',

	'JS_CREATE_TASK' => '建立任務',

	//Notifications
	'JS_MENTION_ATLEAST_ONE_USER' => '至少提及一個用戶',
	'JS_LOADING' => '讀取中...',
	'JS_CASE_ACCEPTED_SUCCESSFULLY' => '案例接受成功',

	'JS_UPLOAD_SUCCESSFUL' => '檔案上傳成功',
	'JS_UPLOAD_FAILED' => '檔案上傳失敗',
	'JS_FAILED_TO_UPLOAD_FILE' => '檔案上傳失敗',
	'JS_DOCUMENT_CREATED' => '文件已建立',
	'JS_DOCUMENT_CREATION_FAILED' => '文件建立失敗',

	'JS_TEMPLATE_TEXT_EXCEEDS_LIMIT' => '樣板大小超出允許上限100 KB。請刪除樣板中的一些文字然後重試',
	'JS_PLEASE_SELECT_IMAGE' => '請選擇圖片',

	'JS_LBL_MY_PREFERENCES' => '個人偏好設定',
	'JS_LBL_MY_PREFERENCES_TEXT' => '配置您的個人偏好，包括時區、幣別、日期格式。您也可以從我的個人偏好選項上傳個人照片。',
	'JS_LBL_HELP' => '幫助',
	'JS_LBL_HELP_TEXT' => '點擊幫助按鈕查找指南和常見問答解答，並使用幫助選單下拉獲得Vtiger支持團隊的幫助',
	'JS_LBL_RESTART_TOUR' => '重新啟動導覽',
	'JS_LBL_RESTART_TOUR_TEXT' => '點擊此處重新開始進行導覽',
	'JS_GOOGLE_REMOVE_SYNC_CONFIRMATION' => '撤銷訪問權限只會移除聯絡人和日曆的現有Google身份驗證，但不會刪除同步的記錄。如果您再次與同一個Google帳戶同步，則會創建重複記錄。你確定要撤銷訪問嗎？',
	'JS_OFFICE_REMOVE_SYNC_CONFIRMATION' => '撤銷訪問只會刪除聯絡人，日曆和電子郵件的現有Office365身份驗證，它不會刪除同步的記錄。如果您再次與同一Office365帳戶同步，則會創建重複記錄。你確定要撤銷訪問嗎？',
	'JS_FOLLOW_RECORD' => '追蹤此記錄',
	'JS_FOLLOWING' => '追蹤中',
	'JS_UNFOLLOW_RECORD' => '取消追蹤此記錄',
	'JS_UNFOLLOWING' => '取消追蹤',
	'JS_RECORD_CREATED' => '記錄已建立',
	'JS_RECORD_UPDATED' => '記錄已更新',
	'JS_LIST_SAVED' => '列表已儲存',
	'JS_TAB_DELETED' => '已刪除',
	'JS_TAB_RENAMED' => '已更名',
	'JS_TAB_REORDERED' => '已重新排序',
	'JS_RECIPIENT_PREFERENCES_SAVED' => '收件人偏好設定已儲存',
	'JS_TASK_ADDED' => '任務已新增',
	'JS_MARKED_COMPLETED' => '標記為已完成',
	'JS_TASK_PRIORITY_CHANGED' => '任務優先級已更改',
	'JS_NO_PERMISSION_TO_MARK_AS_HELD' => '您沒有將此事件標記為已進行的權限',
	'JS_TAG_ADDED' => '標簽已新增',
	'JS_TAB_DELETED' => '已刪除',
	'JS_TAB_RENAMED' => '已重命名',
	'JS_TAB_REORDERED' =>'已重新排序',
	//Convert Lead
	'JS_CONVERT_LEAD_ERROR' => '您必須啟用客戶或聯絡人模組才能轉換潛在客戶。',

	'JS_CHECK_START_AND_END_DATE'=>'結束日期時間應大於或等於開始日期時間',
	'JS_CHECK_START_AND_END_DATE_SHOULD_BE_GREATER'=> '結束日期時間應大於開始日期時間',
	'JS_HOLD_FOLLOW_UP_SHOULD_BE_LESS_THAN_CURRENT_DATE'=> '保持跟進應大於或等於開始日期時間',
	'JS_DUPLICATES_DETECTED' => '檢測到重複！',

	'JS_IS' => '是',
	'JS_IS_NOT' => '不是',
	'JS_EQUALS' => '等於',
	'JS_NOT_EQUALS_TO' => '不等於',
	'JS_ONLY_LETTERS_AND_NUMBERS_ALLOWED' => '僅允許字母 (a-z)，數字 (0-9)和空格, 和空格',
	'JS_WIDGET_RESIZING_WAIT_MSG' => '小工具內容將在調整大小後載入。',
	'JS_SLA_FULFILLMENT_RATE' => 'SLA 達成率',
	'JS_TICKET_COUNT' => '案例數',
	'JS_CASES_AGE_HOURS'=>'案例經歷（小時）',
	'JS_BACKLOG'=> '積壓',
	'JS_AND' => '和',
	'JS_SEQUENCE_UPDATED_SUCCESSFULLY'=>'序列更新成功',
	'JS_VIEW_RECORD' => '查看記錄',
	'JS_HIDE'=>'隱藏',
	'JS_SHOW_ALL'=>'顯示全部',
	'JS_SHOW_LESS' => '顯示較少',
	'JS_SHOW_MORE' => '顯示更多',

	'JS_KANBAN_ANCHORS_LIMIT_MESSAGE' => '您最多只能選擇10個階段', 
	'JS_KANBAN_NO_MORE_RECORDS' => '找不到更多記錄',
	'JS_DELETED' => '已刪除',
	'JS_CLEAR_TEMPLATE_CONTENT_RECIPIENTS'=>'更改模組將會清除所選樣板與收件人欄位，您確定要繼續嗎？',
	'JS_WORKFLOW_ACTIONS_LIMIT_EXCEEDED' => '超過此版本中的上限。',
	'JS_RECORD_CREATION_LIMIT_EXCEEDED' => '建立記錄 - 超過此版本的上限。',
	'JS_KANBAN_NO_ANCHORS_CONFIGURED' => "您沒有為您的銷售渠道定義任何銷售階段。",
	'JS_KANBAN_NO_ANCHORS_CONFIGURED_NON_ADMIN' => "沒有為您的銷售渠道定義任何銷售階段。請聯繫您的管理員，根據您的銷售流程定義銷售階段。",
	'JS_UPDATE_MAPPING_CONFIRMATION' => 'CSV檔案中有一些配對的列項無法儲存在此映射。你想用新的列項更新這個映射嗎？',
	'JS_MAPPING_UPDATED' => '新映射已更新。',
	'JS_MAILCHIMP_REMOVE_SYNC_CONFIRMATION' => '取消訪問將刪除現有的 MailChimp 身份驗證，它不會刪除同步的記錄。您確定要撤銷訪問權限嗎？',
	'JS_WARNING' => '警告',
	'JS_CANT_SELECT_LEAD' => '無法選擇相關的潛在客戶',
	'JS_CANT_SELECT_CONTACT' => '無法選擇相關的聯絡人',
	'JS_MSG_EMPTY_RB_CONFIRMATION' => '您確定要從資料庫中永久移除所有已刪除的記錄嗎？',
	'JS_LBL_RESTORE_RECORDS_CONFIRMATION' => '您確定要恢復記錄嗎？',
	'JS_COMMENT_POSTED_SUCCESSFULLY'=>'評論發布成功',
	'JS_SHARED_PUBLICLY_WITH'=>'公開分享給',
	'JS_SHARED_PRIVATELY_WITH'=>'私人分享給',
	'JS_MAIL_SENT_SUCCESSFULLY'=>'郵件發送成功',
	'JS_SHARED_PUBLICLY_TITLE'=>'公共會話也可以由連結郵件信箱的非用戶查看，如果他們有權訪問相關聯絡人，銷售機會..等',
	'JS_SHARED_PRIVATELY_TITLE'=>'私人會話只能由其連結到的郵件信箱的用戶查看。',
	'JS_LINKED_RECORDS_SUCCESS'=>'已連結的記錄更新已成功',
	'JS_MAIL_DRAFTED_SUCCESSFULLY'=>'列入草稿成功',

	//Custom view default sort translations.
	'JS_PLEASE_REMOVE_ONE_FIELD_FROM_CHOOSE_COLUMNS_LIST_TO_ADD_DEFAULT_SORT_FIELD' => '列表視圖中只允許使用16列，包括排序列。',
	'JS_DEFAULT_SORT_NOTIFY' => '列表現在依默認排序列排序 ',
	'JS_ENABLED' => '已啟用',
	'JS_DISABLED' => '已停用',
	'JS_ONLY_ALLOWED_USERS_ARE_ALLOWED_TO_DO_ACTION'=>'我們無法將會話標記為未讀/已讀/刪除/完成/私人/公開，因為會話與您無關',
	'JS_SHARED_WITH'=>'共享給',
	'JS_DEFAULT_DASHBOARD_TOOLTIP' => '將此資訊主頁重新排序為第一個標簽，將其設為默認值！',
	'JS_SET_DEFAULT_TAB' => '被設置為您的預設表板',
	'JS_PASSWORD_MISMATCH_ERROR' => '請重新輸入密碼。 "新密碼"和"確認密碼"不相同。',
	'LBL_LIST_DELETE_CONFIRMATION' => '您確定要刪除嗎？',
	
	
);
/*+***********************************************************************************
 * 臺灣繁體中文語言包 - Vtiger 系統主體
 * 版本: 7.1.0 
 * 作者: Loki Jiang | https://www.facebook.com/groups/vTigerCRMtoTaiwan/
 * 更新日期: 2018-03-15
 *************************************************************************************/